### PR TITLE
Update SharkNFTs

### PR DESCRIPTION
**Pull request by PatingRA**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Could we have a link to a twitter/webpage which have provided the Policy ID's you are requesting.

Thanks.

**Comment by PatingRA** [comment]
Hi.

My apologies for the delayed response.

Here are some policy IDs we want to get verified please.

https://twitter.com/sharkNFTs/status/1443323411099357187
https://twitter.com/sharkNFTs/status/1443323414245089286

This is the tweet when we said we asked permission from Low Poly Project to
add add Low Poly Manta Ray under Shark NFTs instead of Low Poly Project
because that one was for Shark NFTs.
https://twitter.com/sharkNFTs/status/1437083466428928004

And this one is our request for Proof of Shark S1 verification.
https://github.com/Cardano-NFTs/policyIDs/pull/1823

Thank you.

**Comment by MaxJewell** [comment]
Only the last 2 Policy ID's are available to view on these twitter links.
Could you send links for the other ones and we can put you through.

Many thanks.

**Comment by PatingRA** [comment]
Hi, please check these two tweets.
These are separate tweets.

https://twitter.com/sharkNFTs/status/1443323411099357187
- This one includes Proof of Shark* and Low Poly Manta Ray**.

https://twitter.com/sharkNFTs/status/1443323414245089286
This includes Shark for Good** and Shark Contract**.

*https://github.com/Cardano-NFTs/policyIDs/pull/1823
**https://github.com/Cardano-NFTs/policyIDs/pull/757

**Comment by MaxJewell** [comment]
These still are not the correct Policy ID's

**Comment by PatingRA** [comment]
Hi. The tokens that need to be updated are in those tweets.
The other ones are already verified.
The other policy IDs also need to be verified.
Please let me know which ones are the wrong policy IDs.

**Comment by MaxJewell** [comment]
All the Policy ID's that you know of that are verified already please can you take them out then I can verify the last two for you.

**Comment by PatingRA** [comment]
I just checked CNFT.io.
Now the other verified policy IDs are not showing up.

**Pull request merged**
