### PR TITLE
Isometric World S2

### PR DESCRIPTION
**Pull request by IsometricWorld**
https://www.isometricworld.eu/about 

https://twitter.com/IsometricWorld_

https://discord.gg/mjDKWSvrYm

### CODE REVIEW

**Comment by IsometricWorld** [comment]
I have validated the JSON and the website saw no problems not sure why its saying checks failed

Link below to Pull Request posted on twitter
https://twitter.com/IsometricWorld_/status/1468281235759845389?s=20

**Comment by MaxJewell** [comment]
Morning,
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by IsometricWorld** [comment]
I followed all the steps you aren't helping me your just sending out a
generic message.

**Comment by MaxJewell** [comment]
Open a new pull request following the steps.

**Pull request closed without merging**
