### PR TITLE
Added cyberpunkcars

### PR DESCRIPTION
**Pull request by hideakidesu09**
https://twitter.com/cyberpunkcars

### CODE REVIEW

**Comment by KaiNFT** [comment]
Hi Contributor,

Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

**Comment by hideakidesu09** [comment]
my policy id 3b77329f889f5ace6449fb90612e6037e6388fa1291e7114cbf73952 ,

  060ff4fae879f02fc504b0a5802baf758405f7c4575f4c22c729a3a2 ,

a7e76f079c39221c728cf29bf6aabcafc4fdf60b578ce74196283c0c ,

cab268293450221f1bac51638f4e56be17f635f6c35a57fbc8e60a40 ,
                    da2370344ff58f02c7ea200870754f46fd0f596531b5e4bf09798d26
my twitter : https://twitter.com/cyberpunkcars
                  Thank you.


ในวันที่ พฤ. 18 พ.ย. 2021 เวลา 03:00 KaiNFT ***@***.***>
เขียนว่า:

**Comment by hideakidesu09** [comment]
Updated

**Comment by AnOnlineGuy** [comment]
We have made another change to GitHub that you should be aware of. 

I need you guys today to go through all the PRs and close them with this message. 

‘Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
