### PR TITLE
Fractal Fuzion

### PR DESCRIPTION
**Pull request by badbios420**
Fractal Fuzion NFT's are always minted on Tokhun.io
instagram is: https://www.instagram.com/fractalfuzion/

### CODE REVIEW

**Comment by badbios420** [comment]
Twitter is https://twitter.com/FractalFuzion
all Policy ID's have been listed there
Please add Fractal Fuzion to Verified List
Thank you NFT boss

**Comment by TomStray** [comment]
Dear Contributor, please add commas at the end of lines 4 to 9 and add a closing square bracket to line 14 and a closing } bracket to line 15.

**Comment by thingticketNFT** [comment]
[fractalfuzion.txt](https://github.com/Cardano-NFTs/policyIDs/files/7274145/fractalfuzion.txt)

add your new policies to this text file. p sure the syntax is correct as i copied a merged commit and modified it for you. be sure to double check the info i put in there. :)

**Comment by badbios420** [comment]
{
    "project": "Fractal Fuzion",
    "tags": [
        "Fractal Fuzion",
        "fractal fuzion",
        "fractal fusion",
        "fractalfuzion",
        "fractalfusion",
        "Liquid Metal Plasma",
        "Atomizer" ,
        "Chimera",
        "Minotar",
        "Fractal Rendering",
        "Galactic Supercluster",
        "Flamethrower",
        "Disintegration",
        "Fuzion Console",
        "phoenix",
        "Event Horizon",
        "CodeBreaker",
        "Brainstorm",
        "Cardano Summit 2021 Signature Cap",
        "Starlink",
        "ionosphere",
        "Reversal",
        "Futuristic",
        "hallucination",
        "Biohazzard",
        "Trichome",
        "Dimension",
        "Simulation",
        "Gravitron",
        "Explosion",
        "Catastrophic",
        "Love420",
        "Cataclysmic",
        "Tentacles",
        "String Theory",
        "Construct",
        "plutonium",
        "Superplex",
        "Synthetic",
        "Dyson sphere",
        "Calculus",
        "Radiation",
        "Cluster",
        "Cosmic Leaf",
        "Super Cell",
        "Purple Clouds",
        "Stellar",
        "Spaceship",
        "Galactic",
        "Pyramid",
        "Paradox",
        "Stardust",
        "Red Dwarf",
        "Creature",
        "Fractals",
        "Blockchain",
        "jasmine",
        "eucalyptus",
        "Universal",
        "Glitch Logo",
        "Gravity",
        "Dark Matter",
        "Photobomb",
        "Titanium",
        "Freeze",
        "Organic",
        "Meteor",
        "Weapon",
        "Singularity",
        "Cosmos",
        "Diamond",
        "Quasar",
        "nucleus",
        "Ruby",
        "Sapphire",
        "Distortion",
        "Time",
        "Emerald",
        "BrainDrain",
        "Hydrogen",
        "Derezzed",
        "Vibrations Series",
        "Telepathy",
        "Ragnarok",
        "Elemental",
        "Vector",
        "Pineal",
        "Proton",
        "Tracer",
        "Neural",
        "Lazers",
        "Parallels",
        "Diode",
        "Circuitry",
        "eclipse",
        "Godspeed",
        "Core",
        "Helium",
        "Holy",
        "Nebula",
        "Black Magic",
        "Atomic Portal",
        "Vortex",
        "Mega",
        "ultra",
        "intersection",
        "Fractal Grid",
        "Palace",
        "Big Brain",
        "Rising Sun",
        "Matrix",
        "Ooze",
        "Grey Matter",
        "Electron",
        "Teleport",
        "Spitfire",
        "Ultima",
        "Freezer",
        "Nova",
        "Phototron",
        "Bios",
        "Time Crystals",
        "galaxy",
        "Vibrations",
        "Chakra",
        "The Mothership",
        "King Machine",
        "illuminated",
        "Tri Star",
        "Minds Eye",
        "Line Fried",
        "FractalLit"                                                     
    ],
    "policies": [
        "cd7125bd8fe7b40aae2baa7d28812774d0c6359627702e386c28152e",
        "8e43ec33c2bdbac798ff29d8c844828b18c9dfce6a3b0adca2104417",
        "41045f7a5df6c17cf1cc7ea51921570df3460223b0837ccba792fac1",
        "fe6c5e49f23a6465416cbe1072d574e64dc802ed3e0e12289701b7d6",
        "e0b9b35bc4fdb96032ff4ecde146ecfc304873b28020792d5cb583b7",
        "fe2e3f2f51c1c9f7c5b0bb71ca60f5eb923d096e8d4a42c50ea544b2",
        "8d2c41fed9a8e6317020712b007eb8b5587107879832a2d79070fad8"
    ]
}

**Comment by thingticketNFT** [comment]
[FractalFuzion page on tokhun.io](https://tokhun.io/fractalfuzion)
[@FractalFuzion on twitter](https://twitter.com/FractalFuzion)

@CNFT-io @TomStray @nicolasayotte @MaxJewell Thank you.

**Comment by TomStray** [comment]
Dear Contributor, please can you indent the code in the same way that you had it before you changed the commit.

**Comment by badbios420** [comment]
i attempted to indent not sure if done correctly please advise

**Pull request merged**
