### PR TITLE
Added Projects

### PR DESCRIPTION
**Pull request by CNFTGal**

### CODE REVIEW

**Comment by CNFTGal** [comment]
PunksterArt Project: 

Twitter proof: https://twitter.com/PunksterA/status/1432431635727781893
Website: https://punksterart.com/
Discord: channel #policy-verification on https://discord.gg/4zZhpTvuX3

**Comment by fellipute** [comment]
@itsmestale can we merge this PR with Punksterart's PolicyID? The sales are increasing in the aftermarket and it would be good to have the verified status on cNFT.io.

Thanks!

**Review by CNFTGal — COMMENTED** [review]
Twitter: https://twitter.com/GenArtCardano
Policy Proof: https://twitter.com/GenArtCardano/status/1441704679965007876
Discord: discord.gg/RKrPaTm8f3

**Comment by CNFTGal** [comment]
@nicolasayotte can you help us out on this ?

**Comment by CNFTGal** [comment]
EA Art's Project: 
Policy Proof: https://twitter.com/Eduardogoveiags/status/1397279667141361668
Twitter: https://twitter.com/Eduardogoveiags
Website: https://www.eaarts.net/

**Comment by CNFTGal** [comment]
@itsmestale and @nicolasayotte the 3 projects from this pull have the information/proof about policy id. 

Is this enough or is something else needed?

thanks in advance

**Pull request merged**
