### PR TITLE
Update policies for thiscrazylife

### PR DESCRIPTION
**Pull request by ian6868**
Added new policy for thiscrazylife.

### CODE REVIEW

**Comment by MaxJewell** [comment]
Please leave a link to twitter/webpage for proof with policy ID's.

**Comment by ian6868** [comment]
Hi,

My policies can found on my website https://sites.google.com/view/thiscrazylife/home and my discord server https://discord.gg/asR7ZpKwad.

Thank you
Ian


________________________________

**Comment by MaxJewell** [comment]
Thanks for the response. Only one policy ID can be found. However all policy ID's will need to be provided before merge.

**Comment by ian6868** [comment]
I'm sorry I don't understand? All my policies are listed on both discord and the webpage. On the webpage you just need to scroll down. I think you were looking only at the latest drop. Below that is all my policies. They are also all listed on discord. 
dis1
proof1

Thank you
Ian

**Comment by ian6868** [comment]
If needed I can create a separate page for the policies on my website just let me know but they are all currently listed there.

Thank you
Ian

**Comment by ian6868** [comment]
I went ahead and created a new page on my website already. At the top on the right corner there is a Policies link now. I hope that makes it easier.

Thank you
Ian

**Pull request merged**
