### PR TITLE
Pixel India 

### PR DESCRIPTION
**Pull request by TheCaptRay**
Added Pixel India Project to verify

Twitter - https://twitter.com/TheCaptRay

### CODE REVIEW

**Comment by TheCaptRay** [comment]
https://twitter.com/TheCaptRay/status/1470089478958055425

**Comment by gobboo** [comment]
Seems you deleted your commit, do you still want it added ?

**Comment by TheCaptRay** [comment]
I do want it merged. I created two commits by mistake. One of them is already merged Pixel India. you can find the commit. :)
-- 
TheCaptRay




30 Dec 2021, 19:24 by ***@***.***:

**Comment by TheCaptRay** [comment]
Pixel India is already merged but my project shows unknown project on CNFT and doesn't show as verified.

https://github.com/Cardano-NFTs/policyIDs/pull/4856

https://github.com/Cardano-NFTs/policyIDs/pull/4824 Older commit that I closed because my syntax was wrong. But the one above is already merged, even then the project doesn't show as verified.

-- 
TheCaptRay




30 Dec 2021, 19:24 by ***@***.***:

**Pull request merged**
