### PR TITLE
Please create unshifts.art

### PR DESCRIPTION
**Pull request by TylorVB**
A direct-to-buyer, commission-based project called unshifts.art by TylorVB. unshifts are artfully deconstructed unsig_algorithms.

### CODE REVIEW

**Comment by TylorVB** [comment]
Confirmation tweet: https://twitter.com/TylorVB/status/1431772470361612288

**Comment by TomStray** [comment]
Dear Contributor, please add a closing square bracket to the tags section on a new line below line 6. This closing bracket also needs a comma directly after it.

**Comment by TylorVB** [comment]
Thank you for the direction! (And apologies.) I have now done so.
Please let me know if anything else is incorrect and I'll fix immediately.

**Comment by TomStray** [comment]
Dear Contributor, I haven't got another commit through with the changes that you have made.

**Comment by TylorVB** [comment]
I guess I don't know how that works. New to Github. Will see if I can
figure it out.

**Comment by TylorVB** [comment]
Would you be so kind as to tell me the steps I should take from this link
in order to send a "commit". I added the bracket and comma in a comment.
Apologies for the ignorance.

https://github.com/TylorVB/policyIDs/commit/3ddf04f15df25493a9cbf4927a9d2bb3ea009c4d

**Pull request closed without merging**
