### PR TITLE
The Rats

### PR DESCRIPTION
**Pull request by TheRatsCNFT**
https://theratscnft.com/

https://twitter.com/TheRats_CNFT/status/1492262639245877258?s=20&t=99l3HRMe65N5PVo3bM7bbQ

http://discord.gg/gNm4GPWdpq

### CODE REVIEW

**Comment by MaxJewell** [comment]
There are no Policy ID's on any social media, please add them to any of your social media's you have provided. 
Thanks

**Comment by TheRatsCNFT** [comment]
Thanks we have updated our socials

**Comment by TheRatsCNFT** [comment]
We have put policy ID on socials

**Comment by TomStray** [comment]
Dear Contributor, I cannot see your policy IDs on your website or twitter.

**Comment by TheRatsCNFT** [comment]
It is on twitter and discord and will be on website when our web designer is updating it now

**Comment by TheRatsCNFT** [comment]
Can you confirm when we are being listed as our mint is hours away

**Comment by KaiNFT** [comment]
Closed due to inactivity

**Pull request closed without merging**
