### PR TITLE
Steve3p_0 CNFT

### PR DESCRIPTION
**Pull request by Daawesomedrummer098**
Twitter Handle : @Steve_3p0_. Cheers! Thanks for all the good work you do for the community

### CODE REVIEW

**Comment by Daawesomedrummer098** [comment]
Im wanting to commit my Policy ID. Let me know if there is any feedback that you have with this request. Thanks for your time

**Comment by thingticketNFT** [comment]
[steve_3p0.txt](https://github.com/Cardano-NFTs/policyIDs/files/7274272/steve_3p0.txt)

**Review by Daawesomedrummer098 — COMMENTED** [review]
{
    "project": "Steve3p_0",
    "tags": [
        "Steve3p_0",
        "Steve3p0",
        "Steve 3p0",
        "Steve 3p_0",
        "Steve 3po",
        "Steve 3p_o",
        "Steve",
        "3p_0"
    ],
    "policies": [
		"8dbef3ae32a5ac935172ab84cb7a3540603207892c9ab63956490086"
          ]
}

**Comment by Daawesomedrummer098** [comment]
@CNFT-io @TomStray @nicolasayotte @MaxJewell Thank you

**Comment by thingticketNFT** [comment]
[steve3p_0 website: steve3p_0.info](https://www.steve3p0.info/)
[link to policy id 8dbef3ae32a5ac935172ab84cb7a3540603207892c9ab63956490086 on steve3p_0 wesite](https://www.steve3p0.info/verification)
[link to @steve3p_0_ twitter profile](https://twitter.com/Steve_3p0_)
[link to twitter announcement of PR](https://twitter.com/Steve_3p0_/status/1444738202808434690?s=20)

**Pull request merged**
