### PR TITLE
Science Market project

### PR DESCRIPTION
**Pull request by Beerpot**
Policies are added

### CODE REVIEW

**Comment by MaxJewell** [comment]
This is a good start.
What I will need you to do is to give me a link to a twitter/webpage with the Policy ID's on them to verify your identity.

Many thanks.

**Comment by Beerpot** [comment]
Hi Max, 
Thanks for the reply. 

- Twitter page created: https://twitter.com/NftScience/ 
- SEX/FIB images are added. 

Once you assess the novelty of the idea. I will start populating with Images.

Best regards,
Orcun

**Comment by Beerpot** [comment]
Hi Max, 
I had a silly editorial! I am sure you captured the fact that I meant SEM ( Scanning Electron Microscope!!). When do you believe I can get the tags approved? 
Kindest regards,
Orcun

**Comment by Beerpot** [comment]
> This is a good start. What I will need you to do is to give me a link to a twitter/webpage with the Policy ID's on them to verify your identity.
> 
> Many thanks.

Hi Max,
I had a silly editorial! I am sure you captured the fact that I meant SEM ( Scanning Electron Microscope!!). When do you believe I can get the tags approved?
Kindest regards,

**Pull request closed without merging**
