### PR TITLE
Added imwiththealiens

### PR DESCRIPTION
**Pull request by imwiththealiens**

### CODE REVIEW

**Comment by CNFT-io** [comment]
Please can you provide a link as to where your project is, like Twitter for example. 
Somewhere we can verify this policy belongs to you!

**Comment by imwiththealiens** [comment]
Of course!

Here is my Twitter handle and also my Instagram.

twitter: @imwththaliens

ig: @imwiththealiens

**Comment by imwiththealiens** [comment]
Hi team:

Just wanted to follow up on the below I provided my handles and was hoping to get verified please let me know if there’s anything else you’d like or need. Happy to direct message you from my handles account if needed.

Excited to join the Cardano ecosystem finally! :)

Thanks,

Josimar

**Comment by imwiththealiens** [comment]
THank you guys it works i see it verified. Quick question if i want to add
more art pieces under IMWITHTHEALIENS project do i have to do the same
steps via github and add the different policy ids everytime so that they
are also verified?

Thanks,

Josimar

**Pull request merged**
