### PR TITLE
Add please Brush World

### PR DESCRIPTION
**Pull request by SpilbergUA**
I called this collection “Brush World”. I created 6 pictures with special seeing of some things. Every picture has 10 pieces, divided between few platforms for NFT selling. Collect all pictures of this collection and open your mind for a new seeing of art. Also, you can print this works and beautify your home.
#1 – CONFRONTATION – 10 pieces
#2 – BIRD FLIGHT – 10 pieces
#3 – DEEP – 10 pieces
#4 – MARGHERITA – 10 pieces
#5 – DANTE – 10 pieces
#6 – AFTER DARK – 10 pieces
You can contact me in Twitter: https://twitter.com/SpilbergUA

### CODE REVIEW

**Comment by SpilbergUA** [comment]
This is link of mu twit https://twitter.com/SpilbergUA/status/1440296295587975180

**Comment by SpilbergUA** [comment]
@MaxJewell, @nicolasayotte and @TomStray  Hi guys! Can you Check it?

**Comment by SpilbergUA** [comment]
Also tweeted about this pull request here: https://twitter.com/SpilbergUA/status/1440953010276945923

**Comment by SpilbergUA** [comment]
Hi. Can you check this? I doing it first time. Don't know I did all right or not. @Dean00K

**Comment by SpilbergUA** [comment]
@itsmestale  Hi! I saw you video on YouTube,  but still can't understand how it works.... Can you check my request? It is here a lot of time.

**Comment by TomStray** [comment]
Dear Contributor, please unindent line 20 so that it is in line with line 19.

**Comment by SpilbergUA** [comment]
@TomStray  Check please if I understood you right. And question for the future: I can just add in this code new policies of the new NFTs of this collection?

**Comment by TomStray** [comment]
Dear Contributor, please can you click just before the speech mark at the very start of line 19 and then press the Tab key to indent it once.

**Comment by SpilbergUA** [comment]
@TomStray  Done

**Pull request merged**
