### PR TITLE
Added - Captivate: Cardano Edition

### PR DESCRIPTION
**Pull request by FrostloreGames**
Thank you!
Frostlore Games

### CODE REVIEW

**Comment by FrostloreGames** [comment]
Website & Twitter:
www.frostloregames.com
@FrostloreGames

**Comment by KaiNFT** [comment]
Hi Contributor,

Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

**Comment by FrostloreGames** [comment]
Hi KaiNFT, here is evidence of my Policy ID via website (just have to
scroll down a bit):

https://frostloregames.com/early-access/

& Twitter Account:

https://twitter.com/FrostloreGames

Thanks so much for your help!

Brian Lee

**Comment by FrostloreGames** [comment]
Thank you so much KaiNFT, I really appreciate it!

All the best,

Brian

**Pull request merged**
