### PR TITLE
Create Cardano Help Policy

### PR DESCRIPTION
**Pull request by rockandrollrebellion**
Help policy initial creation.

### CODE REVIEW

**Comment by rockandrollrebellion** [comment]
Pull requst linked on https://twitter.com/CardanoHelp

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your twitter.

**Comment by rockandrollrebellion** [comment]
Done. It's set in my profile description temporarily.
https://twitter.com/CardanoHelp

-J

**Comment by TomStray** [comment]
Dear Contributor, the policy ID you have put in your bio is not the same one that is in your code. As well as this, please make the change to the code that I mentioned in my previous message.

**Comment by rockandrollrebellion** [comment]
Created new pull request. Used json formatter since I didn't see that line
8, 9 was not parallel. Thanks for your patience.

https://github.com/cardano-foundation/cardano-token-registry/pull/630

-J

**Comment by rockandrollrebellion** [comment]
Looks like I'm getting that sequence number issue again. I don't understand
what needs to be done.

-J

**Pull request closed without merging**
