### PR TITLE
Added WordsNFT

### PR DESCRIPTION
**Pull request by darrit**

### CODE REVIEW

**Comment by darrit** [comment]
Our tweet for the pull request:
https://twitter.com/_wordsnft_/status/1457967085913522179

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your twitter or discord so I can verify.

**Comment by darrit** [comment]
Hey TomStray,

I added now to discord.

Thanks

Am Di., 9. Nov. 2021 um 16:52 Uhr schrieb TomStray ***@***.***

**Comment by darrit** [comment]
Hello @TomStray could you please verify it until tomorrow? Its very imoportant because we wanted to launch tomorrow with verifies collection. I've sent you already directly after creating PR the link to the tweet with our policy id here to the comments above and add yesterday the policy id to discord in the channel policy-id and gave you rights to that channel, if you want to write something in this channel.

Hope to hearing from you very soon.

Thank you very much for your work!!!
Best regards

**Pull request merged**
