### PR TITLE
Adding 9 policies and deleting 5

### PR DESCRIPTION
**Pull request by marcusoregano**
2 policies I've tried to add 22 days ago:
#607

1 policy I've tried to add 15 days ago:
#822

3 policies I've tried to add 10 days ago: #1060

1 policy I've tried to add 6 days ago: #1330

Add 1 new Policy.

Also delete
        "56d65af080d23193e98368f360c38ccad21ee9420e4efe9352b40f0e",
        "0be24507384a5e4cf8c4fd68613875f0c9b96160ba6fec8c8fb03ab5",
        "65a961a7a0c6917c852e227400cba36cc0e77194ac2fed00901c90d5",
        "8e5c3b65fd28d30f7350045604def94cdcad3d8ad7ad3a8cb43b3349",
        "9afdccad2fdbd57f226971bbb9c44ee2ffaf6d85214d5bc8faa15d1a",
These 5 policies (to delete)  don't meet the NFT standard and may cause confusion with our community. We plan to airdrop NFTs to these holders in the near future.

Thanks for the help!

### CODE REVIEW

**Comment by CelDivision** [comment]
@CNFT-io i am still learning, and doing so by paying attention to the pulls that are successful and which ones are not. i cant quite understand how this pull request works in terms of the criteria laid out in the tutorial. im so new to this im not even sure if my questions are valid but; 1. are some users exempt from linking to their project to prove the policys, or did you have the onerous task of following each of the nested policy links? 2. the also delete section just has policies, does the system just automatically know which file to remove them from?
apologies if these are ultimate-newb questions but i am an artist :)

**Comment by CNFT-io** [comment]
It's ok, we are working on a new solution for this! as it is a pain! a verification website will be up one day soon which will help!

**Comment by CelDivision** [comment]
> It's ok, we are working on a new solution for this! as it is a pain! a verification website will be up one day soon which will help!

happy to help where i can.

**Comment by pehcastro** [comment]
> It's ok, we are working on a new solution for this! as it is a pain! a verification website will be up one day soon which will help!

With each passing day we have more projects accumulating and a bigger approval list, I'm looking forward to seeing a system that works better or someone responsible for checking and merge pull requests. Good luck at work guys.

**Pull request merged**
