### PR TITLE
Added Nigiri by Cardano Foodies

### PR DESCRIPTION
**Pull request by cardanoFoodies**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments in the json file and provide proof of the Policy ID via website or social media so I can merge the pull request.

**Comment by cardanoFoodies** [comment]
Hi,

1) Regarding the JSON validation, I can see it has failed but the syntax is correct so I do not understand what to change. Should I remove the tags as this feature is no supported anymore maybe?

2) You can see our policy ID on our webpage  at the very bottom: https://cardanofoodies.com/
We also tweeted the same day we did the pull request from the official twitter account: https://twitter.com/CardanoFoodies/status/1458524515491799052

Thanks for the help!

**Comment by cardanoFoodies** [comment]
Ok, I think I have spotted the problem with the JSON file. It should start with array, my bad.

**Comment by cardanoFoodies** [comment]
Should be good now. Sorry for the inconvenience.

**Pull request merged**
