### PR TITLE
Update Alphatron

### PR DESCRIPTION
**Pull request by royalty007**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website and make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue specifically, please use a JSON validator; https://jsonlint.com/ .

**Comment by royalty007** [comment]
Hi

Can I provide you the details here ? Cuz I am not sure if I am managing
GitHub correctly.

Thanks

**Comment by royalty007** [comment]
Hi

Website:
www.alphatrontoys.com

Instagram
https://www.instagram.com/alphatrontoys/

Username:alphatrontoys

**Comment by KaiNFT** [comment]
"type should be array"

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
