### PR TITLE
Shapeverse

### PR DESCRIPTION
**Pull request by Sh4pes**
https://twitter.com/sh4pes1/status/1471869158191214593

https://twitter.com/sh4pes1

https://discord.gg/NM5czmekuV

### CODE REVIEW

**Review by Sh4pes — COMMENTED** [review]
errors in code

**Comment by KaiNFT** [comment]
Dear Contributor,

Please correct the syntax error in your JSON file in order for me to merge the pull request.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Comment by Sh4pes** [comment]
> Dear Contributor,
> 
> Please correct the syntax error in your JSON file in order for me to merge the pull request.

sorry, how can I fix it?. I dont even know what the error is?. Thanks

**Pull request closed without merging**
