### PR TITLE
NHL Pixel Art

### PR DESCRIPTION
**Pull request by Amunt60740**
-=NHL Pixel Art=-

To see the entire flash serie >>>

https://easycnft.art/en/flash/2078

### CODE REVIEW

**Comment by MaxJewell** [comment]
You will need to provide a list with all the Policy ID's on them. 
Thanks

**Comment by Amunt60740** [comment]
> You will need to provide a list with all the Policy ID's on them. Thanks

How can i provide this list to you please ?

**Comment by MaxJewell** [comment]
On your website would be perfect. If you do not want to keep it on there after I have verified it that is fine, you can remove it after.

**Comment by Amunt60740** [comment]
> On your website would be perfect. If you do not want to keep it on there after I have verified it that is fine, you can remove it after.

I don't have website... I must ?

**Comment by Amunt60740** [comment]
> If you could add them onto the website you have given a link to that would be great. If not, a twitter/discord with all of them on would be fine too.

Ok thank you for your advices. So my policy project is now verified ?

**Comment by MaxJewell** [comment]
Once the policies are on the website, I can check them and merge you (verify).

**Comment by Amunt60740** [comment]
> Once the policies are on the website, I can check them and merge you (verify).

Hi you can find all the policies on this website >

http://www.pixelartseries.com

**Pull request merged**
