### PR TITLE
Added DesertStories

### PR DESCRIPTION
**Pull request by NOMAGIK**
I am NOMÅGIK, an audio-visual artist from Greece. My project DesertStories is inspired by multiple cultures from the saharan desert and north Africa in general. I do colourful and organic collages, trying to bring ancient traditions back to life in a modern way. My music has exactly the same approach and you can search for NOMÅGIK on all social platforms in order to get a better idea of my philosophy.

### CODE REVIEW

**Comment by NOMAGIK** [comment]
Pool.pm adresses

The Amazigh Frida: 
https://pool.pm/708b196829d23293258e0f2257401bb9cbaa1852f22e1087ff9d9bfe.TheAmazighFrida
The Cosmic Revolution: https://pool.pm/3f228f6540fd36972f0081c4134b6b3f32fac369275ebee2a957a29a.TheCosmicRevolution
The Gothic Amazigh: https://pool.pm/cbddc2d2cce905ab88ba23176bfb6d5c291724f66c64ecf78c7c9e5b.TheGothicAmazigh

**Comment by NOMAGIK** [comment]
Website of project: www.nomagik.com/nft

**Comment by Dean00K** [comment]
Thank you for an excellent github pull request. This ticks all our boxes. OMG, thank you. The verification requests I'm dealing with are painful. Yours was a breathe of fresh air. Do you mind if I use this as an example of what's required?

**Comment by NOMAGIK** [comment]
Hi @Dean00K,

thanks for that man, feel free to use my request as an example, no problem at all. 

Sending you many greetings from athens.

**Pull request merged**
