### PR TITLE
Added put your hands up

### PR DESCRIPTION
**Pull request by KornerzZZ**

### CODE REVIEW

**Comment by CNFT-io** [comment]
Please add your policy id to your twitter bio, or post them from your account and link your tweet :)

**Comment by KornerzZZ** [comment]
I have added it to my twitter profile, please check it out.

**Comment by KornerzZZ** [comment]
https://twitter.com/kornerzZZZ?s=09

**Comment by CNFT-io** [comment]
Thanks!

**Comment by KornerzZZ** [comment]
Hey, I'm not good at github, I'd like to ask.


If I put a new policy ID in the same project, can I add the code at all?

**Pull request merged**
