### PR TITLE
Please add my CartoMetaverse project

### PR DESCRIPTION
**Pull request by OzPerle**
Twitter handle for this project is https://twitter.com/MetaverseCarto

### CODE REVIEW

**Review by OzPerle — COMMENTED** [review]
updated

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide proof of Policy ID via website or social media so I can merge the pull request.

**Comment by OzPerle** [comment]
> Dear Contributor,
> 
> Please provide proof of Policy ID via website or social media so I can merge the pull request.

Hi there,
Please find my Twitter handle for this project here: [https://twitter.com/MetaverseCarto]

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
