### PR TITLE
Added Imperfect Pandas

### PR DESCRIPTION
**Pull request by ImperfectPandas**
10,000 cute but imperfect pandas living on the blockchain awaiting for their new and lovable owners.
Our first drop will consist of 500 pandas.
This is our:
twitter: https://twitter.com/CNFT_Pandas?s=20
discord: https://discord.gg/pChnbRdngf

and our website is coming very soon!

TY Stale for your time!

### CODE REVIEW

**Comment by KaiNFT** [comment]
Hi Contributor,

Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

**Comment by ImperfectPandas** [comment]
> Hi Contributor,
> 
> Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

Would a tweet or a discord channel work?

Thank you

**Comment by ImperfectPandas** [comment]
> Hi Contributor,
> 
> Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

https://twitter.com/CNFT_Pandas/status/1460573371062636552?s=20

here is the proof

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by AnOnlineGuy** [comment]
We have made another change to GitHub that you should be aware of. 

I need you guys today to go through all the PRs and close them with this message. 

‘Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
