### PR TITLE
Update FunkyCardano

### PR DESCRIPTION
**Pull request by EmaCada**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by EmaCada** [comment]
site: http://funkycardano.hostinggratis.it/Creations/
twitter: https://twitter.com/Cardadicted

**Comment by EmaCada** [comment]
updated site: http://funkycardano.hostinggratis.it/Creations/

**Comment by KaiNFT** [comment]
Dear Contributor,

Thank you for your patience, your request has now been merged.

**Pull request merged**
