### PR TITLE
Added AdaVikings

### PR DESCRIPTION
**Pull request by AdaVikingsNFT**

### CODE REVIEW

**Comment by AdaVikingsNFT** [comment]
Twitter link - 
Discord link - https://discord.gg/EWcuGySB

**Comment by MaxJewell** [comment]
In the policies section would you be able to remove the part of the policy ID where it says AdaVikings as it will fail the merge.

**Comment by AdaVikingsNFT** [comment]
HI, could you please navigate me, where i can remove it? [image: image.png]

út 2. 11. 2021 v 17:45 odesílatel MaxJewell ***@***.***>
napsal:

**Comment by AdaVikingsNFT** [comment]
ok it is done i think. Is it fine now?

út 2. 11. 2021 v 19:12 odesílatel Mark Budno ***@***.***>
napsal:

**Comment by MaxJewell** [comment]
Would I be able to have a fresh discord link so I can go on there in hopes to verify you.

Many Thanks.

**Comment by AdaVikingsNFT** [comment]
Hi, link - https://discord.gg/QdtxbsX2

thank you,
M.

**Comment by MaxJewell** [comment]
Would you be able to add the policy which is in the code onto the discord so I can verify it is you.

Many thanks.

**Comment by AdaVikingsNFT** [comment]
you mean this - 25f1af8aab192ae0608477534dcff2599f91b9e0e21a9?

Thank you

**Comment by MaxJewell** [comment]
Yes please.

**Comment by AdaVikingsNFT** [comment]
Done :)
čt 4. 11. 2021 v 12:39 odesílatel MaxJewell ***@***.***>
napsal:

**Pull request merged**
