### PR TITLE
Create JuxtapositionArt

### PR DESCRIPTION
**Pull request by 0n1udra**
https://twitter.com/0n1udra/status/1446560422086250535

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, I am just leaving a message to say that I will be able to check your policy IDs when the CNFT.io website is back up and running. I will be able to use the links you have to each NFT listing on CNFT.io.

**Comment by TomStray** [comment]
Dear Contributor, please can you update your links to your CNFT.io listings on your twitter.

**Comment by 0n1udra** [comment]
Tweet for each CNFT collection with a policy ID I need verified. 

JuxLight Policy 1 (a31eb93d96395d9e387a563c0037bff30bb507e6ef1a8eed48f37482)
https://twitter.com/0n1udra/status/1457137532399988736

JuxLight Policy 2 (87eed37773452faa0aec372bab6e74ae19055402487a56755d5a3361)
https://twitter.com/0n1udra/status/1457137891889590272

JuxLight Policy 3 (dd2dfa7921ee8e198e2bac99e3b1f0b11111fc8ba573acfbb04c991a)
https://twitter.com/0n1udra/status/1457138049461129218

JuxAbstract Policy (8df8a0f6205a89dde6823339c96b02cf2dc438e2a38bb741b30b9936)
https://twitter.com/0n1udra/status/1457138486172135432

**Comment by 0n1udra** [comment]
this pull request has been closed. will the be merged or did something go wrong?

**Pull request closed without merging**
