### PR TITLE
MilesNFT

### PR DESCRIPTION
**Pull request by jeremydmiles**
https://twitter.com/JeremyM95102701/status/1488351579220684807

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

 Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by KaiNFT** [comment]
Dear Contributor, 

Your social media is very new, do you have another form of social media or a website I can use to verify you?

**Comment by jeremydmiles** [comment]
facebook:
https://www.facebook.com/jeremy.miles.9421

**Comment by jeremydmiles** [comment]
> ###

https://www.facebook.com/jeremy.miles.9421/posts/309163831172092

**Comment by jeremydmiles** [comment]
https://www.facebook.com/jeremy.miles.9421/posts/309163831172092

**Comment by jeremydmiles** [comment]
https://www.facebook.com/jeremy.miles.9421/posts/309163831172092
https://twitter.com/JeremyM95102701/status/1488351579220684807

Will these references be sufficient?

**Comment by jeremydmiles** [comment]
https://www.facebook.com/jeremy.miles.9421/posts/309163831172092
https://twitter.com/JeremyM95102701/status/1488351579220684807

Will these references be sufficient?

**Comment by MaxJewell** [comment]
Due to low user engagement, we have decided to close this request. 
Feel free to open another request whenever your ready.

**Pull request closed without merging**
