### PR TITLE
Added Project Cardano Cosmos

### PR DESCRIPTION
**Pull request by foxtrotnad**
This is my project for the cardano NFT project Cardano Cosmos

### CODE REVIEW

**Comment by MaxJewell** [comment]
Hello, 
Would you be able to add a link to a twitter account/website to verify your identity.

Many thanks.

**Comment by foxtrotnad** [comment]
I do not have a Twitter but I do have a Instagram with my photography that
I used for the NFT's. if you scroll down a couple rows you'll find the same
sky image I used for the NFT project.

https://instagram.com/spokenwolfphotography?utm_medium=copy_link

Let me know if this works.

**Comment by MaxJewell** [comment]
Do you have the Policy ID's on the Instagram page and what posts are there?

**Comment by foxtrotnad** [comment]
Sorry iam new to this. Do I need to post the policy ID in the bio?

The Instagram account has my photography that I use as the background for
the NFTs.

Thanks,

**Pull request closed without merging**
