### PR TITLE
 Paperhand Club

### PR DESCRIPTION
**Pull request by paperhandclubcnft**
https://twitter.com/PaperhandClub

https://discord.gg/eSkYCAx9

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request.

**Comment by paperhandclubcnft** [comment]
thanks! I just fixed it.

**Comment by paperhandclubcnft** [comment]
Hey KaiNFT,

Thanks for the correction, i just commited changes to the pull request. Can
you help check?

Appreciate it!

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by paperhandclubcnft** [comment]
Got it, thanks!

**Comment by paperhandclubcnft** [comment]
Can we just create another account and re-submit? This is hard for me since
we are still looking for a dev at this early stage.

Appreciate your help, Kai.

**Comment by paperhandclubcnft** [comment]
i think i got it, sorry for my lack of knowledge. I submit the new file
within the 'Projects' directory. Thank you!

**Pull request merged**
