### PR TITLE
Update Mr.Cooper

### PR DESCRIPTION
**Pull request by MrCoopernft**
Updated new customs

### CODE REVIEW

**Comment by MrCoopernft** [comment]
Is there an ETA when this will be updated?

**Comment by TomStray** [comment]
Please can you send a link to your twitter account/website with your policy ID on it to verify.

**Comment by MrCoopernft** [comment]
https://mrcoopernft.wixsite.com/mrcoopernft 

https://twitter.com/cspot1980

**Comment by TomStray** [comment]
I am struggling to find a matching policy ID on your website or twitter. If you could clarify, that would be wonderful.

**Comment by MrCoopernft** [comment]
My apologies, I misunderstood. Previously we just needed to show our art on our website. I have added a policy Id tab on my website on the top header.  Can you use this also for pull requests 790. Thanks for you help.

https://mrcoopernft.wixsite.com/mrcoopernft

**Comment by MrCoopernft** [comment]
Correction: Please update pull request #730 also

**Comment by MrCoopernft** [comment]
> I am struggling to find a matching policy ID on your website or twitter. If you could clarify, that would be wonderful.

New links have been updated

**Pull request merged**
