### PR TITLE
Create KMonsterZ

### PR DESCRIPTION
**Pull request by KMonsterZ**
project homepage : https://kmonsterz.io
twitter : https://twitter.com/KmonsterCNFT/

### CODE REVIEW

**Comment by CNFT-io** [comment]
We can't verify your policy ID anywhere. please publish this to your website.

**Comment by KMonsterZ** [comment]
https://cardanoscan.io/tokenPolicy/33540028ad4ade822c82d61ed2d55388422c3db0bfcd11e5e1c92e2a

It's being searched normally.
What additional things should be checked?

**Comment by KMonsterZ** [comment]
We posted the policy ID on our website.

**Comment by KMonsterZ** [comment]
I created a new one.
Create KMonsterZ #1928

**Pull request closed without merging**
