### PR TITLE
In the mouth of Léviatan

### PR DESCRIPTION
**Pull request by jtepsart**
Hello,
This my first nft's project about the mouth of the Hell
My website where you can check my policy ID is : https://sites.google.com/view/leviatanmouth/accueil

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request.

**Comment by jtepsart** [comment]
hello,
I make an adjustement on the name in the JSON file
I think my mistake was the "é" in Léviatan

**Comment by TomStray** [comment]
Dear Contributor, please remove the comma at the end of line 5.

**Comment by jtepsart** [comment]
thanks for the tip

**Pull request merged**
