### PR TITLE
AltDucks

### PR DESCRIPTION
**Pull request by Melstagram**
Policy ID: https://cardanoscan.io/policyholders?policyId=a2c723e4e45c8c74c4e454d1331a16a7ab1c4d6b972031c58e973528

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by Melstagram** [comment]
Is it the proof I'm missing? - A little lost in all this but here's a tweet: https://twitter.com/AltDucksNFTs/status/1479316951721668608

Twitter account: https://twitter.com/AltDucksNFTs

I also have a project on https://pro.nft-maker.io/ - would the policy number for that be useful?

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by Melstagram** [comment]
I've created a project and linked the respository to it. Has anything changed?

**Comment by Melstagram** [comment]
Policy ID is now in the twitter bio

**Pull request merged**
