### PR TITLE
Create NZ Burbs

### PR DESCRIPTION
**Pull request by 272442277**
https://twitter.com/Kiwicrypto85

https://cnft.io/token/61e3a041adb53a1c76801c7b

### CODE REVIEW

**Comment by alstudi01** [comment]
hey!
can you please tell me how did you verified JSON verification? I tried several times but it failed so!

**Comment by 272442277** [comment]
> 

Hi there, i followed this: https://www.youtube.com/watch?v=z6yPjed4sMI&t=149s

**Review by 272442277 — COMMENTED** [review]
thank you I'm hoping this is complete?

**Comment by alstudi01** [comment]
I did saw that video from youtube but i am having problem with JSON validation. there is nothing on youtube about it.
JSON VALIDATION

**Comment by 272442277** [comment]
> I did saw that video from youtube but i am having problem with JSON validation. there is nothing on youtube about it. JSON VALIDATION

**Comment by 272442277** [comment]
https://www.youtube.com/watch?v=8hoYS1xCyWM this one is the one I used sorry.

**Pull request closed without merging**
