### PR TITLE
Adding PocketTowne

### PR DESCRIPTION
**Pull request by kardall**
Since the Repo was broken in 6 places, the deletions are all files that just break the pull. Had to fork and manually remove all 6 of these files. The last 3 were case-sensitive collisions.

```
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'projects/BlaadPlanet'
  'projects/Blaadplanet'
  'projects/DragonzCLub'
  'projects/dragonzclub'
  'projects/FOODIES'
  'projects/Foodies'
  'projects/LITBITZ'
  'projects/Litbitz'
  'projects/Snadake'
  'projects/snADAke'
```

And the 3 were removed for improper file naming conventions

```
 projects/Crypto Auto Club : Prototype Collection |  8 --------
 projects/Pandenum | Angelmon                     | 11 -----------
 projects/Stonks Football Legends.                |  9 ---------
```

### CODE REVIEW

**Comment by KaiNFT** [comment]
You have a new policy ID posted in the files?

**Comment by kardall** [comment]
Yes. It's projects/PocketTowne

The errors are the system trying to find the 8 other files I had to delete in order to successfully checkout the master because of file names having : | . or same file names with different capitalizations (the last 5).

**Comment by KaiNFT** [comment]
Can you re-open a request with just the PocketTowne policy ID please

**Comment by kardall** [comment]
#6382

**Pull request closed without merging**
