### PR TITLE
Update VisionAI

### PR DESCRIPTION
**Pull request by SamGCURIOM**
New policies

### CODE REVIEW

**Comment by MaxJewell** [comment]
Please leave a link to twitter/webpage for proof with policy ID's.

**Comment by SamGCURIOM** [comment]
The only place I talk about those are on my twitter: https://twitter.com/gcuriom and on my tokhun sales page: https://tokhun.io/sam

**Comment by MaxJewell** [comment]
I can't confirm as there are no policy ID's on either.

**Comment by SamGCURIOM** [comment]
I know, I unfortunately don't have a website for this project yet. Since I've made the first pull request and am just adding a policy, I guessed I wouldn't have issues doing it. What do you need from me to add the policies to the current list?

**Comment by BeBeFinancials** [comment]
You should tweet proof on your twitter account.

**Comment by BeBeFinancials** [comment]
I think tweeting the link to this pull request on your twitter should suffice, still waiting on verification myself but I hope that works since that's what I did... :) Good luck

**Comment by SamGCURIOM** [comment]
Alright, sent this tweet just now: https://twitter.com/gcuriom/status/1437808242999144450?s=20

**Comment by BeBeFinancials** [comment]
I think you should tweet out this link, so people can look up this pull request to verify your ownership https://github.com/Cardano-NFTs/policyIDs/pull/554

**Comment by SamGCURIOM** [comment]
alright, let's see ! https://twitter.com/gcuriom/status/1437809028529278977?s=20

**Pull request merged**
