### PR TITLE
SketcHeroes

### PR DESCRIPTION
**Pull request by lalibertad2**
https://twitter.com/SketcHeroes

discord.gg/9Uxy7Za7nE

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by lalibertad2** [comment]
https://twitter.com/SketcHeroes/status/1486692476497068033?s=20

**Comment by MaxJewell** [comment]
ALL policy ID's will need to be in your tweet. 

Thanks

**Comment by lalibertad2** [comment]
https://twitter.com/SketcHeroes/status/1488926961414156301?s=20&t=W6xSdHehsGBcwKX3wVPJ5w

https://twitter.com/SketcHeroes/status/1488926963049844743?s=20&t=W6xSdHehsGBcwKX3wVPJ5w

https://twitter.com/SketcHeroes/status/1488926964564078594?s=20&t=W6xSdHehsGBcwKX3wVPJ5w

https://twitter.com/SketcHeroes/status/1491910275112570887?s=20&t=W6xSdHehsGBcwKX3wVPJ5w

discord.gg/K7zVMHKd3J

**Comment by MaxJewell** [comment]
Morning, 
Please remove the comma from the end of line 14.
Thanks.

**Comment by lalibertad2** [comment]
@MaxJewell Done

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs on lines 11 and 12 to your twitter so that I can verify.

**Comment by lalibertad2** [comment]
https://twitter.com/SketcHeroes/status/1497168546782142465?s=20&t=iPh3aS2tOgbs2FQlyUfsDw

**Pull request merged**
