### PR TITLE
Update Mr.Cooper

### PR DESCRIPTION
**Pull request by MrCoopernft**
Updated project names to Mr. Cooper to consolidate and added tags

### CODE REVIEW

**Comment by MrCoopernft** [comment]
Hello, 

Is it possible to fix, the filter function had 6 Mr.Cooper which all link to the same NFT?

**Comment by Dean00K** [comment]
looking now

**Comment by Dean00K** [comment]
I've just changed your file from what it was, to look like this:

[{
	"project": "Mr.Cooper",
	"tags": [
		"Thin Blue Line", "Blessed Are The Peacemakers", "Time Is Our Greatest Asset", "Lost", "ADA Whale To The Moon!",
		"Limited Edition Digital Lion", "Bull Run", "Friday The 13th"
	],
	"policies": [
		"e6285917ada7b35cba52a158ed56e144794138eaa633763041b68fd6",
		"64b3735692fafbd0db438f696bb6cdf37040ff7f3ecd8e2c2a36350a",
		"e5adf75988efed56dab74dbd21161b1206e87eb3fc85c5ddfee80653",
		"29d1233d494a771d2e93ff0b5118e3f3741899fbfb336824f6b41b4c",
		"cce0bb04e4adab1f993b8a43a3bd19eb0e2c87ddece44705294e3dc4",
		"dc140b300e3d5a3685d45a819a3f193112ee55a88dea03a919e4c1d0",
		"ee36f1f6695aebcda43adb5f7a5979a2d9c8c310523e8475b35e0517",
		"30227c7bb18506e5d9e85d88da471345cdcc5a591e37d08a1ae2e676",
		"f40337f5f7927baf5bd4ec393c0ea56cd1958c5818c6a39a5ddf1ed3",
		"a981256ec0646ea90f8c423ed971573a0cb58b3aaf90c62fa8137f2d"
	]
}]

That should fix it up.

**Comment by MrCoopernft** [comment]
Thanks, it’s fixed

**Pull request merged**
