### PR TITLE
Create text art: the human spectacle

### PR DESCRIPTION
**Pull request by uncha1n3d**
artist: chiarascuro

### CODE REVIEW

**Comment by uncha1n3d** [comment]
https://twitter.com/chiarascuroNFTs

**Comment by Dean00K** [comment]
Hey, can you write me a short blurb about the project please? There isn't much to go off from the twitter account and another point of concern is that your policy ID never locks. Can you give some more insight to the project please?

**Comment by uncha1n3d** [comment]
Hi, Dean,
I am pretty new to making NFTs and I don't know exactly what I'm doing with the policies. I have a lot to learn, but I left them open because I wasn't sure what I should do with them.
My Twitter account is for all my projects, not just one. There will be different types of art coming from me, but the first collection I'm working on is a small collection of black and white digital art featuring text. I've used text in my paintings for many years. I use it to help create texture, as a way of encoding messages (because of numerous violations of my privacy), and as a way of creating intrigue. Usually, there are still a few words or letters still visible, so people always look really close and try to read them. (To no avail. They only get to read what I decide to let them read.)
Here's a link to my website in case it will help.
This really raises some concerns for me. Are open policies not going to be added to the repo? If they're not, I need to warn everyone in Tokhun's Telegram chat. Noobs like me shouldn't have to waste any more Ada trying to mint things that aren't going to be in the repo and will later be dubbed as fakes because of it. This isn't like OpenSea where the UI is simple and straightforward. Relative beginners to minting on Cardano platforms are not being given proper instruction about how to go through this process. It's being assumed that we all know what policies are and what to do with them. It's being assumed we all know our way around Github when, in fact, some of us have never used it at all. 

I'm writing a tutorial for Tokhun right now how to add the policies, so if you have any other insights for me, I'd sure appreciate it.This whole space is supposed to be democracy in a purer form than we've ever seen before. But it's not democratic if only people with programming chops can navigate it.

Let me know if you have any other questions for me, and have a fantastic week!
Chi

---

"The easy way is efficacious and speedy, the hard way arduous and long. But, as the clock ticks, the easy way becomes harder and the hard way becomes easier. And as the calendar records the years, it becomes increasingly evident that the easy way rests hazardously upon shifting sands, whereas the hard way builds solidly a foundation of confidence that cannot be swept away."

- Colonel Sanders
 

    On Monday, August 23, 2021, 07:57:33 PM EDT, Dean00K ***@***.***> wrote:  
 
 


Hey, can you write me a short blurb about the project please? There isn't much to go off from the twitter account and another point of concern is that your policy ID never locks. Can you give some more insight to the project please?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dean00K** [comment]
Hey Chi,
So basically an open policy gives the creator the freedom to continue to mint new tokens against it. So if a creator made an exclusively rare NFT drop of 100 unique NFTs and sold them for 200ADA each, he could go back later and just create more and flood the market. Collectors are looking for locked policy IDs or at least a policy ID that does have a date set for locking in the future. Some projects give themselves 12 months, for example, to get out series 1, 2 and 3. within the same policy to make life simpler. For some, reputable NFT projects, people are still comfortable/okay with seeing a policy ID that never locks. But even then, if the creator loses access or gets hacked, a bad actor could come through and mint more of his collection and again, flood the market. Think of it like a cryptocurrency with a hard cap max supply vs. an inflationary currency. The way cnft.io gives you the verification and yellow tick is by recognising that Policy ID, so if something were compromised and someone was able to mint more NFTs using that same policyID, it would still be ticked and verified. Take the SpaceBudz project for example. The create wasn't sure how that was going to go, he had 10,000 unique NFTs so he set the policy ID to lock after 6 months in case he needed more time to sell all his NFTs. Well that 6 month mark was 2 days ago and there was a little celebration amongst the community about it. He sold out initially in about 5 days.. and up until 2 days ago he could have technically gone and minted himself more rare SpaceBudz.. Hopefully that makes sense.. You're project is fine and I can verify you, But as an avid CNFT collector myself, If a policy ID isn't locked, or have a locking date, I'm more cautious about it.

**Comment by Dean00K** [comment]
I'm verifying you now. But maybe chat amongst your discord server and figure out the best way forward for this maybe.. still very early and there isn't a known standard yet.

**Comment by uncha1n3d** [comment]
Hello, Dean,
Thanks for the explanation. I'll let my peeps know and maybe do an FAQ about policies for the newer ones.
Here's a link to the tutorial I wrote today. How to add your project’s policy ID to the CNFTs Verified Policy Database

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
How to add your project’s policy ID to the CNFTs Verified Policy Database

Welcome to Cardano, the home of CNFT marketplaces! If you’re an artist creating your first CNFT collection, you’...
 |

 |

 |


The Tokhun devs are looking at it because I asked them to check it for accuracy. Would you mind checking it for me, too?

---

"The easy way is efficacious and speedy, the hard way arduous and long. But, as the clock ticks, the easy way becomes harder and the hard way becomes easier. And as the calendar records the years, it becomes increasingly evident that the easy way rests hazardously upon shifting sands, whereas the hard way builds solidly a foundation of confidence that cannot be swept away."

- Colonel Sanders
 

    On Tuesday, August 24, 2021, 08:25:26 AM EDT, Dean00K ***@***.***> wrote:  
 
 


Merged #382 into main.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Dean00K** [comment]
Can you send it to me as a DM on twitter? I can't view it properly here. @Dean_00K

**Comment by Dean00K** [comment]
Here is a really good example of everything I need to verify and merge new projects. This makes the process really easy and it ticks all my boxes for due diligence. https://github.com/Cardano-NFTs/policyIDs/pull/355 
He has a website, has given me links etc etc.
cheers.

**Comment by uncha1n3d** [comment]
Thanks for the info, Dean! I'll pass that along to my group.
This is embarrassing, but I'm not exactly sure who you are. If you give me your Twitter handle, I'll send you the link to view the document. But if you'd like to add any comments (I'd welcome that) then I can share editing access with you via an email address.
Since there will be many people flooding into this space with all experience levels, I'm trying to address the parts of the process that are confusing to those just starting out by creating helpful content. In a Cardano-specific way. There's already a ton of content about how to do this on Ethereum, but doing this on Cardano has been a bit like establishing a colony on the moon. Even the gravity is different. But I write explainers all the time for work, and that's been useful experience breaking down technical concepts for the less tech-savvy.

I've already offered Tokhun a few volunteer hours every month to help them with content, web copy, etc. But if I only do that for them, I feel like it wouldn't be enough. I see a deep need for educational material for the CNFT community in general. I was going to use my blog just to promote my own collections, but now I also want to turn it into a learning resource for everyone who wants to start selling NFTs on Cardano.
Cheers,Chi

---

"The easy way is efficacious and speedy, the hard way arduous and long. But, as the clock ticks, the easy way becomes harder and the hard way becomes easier. And as the calendar records the years, it becomes increasingly evident that the easy way rests hazardously upon shifting sands, whereas the hard way builds solidly a foundation of confidence that cannot be swept away."

- Colonel Sanders
 

    On Tuesday, August 24, 2021, 09:15:36 PM EDT, Dean00K ***@***.***> wrote:  
 
 


Here is a really good example of everything I need to verify and merge new projects. This makes the process really easy and it ticks all my boxes for due diligence. #355
He has a website, has given me links etc etc.
cheers.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Pull request merged**
