### PR TITLE
Create Floating Thunder

### PR DESCRIPTION
**Pull request by gatonjutsu**
https://pool.pm/addr1qy03f0xkt8n2mjhhrxwd67klyv72kulmv4tlj56kqmk50vyg37nv3r0clwlven8037tlw6lltv6mev5lclmll7cmek9q9qr226
twitter link to verify : https://twitter.com/Gatonjutsu/status/1428361165348827150/photo/1

### CODE REVIEW

**Comment by Dean00K** [comment]
Hey mate - I need you to remove some tags - they are too broad.. I need them to be only specific to your NFT title essentially. For context, if I was to merge this commit, anyone else using the word "guitar" or "wizard" in the description or title of their NFT, it would display on the website as "NOT A REAL Guitar Wizard".
Also, are you going to be locking this policy?

**Comment by gatonjutsu** [comment]
Hello sir, already removed the tags.  Actually I don't know how to lock the policy. The  NFT is 1 our of 1 only.

**Comment by Dean00K** [comment]
yeah no worries. I can let this one through, but the guys at cnft.io are tightening the verification process - this wouldn't get through usually because its an unlocked policy id that you could re mint multiple amounts of this NFT at your choosing. I just need you to remove the commas off the end of line 6 and line 9. lmk when its done and ill get it through.

**Comment by gatonjutsu** [comment]
Ahhh, I get it now. will research more about on Policy. Thanks Dean! already done.

**Pull request merged**
