### PR TITLE
Pixy Planet

### PR DESCRIPTION
**Pull request by PixyDaoNFT**
https://www.pixyplanet.com/
discord.gg/pixyplanet
https://twitter.com/PlanetPixy
https://twitter.com/PlanetPixy/status/1496638857479168001

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please remove the comma at the end of line 5.

**Comment by PixyDaoNFT** [comment]
Hello, just fixed it! Thanks!

**Comment by Guru-Dingus** [comment]
I dont know why but edits just don't take sometimes...the best way is to remove the pull request and delete the file and start again (I have been here and its the only way I got to fix it!)

**Comment by PixyDaoNFT** [comment]
Done!
https://github.com/Cardano-NFTs/policyIDs/pull/6604

**Comment by PixyDaoNFT** [comment]
Hey any update?

**Comment by Guru-Dingus** [comment]
Hi, I don’t pass projects I’m just a community member that was trying to
help.

**Comment by PixyDaoNFT** [comment]
OHH, Lmfao!
Thank you!

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Pull request closed without merging**
