### PR TITLE
Update Pandalogy

### PR DESCRIPTION
**Pull request by Pandameth**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Please leave a link to twitter/webpage for proof with policy ID's.

**Comment by Pandameth** [comment]
https://twitter.com/pandalogy101

https://discord.com/invite/fRdmqCuXxd

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs to your twitter so that I can verify.

**Comment by Pandameth** [comment]
Already done it. Policy ID is on my Twitter now. You can check it in my bio.

https://twitter.com/pandalogy101

**Pull request merged**
