### PR TITLE
ADA Crime City

### PR DESCRIPTION
**Pull request by jdev101a**
https://twitter.com/AdaCrimecity

https://adacrimecity.com/

https://discord.gg/VKJ4M4VnvA

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by jdev101a** [comment]
Hi KaiNFT,

Please see website underneath FAQ

https://adacrimecity.com/

Regards,
Judd.

**Comment by jdev101a** [comment]
Hi KaiNft,

Just checking if this has been verified.

Thanks


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: judd Angue ***@***.***>
Sent: Monday, February 14, 2022 9:23:06 PM
To: Cardano-NFTs/policyIDs ***@***.***>; Cardano-NFTs/policyIDs ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [Cardano-NFTs/policyIDs] ADA Crime City (PR #6318)


Hi KaiNFT,



Please see website underneath FAQ



https://adacrimecity.com/



Regards,

Judd.

**Comment by jdev101a** [comment]
Thanks for your support!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request merged**
