### PR TITLE
Verification In New Format!

### PR DESCRIPTION
**Pull request by FullmetalAlgorist**
Hoping for verification for this project! Thanks!

### CODE REVIEW

**Comment by FullmetalAlgorist** [comment]
Tweet about this request, to prove I'm real! 
https://twitter.com/fullmetAlgorist/status/1460337860708470785?s=20

**Comment by KaiNFT** [comment]
Hi Contributor,

Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

**Comment by FullmetalAlgorist** [comment]
Here's my tweet with one policy ID and a link to my pool with all the mints in this project. Thanks!
https://twitter.com/fullmetAlgorist/status/1460340202812043265?s=20

**Comment by FullmetalAlgorist** [comment]
Hello! Any specific policy id I should post? I posted one right when I
asked for the pull request. Happy to do another. I'm real I promise!

**Comment by AnOnlineGuy** [comment]
We have made another change to GitHub that you should be aware of. 

I need you guys today to go through all the PRs and close them with this message. 

‘Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
