### PR TITLE
Alliance Comics LLC

### PR DESCRIPTION
**Pull request by Audiemart**
Comic book art bring real comic to nft.

### CODE REVIEW

**Comment by Audiemart** [comment]
https://twitter.com/audmaphone/status/1478080308276695042?s=20

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by Audiemart** [comment]
I followed the video to the t I am trying to do with my other project I do
not understand.

**Comment by KaiNFT** [comment]
Please read the READ.me file for more information.

**Comment by KaiNFT** [comment]
Dear Contributor,

This request will now be closed, make a new ticket with the following criteria; the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
