### PR TITLE
Added Cardanorcs

### PR DESCRIPTION
**Pull request by Cardanorcs**
Cardanorcs are a fantasy civilisation of unique non-fungible Orcs inspired by mythology, legacy and lore.

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

**Comment by Cardanorcs** [comment]
I have just updated the pull request as mentioned.

Thank you.

**Review by Cardanorcs — COMMENTED** [review]
We've tried it on Jsonformatter as well, it says valid. May I know the issue?

**Review by Cardanorcs — COMMENTED** [review]
Updated Pull Request

**Comment by KaiNFT** [comment]
It's still syaing that the file is not in the projects directory, maybe try and re-open a pull request?

**Comment by Cardanorcs** [comment]
okay sure! thank you!

**Comment by Cardanorcs** [comment]
hi is there any way you can help to resolve this? Thank you!

**Pull request closed without merging**
