### PR TITLE
Project JUST A .JPG

### PR DESCRIPTION
**Pull request by justajpg**

### CODE REVIEW

**Review by justajpg — COMMENTED** [review]
merge of PR

**Comment by bananada1097** [comment]
Just to help you, I had the same problem...

You need to open the Pull Request inside this **Project folder**... Otherwise it will fail

**Click Add File > Create New File**

**Direct link >** https://github.com/Cardano-NFTs/policyIDs/tree/main/projects

**Comment by justajpg** [comment]
> 

Hi Bananada,

Thank you for the help, but it still doesn't work :(

**Comment by bananada1097** [comment]
Do what I said in the other Pulls you opened

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
