### PR TITLE
Added BloodyHand

### PR DESCRIPTION
**Pull request by Leon1Art**
This 3d project, based on true story from the cutted hand of Hazrat Abbas, is one of the Shia Imams who lost his hand to provide water for orphans by the enemie and this is a reminder of the oppression that has been done to him...

twiiter : https://twitter.com/LeonArtgroup/status/1442230274524205065?s=20

website : https://t.co/ILBoBzCVzl?amp=1

### CODE REVIEW

**Comment by Leon1Art** [comment]
New cnft link : https://cnft.io/token.php?id=6154bcac30a286aa9246458e

**Comment by Leon1Art** [comment]
Twitter link : https://twitter.com/leonartgroup/status/1442114797957521411?s=21

**Comment by Leon1Art** [comment]
Instagram.com/leon1art

**Comment by Dado202** [comment]
Kratos-og van, you help me, with my pull request #1741?

**Pull request merged**
