### PR TITLE
Formatting updates v2

### PR DESCRIPTION
**Pull request by kristur**

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, you have conflicts with your code.

**Comment by kristur** [comment]
Can you please elaborate? I'm at my wits end trying to make sense of this stuff.
The code passed github tests. What is wrong, what do I have to do to make it right?

**Comment by TomStray** [comment]
Dear Contributor, conflicts with your code means that a code has already been merged that has some of the content in this code you have now. I can see that you have contributed to this repository in the past. Therefore, if you have policy IDs that are under the same project name or tags, you should be able to fork the code that has already been merged, and add more policy IDs to it.

If you create different pull requests with different policy IDs that are in the same project, it will come up as conflicting as that project will already be in the database.

Hope this helps,

**Comment by kristur** [comment]
Thank you, yes that explains it!
I'll make it right.

**Pull request closed without merging**
