### PR TITLE
Update Crypto_Monstars

### PR DESCRIPTION
**Pull request by noem9studio**
[
   {
      "project":"Monstars_Club",
      "tags":[
         "Monstars_Club"
      ],
      "policies":[
         "4c7e60af227a133d27ebd9f974e39f7930ad95e1fce1eccaf6913c5b"
      ]
   }
]

### CODE REVIEW

**Comment by noem9studio** [comment]
https://twitter.com/Monstars_Club/status/1460662773692735491?s=20

**Comment by KaiNFT** [comment]
Hi Contributor, 

Please can you make the necessary adjustments to the JSON file so I can merge the pull request.

**Comment by noem9studio** [comment]
Hello,
I just edited the file.

Thanks!

**Comment by noem9studio** [comment]
> Hi Contributor,
> 
> Please can you make the necessary adjustments to the JSON file so I can merge the pull request.

Hi Kai, I did edit the JSON file already. Could you please check if everything is alright?

Thank you!

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
