### PR TITLE
BengaJs

### PR DESCRIPTION
**Pull request by buraz24**
https://www.instagram.com/bengajs/
https://twitter.com/BengaJs
bengajs1@gmail.com

### CODE REVIEW

**Comment by buraz24** [comment]
how can I verify json validation?

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by buraz24** [comment]
> Dear Contributor,
> 
> Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

I guess I did it right this time?

**Comment by buraz24** [comment]
> Dear Contributor,
> 
> Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

did I did it right?

**Comment by MaxJewell** [comment]
Can you put your policy ID's onto your twitter.
Thanks.

**Comment by buraz24** [comment]
> Can you put your policy ID's onto your twitter. Thanks.

I did :)

**Comment by buraz24** [comment]
> Can you put your policy ID's onto your twitter. Thanks.

Is it ok? :)

**Pull request merged**
