### PR TITLE
Added Girafdano

### PR DESCRIPTION
**Pull request by Girafdano**

### CODE REVIEW

**Comment by Girafdano** [comment]
1

**Comment by KaiNFT** [comment]
Hi Contributor,

Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

**Comment by Girafdano** [comment]
addr1vyw8vl9ghr90t8572nqda8c64056mc7qm648g7m73gxrykcqpfc7m

**Comment by AnOnlineGuy** [comment]
We have made another change to GitHub that you should be aware of. 

I need you guys today to go through all the PRs and close them with this message. 

‘Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
