### PR TITLE
AdasArk Animals

### PR DESCRIPTION
**Pull request by AdasArk**
https://twitter.com/AdasArkAnimals

### CODE REVIEW

**Comment by AdasArk** [comment]
How long does this take to get approved and then up and active on CNFT.io?

**Comment by TomStray** [comment]
Dear Contributor, please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by AdasArk** [comment]
How do I put it in the "Projects" directory?

**Comment by AdasArk** [comment]
I am so new to all this can someone call me to walk me through it?


*Robyn Tragesser*
*757-876-1007*

**Pull request closed without merging**
