### PR TITLE
ImagesofPaper

### PR DESCRIPTION
**Pull request by AuthenticImage**
https://twitter.com/imagesofpaper

https://discord.com/channels/915064124365500447/915064666361843733

https://twitter.com/imagesofpaper/status/1465516694722465796

Policy id prof : https://twitter.com/imagesofpaper/status/1465538763262734336

### CODE REVIEW

**Comment by AuthenticImage** [comment]
https://twitter.com/imagesofpaper/status/1465516694722465796

**Comment by AuthenticImage** [comment]
tweet 

https://twitter.com/imagesofpaper/status/1465538763262734336

**Comment by AuthenticImage** [comment]
Can someone please help?

**Review by AuthenticImage — COMMENTED** [review]
.

**Comment by AnOnlineGuy** [comment]
Please tweet your policy IDs and leave it as a comment on Github

**Comment by AuthenticImage** [comment]
https://mobile.twitter.com/imagesofpaper/status/1465538763262734336

**Comment by AuthenticImage** [comment]
Done ✅

**Comment by AnOnlineGuy** [comment]
You need to delete the first commit as it's not in the projects folder and resubmit.

**Comment by AuthenticImage** [comment]
Done.

**Pull request closed without merging**
