### PR TITLE
Create ChimpionClubCNFT

### PR DESCRIPTION
**Pull request by chimpionclubcnft**
DISCORD: https://discord.gg/FKXR4TVcqq

WEBSITE: https://chimpionclub.com/

TWITTER: https://twitter.com/ChimpionClubNFT

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website also make the correct adjustments to the JSON file in order for me to merge the pull request.

**Comment by chimpionclubcnft** [comment]
hey KaiNFT,

We've updated the policy ID on our site

For adjustments to the Json file, what do you mean specifically?

Thanks

**Comment by KaiNFT** [comment]
Dear Contributor,

The error I'm receiving on my end is "TYPE should be ARRAY" meaning there is a format issue.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
