### PR TITLE
Adding Fan Art keys policy ID on line 26

### PR DESCRIPTION
**Pull request by deveerei**
This is for a fanart collection for benjamin's club, original artwork by zigor - artist asked these to be minted. Proof of policy:

https://discord.gg/8bits under policy-ids channel. Will also make a tweet of this.

### CODE REVIEW

**Comment by deveerei** [comment]
Here's the tweet for proof: https://twitter.com/anim8bits/status/1468649075356491777

Thanks a lot!

**Comment by MaxJewell** [comment]
Morning,
Would you be able to add 5df0efe3205ea4af727847a5f5e422ddf9a2e590bb85474b59f2f99f to your policy ID channel.
Thanks.

**Comment by deveerei** [comment]
Oh yup sure. Forgot to add that there too. Thanks for reminding me! Done
updating it!

**Comment by deveerei** [comment]
Awesome, thanks!

**Pull request merged**
