### PR TITLE
Update Aeoniumsky Policy IDs

### PR DESCRIPTION
**Pull request by josephfusco**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by josephfusco** [comment]
@KaiNFT Both of the above policy ID's can be seen in aeoniumsky's policy-id discord channel https://discord.com/channels/@me/931357003983511572/938540887267495966

**Comment by josephfusco** [comment]
Hey @KaiNFT please let me know if there is anything else. Thank you!

**Comment by KaiNFT** [comment]
Can you provide a twitter/website?

**Comment by josephfusco** [comment]
> Can you provide a twitter/website?

https://www.aeoniumsky.io/policy-ids

**Pull request merged**
