### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CardanianNFT**
{
    "project": "CardanianSnowGlobes",
    "tags": [
        "CardanianSnowGlobes"
    ],
    "policies": [
        "2d1e33d10789b2284788e7e67bd3fd2d07194720bc81f475adf45cbe",
              "eadf22778135584d96da25ebf4696de1e2bed4b9422ea24444442ade",
              "8aae5b74fb6f66755911200634427ea484bfd2bd313db30a37e96c7b"
          ]
}

### CODE REVIEW

**Comment by CardanianNFT** [comment]
need to add this policy also 1ab7be832daeb8a9f41ff80bec60185fe24058c068dd9bdec2538f99

**Comment by MaxJewell** [comment]
Please leave a link to twitter/webpage for proof with policy ID's.

**Comment by CardanianNFT** [comment]
https://twitter.com/CardanianNFT?s=09

**Comment by CardanianNFT** [comment]
Policy ID for the "Original 6" series :

2d1e33d10789b2284788e7e67bd3fd2d07194720bc81f475adf45cbe

Policy ID for Limited Edition Globes :

8aae5b74fb6f66755911200634427ea484bfd2bd313db30a37e96c7b

Policy ID for the SushiBytes globes :

eadf22778135584d96da25ebf4696de1e2bed4b9422ea24444442ade

Policy ID for the Radioactive globes :

1ab7be832daeb8a9f41ff80bec60185fe24058c068dd9bdec2538f99

**Comment by MaxJewell** [comment]
These need to be within a twitter or website page so they can be verified as your own policy ID's. 

Thanks.

**Pull request merged**
