### PR TITLE
Add AdaArt project

### PR DESCRIPTION
**Pull request by alandarev**
Thanks in advance! :)

### CODE REVIEW

**Comment by alandarev** [comment]
A link to the tweet confirming the ownership: https://twitter.com/adadotart/status/1427597931113234432

**Comment by Dean00K** [comment]
hey - can you delete that 2nd commit for me so i can merge your "create adaart" commit. cheers

**Comment by alandarev** [comment]
https://github.com/Cardano-NFTs/policyIDs/pull/359
Here is a new pull request without "Merge".

**Comment by Dean00K** [comment]
What is this though? I go take a look and the first thing i see is a Policy that never locks? Which doesn't bode well for verification for starters.. The website is "coming soon" and I need to do my due diligence.. Hope that makes sense?

**Pull request closed without merging**
