### PR TITLE
Create Alphabet Ranger

### PR DESCRIPTION
**Pull request by royalty007**
website: www.alphatrontoys.com
instagram: https://www.instagram.com/alphatrontoys/ 
Twitter: https://twitter.com/AlphatronT

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by royalty007** [comment]
Hi

Thanks for the response

I have already provided my websites  for reference check.

www.alphatrontoys.com

Is that be something workable  ? Or is there are more ?

Thanks
Darren

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your twitter or website.

**Comment by KaiNFT** [comment]
Closed due to inactivity

**Pull request closed without merging**
