### PR TITLE
Added All Hajdari project ids

### PR DESCRIPTION
**Pull request by Hajdari-CNFT**
here is the link to our discord so you can verify these are our policy ids
 https://discord.gg/EmD3Yfsx6x

### CODE REVIEW

**Comment by MaxJewell** [comment]
Hello, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by Hajdari-CNFT** [comment]
Thank you for your email, the information is below

My Hajdari project
(Twitter)
https://twitter.com/Hajdari_CNFT?s=09

Isometric World
(Twitter)
https://twitter.com/IsometricWorld_?s=09
(Website)
https://www.isometricworld.eu/

Your sincerely

Hajdari

**Comment by Hajdari-CNFT** [comment]
For the hajdari project, how am I meant to put 24 policy ids up on twitter
since we don't have a website yet ?

**Comment by MaxJewell** [comment]
If you could put it in a txt file and DM it to my account at: @maxjewell74

**Comment by Hajdari-CNFT** [comment]
I cannot send you a message on twitter due to your privacy settings. I've
sent you a follow request from the hajdari cnft twitter account.
For isometric World our policy id is now in our twitter bio

**Pull request closed without merging**
