### PR TITLE
Add Merthings Project

### PR DESCRIPTION
**Pull request by MerthingsCNFT**
Website: https://www.merthingscnft.com/
Discord: https://discord.gg/XpVACmtqzC
Twitter: https://twitter.com/MerthingsCNFT

Thank you!

### CODE REVIEW

**Comment by MaxJewell** [comment]
Can you remove a comma on the end of the Policy ID and then I can merge your request.

**Comment by MerthingsCNFT** [comment]
Thank you so much! We have removed the comma.

Best,
Tristan

**Comment by MerthingsCNFT** [comment]
Thank you! We really appreciate what you and your team are doing for the
community, it looks like a ton of work you're crunching out.

Last question and we'll stop bugging you, do you know the general timeline
for a project to show up on CNFT.io search filters after merging? We will
tell our marketing team to be ready for a hard push around the time our
project should show up.

**Comment by MerthingsCNFT** [comment]
Nevermind, see it :) Thank you!

**Pull request merged**
