### PR TITLE
Please verify

### PR DESCRIPTION
**Pull request by ErnstBlaad**
Dear cnft.io, 

we are kind of desperated because we did this process various times and it just doesn´t work. Please feel free to contact us: ernstblaad@gmail.com and help us. 

Thank you in advance!
Sincerly
Ernst Blaad

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please correct the error in the json file and provide proof of the Policy ID via website or social media so I can merge the pull request.

**Comment by ErnstBlaad** [comment]
Hi KaiNFT,

Thx a lot for your info…
We’re absolutely Noobs in GitHub- can you give us a hint how to repair the
Json file or a step-by-step info to do the verification in the new mode?

Thank you in advance
Really hope that we can do it this time
Sincerely
Ernst Blaad

KaiNFT ***@***.***> schrieb am Mo. 15. Nov. 2021 um 11:47:

**Comment by KaiNFT** [comment]
Hi Ernst,

I have corrected the issue in the JSON file, the JSON validator was trying to validate the old file. As for the proof of policy ID; do you have a website/twitter with the policy ID's posted?

**Comment by ErnstBlaad** [comment]
Sorry forgot to inform that I just posted our policy in Twitter

Alexander Jurescha ***@***.***> schrieb am Mo. 15. Nov. 2021 um
13:39:

**Comment by ErnstBlaad** [comment]
Hi KaiNFT,

first of all thank you for your help 😊
And sorry for asking - with the verification process of BlaadPlanet is
everything correct or is there anything to do?

Please - if possible - can you give us info about when we will be verified?

Thank you for your patience
Sincerely
Ernst Blaad

KaiNFT ***@***.***> schrieb am Mo. 15. Nov. 2021 um 15:59:

**Pull request merged**
