### PR TITLE
update The Psychedelic

### PR DESCRIPTION
**Pull request by ThePsychedelicMan**
130 of my nfts are minted ready to go on the market. I was already verified before.  I just would like to update my project with some more nfts.
much thanks to everyone working at cnft.io.
Twitter : @ThePsycheMan

### CODE REVIEW

**Comment by ThePsychedelicMan** [comment]
@CNFT-io @TomStray <3

**Comment by CNFT-io** [comment]
Looks great!

**Comment by Dado202** [comment]
Your, all project have yellow check

**Comment by ThePsychedelicMan** [comment]
> Your, all project have yellow check

well it keeps going from having a yellow tick back to being unknown. it just happened again :(
Hope they can fix it

**Comment by ThePsychedelicMan** [comment]
@CNFT-io Can you please help? my project keeps moving from a yellow tick to being unknown. Please help.

**Comment by CNFT-io** [comment]
Looking into this!

**Comment by Dado202** [comment]
@CNFT-io can you help me with my pull request number #1642?please

**Comment by ThePsychedelicMan** [comment]
> Looking into this!

@CNFT-io it happened again brother, my projects are back to being unknown. Hope you figured out something.

**Comment by CNFT-io** [comment]
What policy ID is it happening for btw? I have been checking but can't confirm..... 

What browser are you using!?!?!

**Comment by ThePsychedelicMan** [comment]
> What policy ID is it happening for btw? I have been checking but can't confirm.....
> 
> What browser are you using!?!?!

It's happening for all the 3 policy IDs merged in this PR. I'm using Google Chrome, it's not just me the buyers have told me about this too, I think this PR is clashing with my other merged PR https://github.com/Cardano-NFTs/policyIDs/pull/839, maybe the tags in that PR might be affecting this? I think if you tried deleting the old PR it might work

**Comment by CNFT-io** [comment]
I can't replicate the issue on all the IDs we have.... 

https://www.cnft.io/marketplace.php?s=249cf7dacfecc3c2efb01f05d7312ce2e4f9c62134f828bff075a787

**Comment by ThePsychedelicMan** [comment]
> I can't replicate the issue on all the IDs we have....
> 
> https://www.cnft.io/marketplace.php?s=249cf7dacfecc3c2efb01f05d7312ce2e4f9c62134f828bff075a787

https://i.imgur.com/2BxZi7z.jpg
https://i.imgur.com/XxX8dDZ.jpg

Bro, these pictures are minutes apart. 12:26 & 12:34, you can see its the same search word i have used. Okay, if nothing works can you please delete this PR and https://github.com/Cardano-NFTs/policyIDs/pull/839 this one, and ill make a new one with all the same policy IDs. Is that okay with you?

**Comment by ThePsychedelicMan** [comment]
> I can't replicate the issue on all the IDs we have....
> 
> https://www.cnft.io/marketplace.php?s=249cf7dacfecc3c2efb01f05d7312ce2e4f9c62134f828bff075a787

@CNFT-io https://imgur.com/a/6AkGmlc this screenshot is what i see now when i clicked the link you send, a while ago it was working properly.

**Comment by ThePsychedelicMan** [comment]
@CNFT-io Check your twitter DM please. I have send a video proof and screenshots, going from verified to unknown in 30 minutes.

**Comment by ThePsychedelicMan** [comment]
Video Proof of Project being unknown and can only be seen when checkbox of verified policy ID is removed @ 11 : 14pm  https://imgur.com/a/nckibKT
Project back to being verified @11 : 26 https://imgur.com/a/2yzgRb9
Project going back to being unknown @11:58 https://imgur.com/UgqYxC7

**Comment by ThePsychedelicMan** [comment]
> Video Proof of Project being unknown and can only be seen when checkbox of verified policy ID is removed @ 11 : 14pm https://imgur.com/a/nckibKT
> Project back to being verified @11 : 26 https://imgur.com/a/2yzgRb9
> Project going back to being unknown @11:58 https://imgur.com/UgqYxC7

**Pull request merged**
