### PR TITLE
Create spacefucks project policy

### PR DESCRIPTION
**Pull request by Doctor-Captain**
spacefucks are the first NFT series created by doctr_captn.  www.doctorcaptain.com

### CODE REVIEW

**Comment by Doctor-Captain** [comment]
https://twitter.com/Doctr_Captn/status/1435410124651253767?s=20

**Comment by Doctor-Captain** [comment]
https://pool.pm/addr1q9mu7n2qg3ny30lnlpek2yxsg3an3xm2q4a5q37gt2938my8n9cduezjw8f58tvz05wfrfkhw7eunt7ucpqmceske0wsgczd92

**Comment by TomStray** [comment]
Dear Contributor, please add an opening square bracket to the end of line 3 and a closing square bracket to a new line below line 4 with a comma after this bracket. As well as this, please remove the comma at the end of line 6

**Comment by Doctor-Captain** [comment]
Hello,

Apologies for my ignorance, but how do I edit those lines?
Would you be so kind as to share a video or some guide on how to do so?

Thank you, and again, apologies for my coding ignorance... very new to the
coding world.

Thank you for your help,
Beau.

**Comment by Doctor-Captain** [comment]
> Dear Contributor, please add an opening square bracket to the end of line 3 and a closing square bracket to a new line below line 4 with a comma after this bracket. As well as this, please remove the comma at the end of line 6

Those changes have been made.
Thank you!

**Pull request merged**
