### PR TITLE
art drawings

### PR DESCRIPTION
**Pull request by Nftcarda**
Policy ID 3ad20f1a2fd242e037ba6b868363c0c4c82cc4830a01389f75d26de3

https://twitter.com/Cardano1988

### CODE REVIEW

**Comment by Nftcarda** [comment]
https://twitter.com/Cardano1988

**Comment by Nftcarda** [comment]
F8802256-D684-4C8D-8D94-3B0163BA3079

**Comment by Nftcarda** [comment]
Why all this time for verification?

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your twitter.

**Comment by Nftcarda** [comment]
326715C6-6247-4682-8559-AFCAA2DFBBA5

**Comment by Nftcarda** [comment]
https://twitter.com/Cardano1988

**Comment by Nftcarda** [comment]
https://github.com/Cardano-NFTs/policyIDs/pull/5205 


https://twitter.com/Cardano1988


Inviato da iPhone

**Pull request merged**
