### PR TITLE
Ash and Tray CNFT comic Season 1

### PR DESCRIPTION
**Pull request by veopixelado**
Following your instructions, I have created this new policy in the Projects folder using the new readme file.I want to verify my project, I created a monthly comic strip, using NFT-MAKER pro tools and I want to drop on December, 2.

These are project social links and website:

twitter: https://twitter.com/ashandtraycomic
discord server: https://discord.gg/NMg6CpcZyd
website: https://pixelado.art/projects/ash-and-tray-comic-strip-cardano-nft/

### CODE REVIEW

**Comment by veopixelado** [comment]
@TomStray @CNFT-io hi, please could you check this out and help me verify it today, i drop my project tonight 8pm UTC and this is something i would like to solve and announce to buyers. Will do whatever you tell me to, please consider I have no coding skills.. thank you very much!

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by veopixelado** [comment]
@KaiNFT @TomStray @CNFT-io I don't get it, I created it inside the Project folder, for sure... i am still getting that json error I can't understand.. I tried to create this pull request several times but don't know what happens.. instructions are pretty clear and I followed them precisely.. but don't know what's the issue, for sure i created it in the correct folder, at least twice.. please help me and I'll do what you tell me as fast as possible

**Comment by KaiNFT** [comment]
Hi @veopixelado,

I have contacted the owner of CNFT with your pull request linked for further support, please bare with us and we will attempt to solve your issue by the deadline given.

**Comment by veopixelado** [comment]
@KaiNFT really appreciate it! thank you very much! I'll keep an eye on this to do whatever you tell me to.

**Comment by veopixelado** [comment]
@KaiNFT @TomStray @CNFT-io Good day! please could you help me solve the issues with the pull request? I followed the process at least 3 times but still getting errors i can't understand.. looking forward to your replies, feel free to edit my files as you consider. thank you very much

**Comment by KaiNFT** [comment]
Hi @veopixelado 

Sorry for the delay, please can you attempt to re submit this pull request, thanks.

**Comment by veopixelado** [comment]
Gm @KaiNFT @TomStray @CNFT-io I am following step by step the video tutorial:
1) Forked and then entered the projects folder (fetched and merged)
2) Create new file, add name.. (route says policyIDs/projects...) 
3) I copy pasted the code from a verified project, changed all details for mine (title, tags, and policy ID)
4) I followed all the steps, and created a new pull request, this is it: https://github.com/Cardano-NFTs/policyIDs/pull/4684

Hope its ok, please let me know as soon as possible, thanks!

**Comment by veopixelado** [comment]
hey @KaiNFT I saw that you closed my latest pull request, https://github.com/Cardano-NFTs/policyIDs/pull/4684 what do I do now? please tell me
cc: @TomStray @CNFT-io

**Pull request closed without merging**
