### PR TITLE
Update Metablocks

### PR DESCRIPTION
**Pull request by GhostArt17**
added granularity to "tags"
also  missed  a  comma after one of the tags...fixed it...hope that didn't cause any issues.(error that was caught below)
Error: Parse error on line 8:
...",		"generative"		"ghostart"	],	"pol
---------------------^
Expecting 'EOF', '}', ':', ',', ']', got 'STRING'

### CODE REVIEW

**Comment by TomStray** [comment]
Please can you send a link to your twitter account/website with your policy ID on it to verify.

**Comment by GhostArt17** [comment]
> Please can you send a link to your twitter account/website with your policy ID on it to verify.

Hi Tom 
Here's the Link to this Update:
https://twitter.com/MetablockArt/status/1437826683248250884

And the link to the original Pull Request
https://twitter.com/MetablockArt/status/1437635417457795075?s=20

Let me know if you need anything else
Cheers/Thanks.

**Comment by GhostArt17** [comment]
Hi Tom
Thanks for taking the time to check out our PolicyID ...We've added the links on our twitter with the on policyID in the Github Comments section.
Thanks.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by TomStray** [comment]
Dear Contributor, could you also please click just before the speech marks on lines 15 to 22 and press the Tab key to indent them once.

**Pull request closed without merging**
