### PR TITLE
Added The Pasta Society

### PR DESCRIPTION
**Pull request by DammeCoding**

### CODE REVIEW

**Comment by DammeCoding** [comment]
I hope this time i did write this the right way :)

**Comment by Dean00K** [comment]
The file is good. But can i get some twitter or website links where i can verify policy IDs please?

**Comment by DammeCoding** [comment]
Hi!

My twitter is PaulCucuruz ***@***.***).
I’ve put the twitter in the tags when i minted the NFTs. I don’t know how
to check them other than to click ok them on CNFT.io

I don’t have a website.

Thank you!

tors 19 aug. 2021 kl. 14:28 skrev Dean00K ***@***.***>:

**Comment by Dean00K** [comment]
Ohhh - yeah i remember, is this a second project of yours?

**Comment by DammeCoding** [comment]
Yes !

I have been watching some instructional videos and it feels like it’s
coming to me :) I always dreamed about learning how to draw and so finally,
i took the first step. The digital tools are amazing... i was just always
working and ”didn’t had time” :)

A big thanks for your work, i didn’t expected such speed and effectivity !

tors 19 aug. 2021 kl. 14:34 skrev Dean00K ***@***.***>:

**Comment by Dean00K** [comment]
to make it easier, you should just add this to your original commit and keep all 3 projects on the same commit - does that make sense? you can still go in and add things to already merged commits, and i just re-merge them. Can we do it that way please? easier for me to having to track less files

**Comment by DammeCoding** [comment]
Yeah no problem. I’ll do that right away.

tors 19 aug. 2021 kl. 14:53 skrev Dean00K ***@***.***>:

**Comment by Dean00K** [comment]
Something went wrong - the file you updated is right, but i cant merge it, did you do a pull request?

**Comment by Dean00K** [comment]
it tells me it belongs to a fork outside the repository

**Comment by DammeCoding** [comment]
What are the steps to do it right ?

First a made a new pull request, then you said it’s easier if i write this
in the old document from yesterday. I watched a video on how to go to the
file and add stuff. First I tried thru a comment somehow, i didn’t felt
right so i did the same as is the video, adding to the original file.

tors 19 aug. 2021 kl. 15:13 skrev Dean00K ***@***.***>:

**Comment by Dean00K** [comment]
its okay - im not 100% sure either but i can fix it up on my side - I'll edit your file within the repo and close the current pull request.
sorry, i want to learn as well but i need to get to bed :) thanks mate - ill sort it within a couple of minutes :)

**Comment by DammeCoding** [comment]
☺️🙏🏻

tors 19 aug. 2021 kl. 15:19 skrev Dean00K ***@***.***>:

**Comment by DammeCoding** [comment]
Hi!

The update doesn't work, i just checked why.
Lines 52 and 53 are doubles of 50 and 51. That's the only possible error I
can find.

Thank you !

Den tors 19 aug. 2021 kl 15:21 skrev Dean00K ***@***.***>:

**Comment by Dean00K** [comment]
Morning mate! Sorry, not sure what i did wrong there - we should be good now.

**Pull request merged**
