### PR TITLE
Created RMoons

### PR DESCRIPTION
**Pull request by rmoons**

### CODE REVIEW

**Review by rmoons — COMMENTED** [review]
added policies

**Comment by MaxJewell** [comment]
This is a good start.
What I will need you to do is to give me a link to a twitter/webpage with the Policy ID's on them to verify your identity.

Many thanks.

**Comment by rmoons** [comment]
All I have are shots from cnft.io – does that work?

**Comment by MaxJewell** [comment]
That does not 100% prove your the owner of this.

**Comment by rmoons** [comment]
How about these transactions from my Yoroi wallet?

**Pull request closed without merging**
