### PR TITLE
Added ProjectNFTFootball by Creative Crypto Lab

### PR DESCRIPTION
**Pull request by scorpion141**
Discord is https://discord.gg/Qj7JBaSv

### CODE REVIEW

**Comment by scorpion141** [comment]
Twitter Link is: https://twitter.com/CreativeCryptoL

**Comment by scorpion141** [comment]
Can you please Verfiy my Projekt :)

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your twitter so that I can verify it.

**Comment by scorpion141** [comment]
Hello Tomstray i added the Policy Ids in a Twitter Post: 

https://twitter.com/CreativeCryptoL/status/1445689213064597516

Is this ok ?

Or must i write the IDs in the Profile ?

Thank you very mutch.

**Pull request merged**
