### PR TITLE
Added Project Cardanonky

### PR DESCRIPTION
**Pull request by Cardanonky**

### CODE REVIEW

**Comment by Cardanonky** [comment]
Hello,

Here is my Twitterlink:
https://mobile.twitter.com/CardanonkyNFT

**Comment by RedArchfiend** [comment]
Please provide a visible Policy ID on your Social page.

**Comment by Cardanonky** [comment]
> Please provide a visible Policy ID on your Social page.

Thanks for you response, my fault i provide a visible PolicyID on my Social page.
I preseaite your time! Thanks for everything.

Greetz Issy

**Comment by Cardanonky** [comment]
@RedArchfiend

**Pull request merged**
