### PR TITLE
Added project Skylines

### PR DESCRIPTION
**Pull request by thuga**

### CODE REVIEW

**Comment by thuga** [comment]
@MaxJewell  Here: https://cnft.io/token.php?id=61360a93ebdbe1a5a811a257

**Comment by thuga** [comment]
@MaxJewell I removed the comma by the way.

**Comment by MaxJewell** [comment]
Have you got a twitter or other social media account we can check to verify your identity.

**Comment by thuga** [comment]
> Have you got a twitter or other social media account we can check to verify your identity.

https://www.instagram.com/thuga_007/

**Pull request merged**
