### PR TITLE
Cardano Puffies

### PR DESCRIPTION
**Pull request by puffiesnft**

### CODE REVIEW

**Comment by puffiesnft** [comment]
https://twitter.com/PuffiesC/status/1465386155122253831?s=20

**Comment by KaiNFT** [comment]
Dear Contributor, 

Apologies for the delay, please can you link all of your social media/websites.

**Comment by puffiesnft** [comment]
Discord address: discord.gg/e4JgrSQfqU
Twitter: https://twitter.com/PuffiesC
These are all of our social media accounts

**Comment by MaxJewell** [comment]
Would you be able to add the Policy ID's you are trying to verify onto either of the social media's please.

**Comment by puffiesnft** [comment]
We added the Policy ID on Twitter
https://twitter.com/PuffiesC/status/1467862880687169542

**Comment by puffiesnft** [comment]
Is this ok? The pr seems closed but I can't see where it says if it was merged or not

**Pull request merged**
