### PR TITLE
Verify MADAzine Covers

### PR DESCRIPTION
**Pull request by MarcoZeroNFT**
https://c-nftagency.com/
https://twitter.com/UKCNFTAgent1
https://twitter.com/marco__zeroNFT

### CODE REVIEW

**Comment by KaiNFT** [comment]
Hi Contributor, 

Can you please provide a link on your website/twitter to where I can locate your Policy ID.

**Comment by MarcoZeroNFT** [comment]
> Hi Contributor,
> 
> Can you please provide a link on your website/twitter to where I can locate your Policy ID.

Hey, of course! 
https://c-nftagency.com

**Comment by MarcoZeroNFT** [comment]
You can locate it directly here. The website is yet being updated.

https://twitter.com/marco__zeroNFT/status/1461926813937147910?t=4bMF8WN567sQ2Tf9DuCW7A&s=19

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
