### PR TITLE
Ash and Tray comic strip

### PR DESCRIPTION
**Pull request by veopixelado**
These are project social links and website:

twitter: https://twitter.com/ashandtraycomic
discord server: https://discord.gg/NMg6CpcZyd
website: https://pixelado.art/projects/ash-and-tray-comic-strip-cardano-nft/
tweet: https://twitter.com/ashandtraycomic/status/1462877054018502661?s=20

### CODE REVIEW

**Comment by veopixelado** [comment]
Hi @KaiNFT @CNFT-io @TomStray I created this new pull request, after all my other attemps were closes with no explanation, I've been trying this for more than a month, getting errors even though I am following exactly the process as explained in the video, I have screenshots. Please I need to verify this or at least guide me because I don't understand where the issues are. 
Looking forward to your reply,
best

**Comment by CNFT-io** [comment]
The reason is; 'File Ash and Tray Season 1 is not in projects directory!'

**Comment by veopixelado** [comment]
@CNFT-io thanks for the reply, I just replied to you on twitter, i attached two screenshots because I did submitted the pull request in the projects folder, but don't know why or how it was moved.. now I don't know how to move it and re-commit (don't even know what's that).. I just followed step by step, but no idea of this... thanks again for your fast reply but i need help

**Comment by CNFT-io** [comment]
@veopixelado - Do you just want to add this? 

[
  {
    "project": "Ash and Tray",
    "policies": [
      "d28f39739e0d19974ee3c961142b0e729b8341432158ccd9e5856ac8"
    ]
  }
]

**Comment by veopixelado** [comment]
@CNFT-io Yes please!! with this specific project name please, pasting here:
[
{
"project": "Ash and Tray Season 1",
"policies": [
"d28f39739e0d19974ee3c961142b0e729b8341432158ccd9e5856ac8"
]
}
]

**Comment by CNFT-io** [comment]
I have done this for you.

**Comment by veopixelado** [comment]
@CNFT-io  thank you very much! I just checked that it's already verified! yes! thanks! 
you'd take a look at the project by the way :)
Thanks!

**Pull request closed without merging**
