### PR TITLE
Create AdaApeClub

### PR DESCRIPTION
**Pull request by FredrickDean**
Created AdaApeClub + AdaApeClubVIPPass

### CODE REVIEW

**Comment by AnOnlineGuy** [comment]
Please may you add all your socials

**Comment by FredrickDean** [comment]
https://twitter.com/AdaApeClub

Policy ID is in our bio

**Comment by AnOnlineGuy** [comment]
You have 2 IDs in the code. Please Include both.

**Comment by FredrickDean** [comment]
my apologies, both have now been added to https://twitter.com/AdaApeClub bio

**Pull request merged**
