### PR TITLE
Funny Sarcastic Stuffs

### PR DESCRIPTION
**Pull request by todebubu**
https://twitter.com/Funny_FSS/status/1489696267286585352?s=20&t=y06oP_WdG5XXi9GfaeAajg

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

 Your social media is very new, do you have another form of social media or a website I can use to verify you?

**Comment by todebubu** [comment]
Hello there,
I’m a beginner, this is my first project, so i don’t have any other social media tied to this project.

Thank you ,
Andrei TODERICA
Funny Sarcastic Stuffs

**Comment by KaiNFT** [comment]
Dear Contributor, 

You must have a valid website that's directly linked to your project in order for me to verify this request.

**Comment by KaiNFT** [comment]
Closed due to inactivity

**Pull request closed without merging**
