### PR TITLE
Update thiscrazylife policies

### PR DESCRIPTION
**Pull request by ian6868**
Added new policy. Policies can be found here https://www.thiscrazylife.io/policies. Thank you.

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

The last policy ID you've listed is not listed on your website.

**Comment by ian6868** [comment]
Hi, I see the policy on my site, I have just checked. Please see both screenshots. One is my view of my pull request, the last policy is the same as the policy on my screenshot from my website. Please let me know if there is still an issue. Thank you

cnft io2
cnft io

**Comment by ian6868** [comment]
Hi, Sorry, I just realized what policy was missing. Please check the website now https://www.thiscrazylife.io/policies. The last two policies listed should be the last two policies on my pull request. Sorry for the mistake.

**Comment by ian6868** [comment]
Hi,I have update my website. Have you had a chance to take a look?Thank youIanOn Jan 17, 2022 6:56 AM, KaiNFT ***@***.***> wrote:
Dear Contributor,
The last policy ID you've listed is not listed on your website.

**Comment by ian6868** [comment]
Going to close this and submit a new one.

**Pull request closed without merging**
