### PR TITLE
Create StrangeCreatures by CubeForm

### PR DESCRIPTION
**Pull request by CubeForm-CNFT**
StrangeCreatures by CubeForm
https://twitter.com/CubeForm_NFT

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

I can't seem to find the Policy ID  on your twitter. Please can you ensure that it is posted so i can verify you own it.

**Comment by CubeForm-CNFT** [comment]
I posted it as comment in my pinned tweet♥️

Il giorno ven 14 gen 2022 alle 14:22 KaiNFT ***@***.***> ha
scritto:

**Comment by MaxJewell** [comment]
The policy ID does not seem to be in the comments.
Please add this and let us know!

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
