### PR TITLE
Added Isometric World policy id

### PR DESCRIPTION
**Pull request by IsometricWorld**
Link to website with our policy id
https://www.isometricworld.eu/about

### CODE REVIEW

**Comment by IsometricWorld** [comment]
We have tweeted our pull request on our Twitter, (link below)
https://twitter.com/IsometricWorld_/status/1457749582243315712?s=20

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs from your "Hajdari" code onto your discord.

**Comment by IsometricWorld** [comment]
They are already there, the link is https://discord.gg/EmD3Yfsx6x

**Comment by IsometricWorld** [comment]
Hello there seems to be an error on my end. The only policy id for the
Isometric World Project is below. I accidentally sent the hajdari project
policy ids to this pull request above is there anyway you could remove
those and only keep this one as it is our only policy id. Sorry about the
error.

721e3dcf9f6778606aae39da690234136e3d6d32e2083275e4e105ae

**Comment by Hajdari-CNFT** [comment]
Don't mind the above message, people just needed to relist their assets im starting to see the verified nfts coming up

**Pull request merged**
