### PR TITLE
Update CyberPunks - additional PolicyID (https://cyber-punks.xyz/#/CelestialLanding)

### PR DESCRIPTION
**Pull request by Habacef**
https://cyber-punks.xyz/#/CelestialLanding

Here the newly added Policy ID (last lane) is stated at the bottom of the website!

### CODE REVIEW

**Comment by Habacef** [comment]
Hello, when will this be processed?

**Comment by MaxJewell** [comment]
I can verify c35a7adcdfecdc96d5aabfe836bd4ca457657c88d9d0283093a19024 but no others as I will need links to the Policy ID's on the website you have provided.

When you have done this please let me know..
Thanks

**Comment by Habacef** [comment]
The others are already verified. I only added one...

**Comment by MaxJewell** [comment]
I understand this. However to avoid verification twice can I request you remove them.

Many thanks.

**Comment by Habacef** [comment]
Ah, thanks, yeah for me it is not clear wether all policy IDs are needed to be listed and resubmitted, I thought it is some kind of automated and all policies need to be in here... so in the JSON I’ll include just new policies which I want to add for future validations? 
Cheers and thanks! :)

**Comment by MaxJewell** [comment]
Just let me know when you have made the changes.

**Comment by Habacef** [comment]
What changes? I want to still have the old policies in place please..

**Pull request closed without merging**
