### PR TITLE
Adding project names to NFT Dutch Tripping Art

### PR DESCRIPTION
**Pull request by 0ldManPlaying**
Adding the TAG and Project name to NFT ART

### CODE REVIEW

**Comment by 0ldManPlaying** [comment]
Dear MaxJewell, My twitter is : https://twitter.com/0ldmanplaying  And policy ID : e0881f34180c4b66509a454da4b15f2e4f1963a61b4c8e423987a46e

**Comment by MaxJewell** [comment]
I will need the policy ID on the twitter account to verify it is you.

Thanks.

**Comment by 0ldManPlaying** [comment]
What do you mean, sorry i dont understand your question I guess.

**Comment by 0ldManPlaying** [comment]
I see that my twitter isnt Verified, will do this and will get back at you

**Pull request closed without merging**
