### PR TITLE
Create BitsServe

### PR DESCRIPTION
**Pull request by yopkub**
Add Policy IDs for BitsServe.

Twitter : https://twitter.com/BitsServe

### CODE REVIEW

**Comment by yopkub** [comment]
> Add Policy IDs for BitsServe.
>"cc8e45713c50e0a58512b97e2bd223000a21c798e526f224f5eea30a" 

> Twitter : https://twitter.com/BitsServe

**Comment by yopkub** [comment]
@Dean00K  
Please help me, My Pull request merge for verify cnft is correctly ?

**Comment by Dean00K** [comment]
Morning, will take a look shortly. Thanks for the message!

**Comment by yopkub** [comment]
Thank you very much.

If you have any require, please let me know to success modify.

**Comment by yopkub** [comment]
@Dean00K 
My pull request have anything wrong ?
😭

**Comment by Dean00K** [comment]
Yes, sorry, Busy busy. Was meaning to get back to you. Are you a collaboration project with cbits? Or do you own the original cbits you're using to create new cbit NFTs? What's the story here with your project and CardanoBits? I need to do my verification process and due diligence.

**Comment by yopkub** [comment]
Thank you for support,

BitsServe isn’t collaborate with cbits anymore.
I just create it byself (inspiration from cbits)


BitsServe is project to create many character to server something shifting. 💁🏻‍♂️


for clearly, BitsServe is not any relate with cbits.

**Comment by Dean00K** [comment]
Okay - Let me talk to the owners of the website and ill get back to you. I can't give you verification just yet. Please wait patiently. Thank you.

**Comment by Dean00K** [comment]
In the mean time, can you go back and delete those other merges you did and just leave the "created bitserve" commit

**Comment by yopkub** [comment]
#242 Pull request, I already closed (because my polidy id worng)

then i open new one #245

**Comment by Dean00K** [comment]
Untitled

**Comment by Dean00K** [comment]
i mean those ones that are circled

**Comment by yopkub** [comment]
Sorry, how to delete ?
I click in to that your circle.
But not any buton to click delete

**Comment by Dean00K** [comment]
you should be able to edit it - and just make paste over the top your original commit?

**Comment by yopkub** [comment]
1506364B-A2FA-4740-8E96-1C5339B153AA
ED27766A-5C47-4C5B-824D-ABE0DC094715


Have not ant edit 😭

**Comment by Dean00K** [comment]
copy and paste and open a new one :)
ill close this one off afterwards

**Comment by yopkub** [comment]
Okay, i will do next 3hr.
Now i’m on the road.

thx

**Comment by yopkub** [comment]
@Dean00K
I can't create new one because name is same this pull request. Or I need to close this #245 first ?

**Comment by Dean00K** [comment]
yeah close it, but obviously copy your work first and re do with same name.

**Pull request closed without merging**
