### PR TITLE
CardanoScape

### PR DESCRIPTION
**Pull request by Rickaap**
CardanoScape digital NFTs

https://twitter.com/CardanoScape

### CODE REVIEW

**Comment by Rickaap** [comment]
11cf9383661c51074891302e7e7bc0d29fc67c1c262cf3c37abb0deb is the policy ID

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence via another form of social media as your username and twitter account do not match up and it is a brand new account.

**Comment by Rickaap** [comment]
https://twitter.com/CardanoScape/status/1476550655674310660 

this is the tweet with my github request

**Comment by KaiNFT** [comment]
Do you happen to have a website/instagram also?

**Comment by Rickaap** [comment]
No I just started. But minted my first NFTs on CNFT.io
Want to secure the name and will expand my social media coverage. Could you please secure CardanoScape for me? Thanks in advance

**Comment by Rickaap** [comment]
https://cnft.io/token/61cdc0cf4185f57d50fa496d

first NFT btw

**Comment by Rickaap** [comment]
instagram is @cardanoscape

**Pull request merged**
