### PR TITLE
DoodlesXXX

### PR DESCRIPTION
**Pull request by DoodlesXXX**
https://twitter.com/DoodlesXXX

https://linktr.ee/DoodleXXX

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please put the correct policy ID in your file, he policy ID you have listed is the one from the template.

**Comment by KaiNFT** [comment]
Dear Contributor,

Please put the correct policy ID in your file.

**Comment by DoodlesXXX** [comment]
I have put the policy ID in my file.

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by MaxJewell** [comment]
Due to inactivity on this pull request we will have to close this request. 
Feel free to open a new request when you have gathered everything you need to be verified.

**Pull request closed without merging**
