### PR TITLE
TranquilityGirl

### PR DESCRIPTION
**Pull request by Chachi200688**
[
](https://twitter.com/Anuwrld/status/1483237514559242251?s=20)

85274b3d6bf1f14d1566aeb498c733db8c3269d8ca85997d02c5ccc8

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning,
Please use the new JSON format in the Readme file on the home page.
https://github.com/Cardano-NFTs/policyIDs/blob/main/README.md

**Comment by Chachi200688** [comment]
> Morning,
> Please use the new JSON format in the Readme file on the home page.
> https://github.com/Cardano-NFTs/policyIDs/blob/main/README.md

I am so lost , what do I have to put into the Json validator? then what after that? sorry new to this

**Comment by Chachi200688** [comment]
[
   {
      "project":"TranquilityGirl",
      "policies":[
         "85274b3d6bf1f14d1566aeb498c733db8c3269d8ca85997d02c5ccc8"
      ]
   }
]

**Comment by Chachi200688** [comment]
<blockquote class="twitter-tweet"><p lang="fr" dir="ltr">[<br> {<br> &quot;project&quot;:&quot;TranquilityGirl&quot;,<br> &quot;policies&quot;:[<br> &quot;85274b3d6bf1f14d1566aeb498c733db8c3269d8ca85997d02c5ccc8&quot;<br> ]<br> }<br>]</p>&mdash; Anthony P. (@Anuwrld) <a href="https://twitter.com/Anuwrld/status/1483529686466584583?ref_src=twsrc%5Etfw">January 18, 2022</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by TomStray** [comment]
Dear Contributor, please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
