### PR TITLE
Create Baby Otter Party

### PR DESCRIPTION
**Pull request by BabyOtterNFT**
Hi, updated my code and applying for listing my cnft project on cnft.io

Twitter: https://twitter.com/BabyOtterParty
Discord: https://discord.gg/FeAY5CSa
WEBSITE: https://babyotter.io/

policy id:
602271c40a15510c68c5fe4120a9261cd48a7291af8a8a78395edc13
https://cardanoscan.io/tokenPolicy/602271c40a15510c68c5fe4120a9261cd48a7291af8a8a78395edc13

Listing pull request on twitter
https://twitter.com/BabyOtterParty/status/1465600463122812931

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file format in order for me to merge the pull request.

**Comment by BabyOtterNFT** [comment]
{
   "721":{
      "<policy_id>":{
         "<asset_name>":{
            "name":"<otter_name_data>",
            "image":"<ipfs_link>",
            "mediaType":"<mime_type>",
            "description":"<description>",
            "files":[
               {
                  "name":"<asset_name>",
                  "mediaType":"<mime_type>",
                  "src":"<ipfs_link>"
               }
            ],
            "dna":"<dna_data>",
            "date":"<created_Unix_Time_data>",
            "attributes":[
               {
                  "trait_type":"Background",
                  "value":"<background_data>"
               },
               {
                  "trait_type":"Shadow",
                  "value":"<shadow_data>"
               },
               {
                  "trait_type":"Body",
                  "value":"<basic_data>"
               },
               {
                  "trait_type":"Face",
                  "value":"<face_data>"
               },
               {
                  "trait_type":"Suit",
                  "value":"<suit_data>"
               },
               {
                  "trait_type":"Hat",
                  "value":"<hat_data>"
               },
               {
                  "trait_type":"Hand Accessories",
                  "value":"<h_accessories_data>"
               },
               {
                  "trait_type":"Other Accessories",
                  "value":"<other_accessories_data>"
               }
            ]
         }
      },
      "version":"1.0"
   }
}

**Comment by BabyOtterNFT** [comment]
image

**Comment by BabyOtterNFT** [comment]
> Dear Contributor,
> 
> Please make the necessary adjustments to your JSON file format in order for me to merge the pull request.

Are these okay?

**Comment by BabyOtterNFT** [comment]
{
   "721":{
      "<policy_id>":{
         "<asset_name>":{
            "name":"<otter_name_data>",
            "image":"<ipfs_link>",
            "mediaType":"<mime_type>",
            "description":"<description>",
            "files":[
               {
                  "name":"<asset_name>",
                  "mediaType":"<mime_type>",
                  "src":"<ipfs_link>"
               }
            ],
            "dna":"<dna_data>",
            "date":"<created_Unix_Time_data>",
            "attributes":[
               {
                  "trait_type":"Background",
                  "value":"<background_data>"
               },
               {
                  "trait_type":"Shadow",
                  "value":"<shadow_data>"
               },
               {
                  "trait_type":"Body",
                  "value":"<basic_data>"
               },
               {
                  "trait_type":"Face",
                  "value":"<face_data>"
               },
               {
                  "trait_type":"Suit",
                  "value":"<suit_data>"
               },
               {
                  "trait_type":"Hat",
                  "value":"<hat_data>"
               },
               {
                  "trait_type":"Hand Accessories",
                  "value":"<h_accessories_data>"
               },
               {
                  "trait_type":"Other Accessories",
                  "value":"<other_accessories_data>"
               }
            ]
         }
      },
      "version":"1.0"
   }
}

**Comment by MaxJewell** [comment]
Please use the new JSON format in the Readme file on the home page.

**Pull request closed without merging**
