### PR TITLE
TheCNFTartistBS

### PR DESCRIPTION
**Pull request by TheCNFTartistBS**
Starting a new CNFT Project I'm a independent artist posting my one of a kind art.

### CODE REVIEW

**Comment by TheCNFTartistBS** [comment]
I don't have a website yet here is my twitter. https://twitter.com/theCNFTartistBS 
I did Tweet my pull request.
I'm trying to get this piece of art verified
https://cnft.io/token.php?id=6136258a7977b05ba3ddc405
Thank you

**Comment by TheCNFTartistBS** [comment]
I have a website now its. www.thecnftartistbs.com. here is also my public address for pool.pm
phttps://pool.pm/addr1q9nvx0ld63rtvr7jsr0pcskt3ak6q7r6m6pfuw5zd2yrmf53sp9pq6d9wedzl2vzeyrgxfky7kekexg4w0kk4uv89l0qkphfqc
If you need anything else let me know. I do have a question if when I want to launch more CNFTs do I need to create a new pull request for that new policy ID and sit in the pull request Queue(to get verified)? if you could let me know that would be great

thank you

**Comment by MaxJewell** [comment]
Would you be able to remove the comma at the end of the policy ID please.
Once you have done so please let me know and we can move forward.

Many thanks

**Comment by TheCNFTartistBS** [comment]
I removed the comma. sorry about that.

**Comment by TheCNFTartistBS** [comment]
I removed the comma sorry about that Sent from my Galaxy
-------- Original message --------From: MaxJewell ***@***.***> Date: 9/28/21  10:53 AM  (GMT-05:00) To: Cardano-NFTs/policyIDs ***@***.***> Cc: TheCNFTartistBS ***@***.***>, Author ***@***.***> Subject: Re: [Cardano-NFTs/policyIDs] TheCNFTartistBS (#852) 
Would you be able to remove the comma at the end of the policy ID please.
Once you have done so please let me know and we can move forward.
Many thanks

**Pull request merged**
