### PR TITLE
Added ADARock

### PR DESCRIPTION
**Pull request by adarockio**
www.adarock.io

### CODE REVIEW

**Comment by adarockio** [comment]
Twitter: https://twitter.com/ADARock_io/status/1435654400492589062

**Comment by adarockio** [comment]
Hey guys, would love to get my project verified! :) Keep up the good work!

**Comment by TomStray** [comment]
Dear Contributor, please add an opening speech mark to the start of line 5.

**Comment by adarockio** [comment]
done @TomStray

**Comment by adarockio** [comment]
Hey @TomStray, could you please delete the policy "0108cea3f27deb91da611f823533a726df10369a6fdb3832926b915a"? Thank you very much!

**Pull request merged**
