### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by Sebsone-dwg**
Added new policies from new tokens for the collection.
Policies:
4981cd1f2a83e6c48b52fef9f2d2d666464055f36e56435b893859a2
66b4c2d4dbb92c13354da6938c2bdbb1e661d5b357ea121871104906
92004e417b2dbf41c3cbd6b5d056657aa7e19818f57049d5c12c100b
f0eddce0ec97484f8df3e3cd61cdc0202c1eaba01ecbb6b7ee4e0063

### CODE REVIEW

**Comment by MaxJewell** [comment]
Afternoon,
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by Sebsone-dwg** [comment]
hi! Thank you. here are some links:

Twitter: https://twitter.com/Sebsone_dwg
Site:https://www.behance.net/sebsone13
ig:https://www.instagram.com/sebsone.dwg/ & https://www.instagram.com/mycnft/

**Comment by TomStray** [comment]
Dear Contributor, your code has conflicts. I believe it is the last commit that you made that caused the conflicts, this means that it should be your policy ID on line 14 that is causing the conflicts. Please remove this line again and we can see if it resolves the issue.

When you make new requests, make sure to not add any policy ID that have already been verified.

Many Thanks,

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
