### PR TITLE
Create forest-tokens

### PR DESCRIPTION
**Pull request by kwillter**
Hope this is all good, thanks!

### CODE REVIEW

**Comment by kwillter** [comment]
https://twitter.com/kwillter1/status/1429246564363612162?s=20

**Comment by Dean00K** [comment]
Hey, your Policy ID isn't showing - can you double check it for me please.

**Comment by kwillter** [comment]
> Hey, your Policy ID isn't showing - can you double check it for me please.

Sorry - first time doing this here, tried my best to follow the tutorials... I pasted the policy ID into the code for the pull request, and when I check the "files changed" section, the policy id is still there, and still correct... 

This is the policy ID # 756dd7b54b70140917348d06801e65a32a4d2abda41896fab1e09d8a

Please let me know if I am still missing something, thank you.

**Comment by kwillter** [comment]
> Hey, your Policy ID isn't showing - can you double check it for me please.

Sorry Dean - I think this is what you were looking for?

https://tokhun.io/explore/756dd7b54b70140917348d06801e65a32a4d2abda41896fab1e09d8a.6of36001

**Comment by Dean00K** [comment]
Cool, can i get a pool.pm linkk to one of these NFTs please?

**Comment by kwillter** [comment]
> Cool, can i get a pool.pm linkk to one of these NFTs please?

https://pool.pm/addr1q8gwfchnx2hrnz4tkmm9a3wav04m6y7p62hd4xkujk43f0r7f724skdwvgdrmmjuur6x3fuf6j2f00nyuy49uklrm0vqk9myvj

**Pull request merged**
