### PR TITLE
Update BitsServe PolicyIDs

### PR DESCRIPTION
**Pull request by yopkub**
Update BitsServe PolicyIDs

### CODE REVIEW

**Comment by yopkub** [comment]
@Dean00K 
Hi, 
First time to try update policyIDs by edit file changed. I'm not sure correctly. lol

I know cnft.io staff so hard working and busy atm.
Cheer up for cnft.io improvement.


Thx  Sir,

**Comment by skilltestz** [comment]
it's correct 
@Dean00K 
image

**Comment by yopkub** [comment]
@itsmestale It's correctly ?

**Comment by yopkub** [comment]
@itsmestale Thank god, cnft.io come back. 🎊
Please consider to approve addition policyIDs, I have to launch next drop. 

Thank you stale, I know your team busy.

**Comment by yopkub** [comment]
Please,,,,, @itsmestale

**Comment by yopkub** [comment]
Dear Stale,
New Drop already sold out on cnft.io yesterday (8 Sep’21)
For collector to run aftermarket, please verify to get check mark✅

Thank tou, sir
638156B8-8E11-4DB1-B325-5DFC923CFAB1

**Pull request merged**
