### PR TITLE
Rename current project to Lowpoly - JPNFTArt and add another policy ID to the project

### PR DESCRIPTION
**Pull request by pbhudia**
https://www.instagram.com/jpnftart

790caf08b7b118cdddfdfba4a79530b5a4ff6ca4706bb0e486e4ef82

### CODE REVIEW

**Comment by pbhudia** [comment]
> https://www.instagram.com/jpnftart
> 
> 790caf08b7b118cdddfdfba4a79530b5a4ff6ca4706bb0e486e4ef82

@KaiNFT - sorry i am new to this. When will this get verified and changes made? I have made changed to the project name and added an additional policy ID to the project.

**Comment by pbhudia** [comment]
Policy ID to verify - 790caf08b7b118cdddfdfba4a79530b5a4ff6ca4706bb0e486e4ef82

@TomStray @AnOnlineGuy - sorry i am new to this and tagging you guys for any assistance. When will this get verified and changes made? I have made changes to the project name and added an additional policy ID to the project.

If any issues please let me know.

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID on line 6 to your Instagram.

**Comment by pbhudia** [comment]
Hi.

That has been added to my instagram now.

Thanks

**Comment by TomStray** [comment]
Apologies, I meant add the policy ID on line 5

**Comment by pbhudia** [comment]
Hi

That's been added now. Thanks

**Comment by pbhudia** [comment]
Hi.

That's been added now
Thanks

**Comment by pbhudia** [comment]
Please can you rename the project from "Lowpoly" to "Lowpoly - JPNFTArt"

Also move policy ID 790caf08b7b118cdddfdfba4a79530b5a4ff6ca4706bb0e486e4ef82
From "YourFirstProjectName" project to "Lowpoly - JPNFTArt" project?

**Pull request merged**
