### PR TITLE
Added Christmas Special to Creepy Cardanos

### PR DESCRIPTION
**Pull request by Cooperal1**
[
{
    "project": "Creepy Cardanos",
    "tags": [
        "Creepy Cardanos"
    ],
    "policies": [
        "b6ce56a5f1bdc8bf0f1f4575fb8d085cdeb7901f4ea17d072c897338",
        "e1107a8f89ccfd45b355e98bff8963b796cbfc6b3c6e0b59fee248c6"
    ]
    },
    {
        "project": "Creepy Cardanos | ChristmasSpecial",
        "policies": [
            "98ef05212a1d4acd12387e38dd5471855edc4c4248e4dab762581ff0"
        ]
    }
]

### CODE REVIEW

**Comment by Cooperal1** [comment]
Website - https://www.creepycardanos.com/
Twitter - https://twitter.com/CCardanos

**Comment by KaiNFT** [comment]
Dear Contributor,

Your file has conflicts, please make the necessary adjustments in order for me to merge the pull request.

**Comment by Cooperal1** [comment]
Hey, Think conflicts are resolved. Please let me know if anything else is needed. Thanks

**Comment by KaiNFT** [comment]
There are still conflicts, apologies for the delay. I am going to get someone to look into this for you.

**Comment by Cooperal1** [comment]
No problem and thank you

**Comment by KaiNFT** [comment]
Hi @Cooperal1

I'm going to close his request, please make another request with only 1 file with each policy ID(s) in it.

**Comment by Cooperal1** [comment]
Hi @KaiNFT I have submitted a new pull request with just our new collection to be added separate to our main collection. hopefully this will avoid the issues we had. Thanks

New pull request #5606

**Pull request closed without merging**
