### PR TITLE
Xanyart NFT

### PR DESCRIPTION
**Pull request by XanyRose**

### CODE REVIEW

**Review by XanyRose — COMMENTED** [review]
Please check update, i´m new and i make a few mistakes. ;)

**Review by XanyRose — COMMENTED** [review]
Policy ID change

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

**Comment by XanyRose** [comment]
My instagram page is where i put my nfts. If i have to create a twitter
account, tell me.

https://www.instagram.com/xanyartnft

Thanks. Regards

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID onto your Instagram so that I can verify it. As well as this, please change the square bracket on line 8 so that it is parallel with lines 2, 3, 5 and 6.

**Pull request closed without merging**
