### PR TITLE
Request to verify project InkWarriors

### PR DESCRIPTION
**Pull request by nftartisan**
This is a project of a collection of 13 NFTs (named Ink Warriors) with digitized printable (300 ppi) images of fantasy warriors. The images have been made by hand with ink and acrylic by the German-Spanish artist Juan Markus, part of our team NFT Artisans.

- The policy ID they all share is "c4c0ed3af962b8d27deac806bccc8f803e645c280932005100464d8c".
- They can be seen at our website. This is the direct link: https://www.nftartisans.xyz/collections/ink-warriors
- We recently got a Discort https://discord.gg/AJmHCVfwEk, but we don't have twitter account for now. However, here are our FB page https://www.facebook.com/nftartisans and Instagram account https://www.instagram.com/nft.artisans/ 

Please, let me know if you need any other information. We are pretty new to the space and this is our first project.

Thank you very much for all your help!

### CODE REVIEW

**Comment by nftartisan** [comment]
Our Twitter is ready! https://twitter.com/ArtisansNft/status/1430482754425147397

**Comment by Dean00K** [comment]
Hey team, a few issues from my side. These are not NFTs, these are fungible tokens. The project looks good. Nice website and everything, but Twitter is a little light on community engagement. There are 14 tokens under that policy (including a mirrored thief girl and your policy ID never locks) but you're telling everyone there are only 13 tokens? Policy locking is very important, if not locked already, at least having a date set for example helps with verification. which I can't do at this time. Let me know if you have any questions. Cheers

**Comment by nftartisan** [comment]
Hey, thanks for your reply. It is our first time doing something like this so we really appreciate your feedback. 

I can tell everyone about the 14th token and add it to the collection. It was a mistake on our part, we would love to burn that one but we just don't know how. 

We do all the minting through metromermaids.com and are very dependent on the options for policies they offer. Do you know if it would be possible to change the policy locking at this point? Please, if you know a non tech-savvy way to do it we are all ears. 

Metromermaids offers a 1-year locking. That would be our other option: to do again the collection under other ID with a one-year due date. Would that be enough for the verification?  Our last option is 13 closed policy IDs, but we don't want to go through that route if possible.

Thanks again for your help and all your hard work!

**Comment by Dean00K** [comment]
Hey - Just saw your comment but im just turning off my computer now and going to bed.. I will have a think about this and maybe talk to freddy from mermaids as well. You guys are not the first, so don't worry. It might help if I let freddy know about the verification process so he can help his customers with selecting the right options as well. You wouldn't need 13 closed policy IDs, all 13 NFTs can be under a single policy ID similar to how it is now. you can't change them now though, it would be a burn and re mint. But again, there is no official burn address on cardano yet. Not a trusted one from the cardano foundation at least. Will get back on this tomorrow! Thank you for your understanding!

**Comment by nftartisan** [comment]
Not a problem at all. It's great that you are willing to put all this effort not only for us but for the community.
Have a good night!

**Comment by nftartisan** [comment]
Thanks for the heads up. It is heartbreaking to hear it at his point to tell the truth but well, I wrote to the email address they have provided... we'll see...

Hope everything goes well with you and I wish you the best, you have been extremely helpful.

**Comment by Dean00K** [comment]
thanks mate! good luck with you too.
________________________________

**Pull request closed without merging**
