### PR TITLE
Update Thakargc

### PR DESCRIPTION
**Pull request by Koelie1984**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Could we have a link to a twitter or website with the Policy ID's on them.

Thanks.

**Comment by Koelie1984** [comment]
twitter : @thaka_gopal_
Discord server : https://discord.gg/BX9S5QcN5Q

**Comment by MaxJewell** [comment]
Not all Policy ID's can be found. 
Could you leave links to each one after this comment then I can verify for you.

Thanks.

**Comment by Koelie1984** [comment]
It is in the discord server under policy channel

**Pull request merged**
