### PR TITLE
Create NFTwerk

### PR DESCRIPTION
**Pull request by FriscoTec**
Created NFTwerk project

### CODE REVIEW

**Comment by FriscoTec** [comment]
https://www.friscotec.com/

Thaank you! Please let me know if I need to modify anything. Happy Thursday!

On Thu, Oct 21, 2021 at 7:52 AM RedArchfiend ***@***.***>
wrote:

> Please provide social/website link that clearly states your Policy IDs.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://protect-us.mimecast.com/s/AftrCL91x8cPDQ86wsBPutF?domain=github.com>,
> or unsubscribe
> <https://protect-us.mimecast.com/s/h6VpCM8KyQC5yzmNktkhr1k?domain=github.com>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://protect-us.mimecast.com/s/6DsvCNkKz9tNqjy4PHjmw_l?domain=apps.apple.com>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>


-- 
Thank you.

**Comment by TomStray** [comment]
Dear Contributor, I haven't got anything through with your updated code. Please try again.

**Comment by FriscoTec** [comment]
Everything is aligned on the webpage. At least using a PC and most common
browsers. I'm not sure what other steps I need to do- have done the github
portion.

On Tue, Nov 2, 2021 at 7:03 AM TomStray ***@***.***> wrote:

> Dear Contributor, I haven't got anything through with your updated code.
> Please try again.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://protect-us.mimecast.com/s/ygO7CjRgoqCjz7rljFW83rT?domain=github.com>,
> or unsubscribe
> <https://protect-us.mimecast.com/s/Sz_cCkRjpZCnDMEYniV2xDj?domain=github.com>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://protect-us.mimecast.com/s/CgIUClYkq5coWBrOouyCi7l?domain=apps.apple.com>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>


-- 
Thank you.

**Comment by TomStray** [comment]
Dear Contributor, I am on Microsoft Edge on PC and it is not aligned for me. This is what I can see:

image

Let me know if it is any different for you.

**Comment by FriscoTec** [comment]
[image: website.PNG]
Designed with Dreamweaver... Looks good there.Thanks for your patience!

On Tue, Nov 2, 2021 at 11:50 AM TomStray ***@***.***> wrote:

> Dear Contributor, I am on Microsoft Edge on PC and it is not aligned for
> me. This is what I can see:
>
> [image: image]
> <https://protect-us.mimecast.com/s/mj9OCv2xEotWJlpk4SQFAjR?domain=user-images.githubusercontent.com>
>
> Let me know if it is any different for you.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://protect-us.mimecast.com/s/M_ojCwpyGmCL5NJwPtqRyAX?domain=github.com>,
> or unsubscribe
> <https://protect-us.mimecast.com/s/5WolCxkzJvtJpXnWBcYGahq?domain=github.com>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://protect-us.mimecast.com/s/OUDkCyPAKrSNG4qBJsRpLw5?domain=apps.apple.com>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>


-- 
Thank you.

**Comment by TomStray** [comment]
Dear Contributor, I think you tried to add a picture to your previous comment but it only came through as text. As well as this, I will still need you code to be updated so that I can verify it.

If you have any questions, let me know.

**Comment by FriscoTec** [comment]
[image: website.PNG]
Hi, the pic shows on my end. Code alignment is correct.

On Thu, Nov 4, 2021 at 6:03 AM TomStray ***@***.***> wrote:

> Dear Contributor, I think you tried to add a picture to your previous
> comment but it only came through as text. As well as this, I will still
> need you code to be updated so that I can verify it.
>
> If you have any questions, let me know.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://protect-us.mimecast.com/s/eXAfC5ywO9c0y9VJptzdirn?domain=github.com>,
> or unsubscribe
> <https://protect-us.mimecast.com/s/oRXEC68xPRCoRmnN0t6aJrr?domain=github.com>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://protect-us.mimecast.com/s/4PmMC73yQLSmrNOgVSBMQlh?domain=apps.apple.com>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>


-- 
Thank you.

**Comment by FriscoTec** [comment]
website

**Comment by FriscoTec** [comment]
I saw the code wasn't aligned at Github. I adjusted that. Sorry- I thought
you meant the web code for the page. I also posted the reply at Github
instead of via email.. could this be reopened?

On Mon, Nov 8, 2021 at 5:47 AM CNFT-io ***@***.***> wrote:

> Closed #2113
> <https://protect-us.mimecast.com/s/QyvFCgJDlLUlOm5y3SoGQQf?domain=github.com>
> .
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://protect-us.mimecast.com/s/uKzLC0RoJVC2qM0Bxiwjl0i?domain=github.com>,
> or unsubscribe
> <https://protect-us.mimecast.com/s/Jag3CjRgoqCjK31mrT5BX6m?domain=github.com>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://protect-us.mimecast.com/s/KWhQCkRjpZCn8r3BES90x7b?domain=apps.apple.com>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>


-- 
Thank you.

**Pull request closed without merging**
