### PR TITLE
CardanoSesang

### PR DESCRIPTION
**Pull request by CardanoSesang**
twitter.com/CardanoSesang

twitter.com/CardanoSesang/status/1466119749826457603

https://www.cardanosesang.com/

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by CardanoSesang** [comment]
Good morning Kai,

I keep getting this message "Validate JSONs: All jobs have failed".  I may
be doing something really wrong here.

**Comment by KaiNFT** [comment]
Dear Contributor, 

apologies for the delay on the reply, it's still informing me that your file is not in the projects directory, please check the README.md for some help.

**Comment by CardanoSesang** [comment]
> Dear Contributor,
> 
> apologies for the delay on the reply, it's still informing me that your file is not in the projects directory, please check the README.md for some help.

Sorry, I don't understand.  I read the README.md multiple times and watched and followed the Youtube tutorial video.  What am I doing wrong?  Any detailed instruction would be very appreciated.

**Comment by KaiNFT** [comment]
Dear Contributor,

Again sorry for the delay, but your commit now has conflicts, meaning its either already in the workspace or there is duplicate lines in your file, please make the necessary adjustments.

**Comment by MaxJewell** [comment]
Afternoon,
Due to inactivity in resolving your pull requests we will now close this request permanently.

**Pull request closed without merging**
