### PR TITLE
Update Gremoca

### PR DESCRIPTION
**Pull request by rirahemo**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide proof of Policy ID via website or social media so I can merge the pull request.

**Comment by rirahemo** [comment]
Gremoca social media

https://twitter.com/gremoca_art

**Comment by rirahemo** [comment]
Gremoca website

https://gremocaart.wordpress.com/

**Comment by rirahemo** [comment]
> Dear Contributor,
> 
> Please provide proof of Policy ID via website or social media so I can merge the pull request.

I forgot.  Thanks.

**Comment by KaiNFT** [comment]
Hi rirahemo,

I can't seem to find the Policy ID on your website "490741c4fcb9f7b7c9eadd5a52a7d9b3bb78fb0e77afd03e2f3b551c"

**Comment by rirahemo** [comment]
> Hi rirahemo,
> 
> I can't seem to find the Policy ID on your website "490741c4fcb9f7b7c9eadd5a52a7d9b3bb78fb0e77afd03e2f3b551c"

But its on twitter, i need for mint new nfts.  Or i have to mint them first?

**Comment by KaiNFT** [comment]
Hi,

Your twitter link does not work.

**Comment by rirahemo** [comment]
So sorry i think this is it.

https://twitter.com/gremocaart

**Comment by rirahemo** [comment]
> Hi,
> 
> Your twitter link does not work.

So sorry check again, please.

**Pull request merged**
