### PR TITLE
Added Grid Project

### PR DESCRIPTION
**Pull request by Sebsone-dwg**
Grid Project capsules the C-Grid arts

### CODE REVIEW

**Comment by Sebsone-dwg** [comment]
Twitter: https://twitter.com/Sebsone_dwg
Site:https://www.behance.net/sebsone13
ig:https://www.instagram.com/sebsone.dwg/

**Comment by TomStray** [comment]
Dear Contributor, please put your policy IDs on your twitter so that I can verify. Also, please remove the comma at the end of line 8.

**Comment by Sebsone-dwg** [comment]
> Dear Contributor, please put your policy IDs on your twitter so that I can verify. Also, please remove the comma at the end of line 8.

Done! Hope everything else is good. Thank you sir!

**Comment by Sebsone-dwg** [comment]
@

> > Dear Contributor, please put your policy IDs on your twitter so that I can verify. Also, please remove the comma at the end of line 8.
> 
> Done! Hope everything else is good. Thank you sir!

@TomStray

**Pull request merged**
