### PR TITLE
PokePlanters

### PR DESCRIPTION
**Pull request by declouxaproductions**
For every CNFT purchased you will support 1000 trees planted in Canada

### CODE REVIEW

**Comment by declouxaproductions** [comment]
Hi Im new I just followed a tutorial. This is 1 of my nfts, I have 71 more to add later on when i have ADA to mint. Is that if I update as I g? thanks <3 love u long time 

- a a ron

**Comment by declouxaproductions** [comment]
verify me ! 

https://declouxa.wixsite.com/pokeplanters?fbclid=IwAR3NdmtWIZcDgMX43Gd1pqK8PW8evsMsgkHehqZzRPekKdsQ_VCqyqscXRQ

https://discord.gg/ZcDSASTd

youtube.com/declouxa

instagram.com/_declouxa

twitter.com/aaron_decloux

**Comment by declouxaproductions** [comment]
if one my CNFT sells while Im doing this, can it still be verified as part of the project ? thanks ! <3

**Comment by declouxaproductions** [comment]
Damn I cant figure this out !

**Comment by KaiNFT** [comment]
Dear Contributor,

 This request will now be closed, make a new ticket with the following criteria; the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
