### PR TITLE
I am starting a new one

### PR DESCRIPTION
**Pull request by DammeCoding**
I am working alone on this project and the aim is to mint NFTs to different ocasions and purposes.

### CODE REVIEW

**Comment by Dean00K** [comment]
Hey, so are these 2 different projects? If so, I need you to go back and use the second template from the readme.md - It will show you how to create under the one commit. Even if I could approve and merge these as they were, the JSON file is invalid. There are a couple of commas in the wrong places - if you need a hand DM me @Dean_00K on twitter or Dean_00K#3046 on discord.

**Comment by DammeCoding** [comment]
Sorry for the mess, i have no previous experience with this kind of stuff. I deleted the old request and created a new one. Thank you !

**Comment by DammeCoding** [comment]
> 
> 
> Hey, so are these 2 different projects? If so, I need you to go back and use the second template from the readme.md - It will show you how to create under the one commit. Even if I could approve and merge these as they were, the JSON file is invalid. There are a couple of commas in the wrong places - if you need a hand DM me @Dean_00K on twitter or Dean_00K#3046 on discord.

Hi! 
I hope it´s right this time. Thank you for all the help!

**Comment by Dean00K** [comment]
Almost :)
Just add [ and ] to the start and end of your lines and it will be valid.
Also, I can't approve all of those tags.
We can’t allow the tags you have included in your commit due to the broad description. If someone else wanted to include the name “Launch Day” or that particular date in the name or description of their CNFT, the cnft.io website listing would display as “not a real Aether Crypto” or similar. These tags need to be specific to your project only. We need you to remove your "Launch Day" and date, happy for you to keep the title and the "the first crypto to be sent to space" tags. Please review and make necessary changes. Thank you.

**Comment by DammeCoding** [comment]
Hopefully it is right this time :) Otherwise i might start learning some programming basics

**Comment by Dean00K** [comment]
Yep looks good now - have you got a website or twitter or anything?

**Comment by DammeCoding** [comment]
Yes!

PaulCucurz on Twitter ***@***.***)

Thank you !

Den ons 18 aug. 2021 kl 11:46 skrev Dean00K ***@***.***>:

**Pull request merged**
