### PR TITLE
Create DEADPXLZ x Cypherkicks

### PR DESCRIPTION
**Pull request by DEADPXLZ**

### CODE REVIEW

**Comment by RedArchfiend** [comment]
Please provide links to social/website that clearly states Policy ID.

**Comment by DEADPXLZ** [comment]
> Please provide links to social/website that clearly states Policy ID.

This is a collab between two established projects which are already verified on CNFT.io, let's cut the red tape?

**All assets have been pre-minted and can be found here: https://pool.pm/addr1qyftf2y2z8cxu8jycw4eduydef65cyjxgecersc0ayvdtzq48nqew7pu3xfufml7srdwgh0l9njwjpv43wucwvqqn2sqw663pv/2f596ad8**

**Comment by CNFT-io** [comment]
Let's not. 

Do as you're asked please, or we will just close the request. 

Just send your socials/websites where the policy ID is published.

**Comment by DEADPXLZ** [comment]
> Let's not.
> 
> Do as you're asked please, or we will just close the request.
> 
> Just send your socials/websites where the policy ID is published.

This should do it
[https://twitter.com/pxlzNFT/status/1445375896790224900?s=20]

**Pull request merged**
