### PR TITLE
Lizard King

### PR DESCRIPTION
**Pull request by OddNombra**
www.twitter.com/OddNombra/status/1478221206952103936

www.twitter.com/oddnombra

www.withkoji.com/@OddNombra

www.discord.gg/9Zm3eASf

https://oddnombra.godaddysites.com/

### CODE REVIEW

**Review by OddNombra — COMMENTED** [review]
JSON files were validated. Need Githubs end for verification

**Comment by OddNombra** [comment]
Need Help

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by KaiNFT** [comment]
Dear Contributor,

This request will now be closed, make a new ticket with the following criteria; the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
