### PR TITLE
added project 'DigiTits'

### PR DESCRIPTION
**Pull request by DigiTits**
DigiTits - Digital Tits

### CODE REVIEW

**Comment by DigiTits** [comment]
www.digitits.co
www.discord.com/XCcZ7mYD
www.twitter.com/DigiTitsNFT

**Comment by KaiNFT** [comment]
Hi Contributor, 

Please can you make the necessary adjustments to the JSON file so I can merge the pull request.

**Comment by MaxJewell** [comment]
Please use the new JSON format in the Readme file on the home page.

**Comment by DigiTits** [comment]
Sir could you elaborate on the changes to be made , to get my Policy ID
verified by you ?

**Comment by AnOnlineGuy** [comment]
We have made another change to GitHub that you should be aware of. 

I need you guys today to go through all the PRs and close them with this message. 

‘Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
