### PR TITLE
Added Striscione

### PR DESCRIPTION
**Pull request by Striscione**
We would like to get the policy ID verified 
you can find the policy ID on our Twitter @striscione_nft
it is also under the #policy-Id channel in our discord https://discord.gg/NYaNABkzA2

### CODE REVIEW

**Comment by Striscione** [comment]
14 days ago I json verified this
this process is really not that easy

**Comment by KaiNFT** [comment]
Dear Contributor,

Please correct the error in the json file so I can merge the pull request.

**Comment by Striscione** [comment]
im not sure how to correct it or whats even wrong with it

**Comment by Striscione** [comment]
honestly i dont even know how to navigate your website to fix it
the first pull request i tried I ran it through json and was given the ok
now I went to go back and do it over and said file already exists
nowhere could i find where to run it back through the json verifier

**Comment by Striscione** [comment]
I think I have fixed it

**Comment by Striscione** [comment]
> Dear Contributor,
> 
> Please correct the error in the json file so I can merge the pull request.

I think i got it done correctly

**Comment by Striscione** [comment]
thank you

**Comment by Striscione** [comment]
how do I edit it to add a second policy number

**Pull request merged**
