### PR TITLE
Update Zamunda Metaverse

### PR DESCRIPTION
**Pull request by femhab**

### CODE REVIEW

**Comment by femhab** [comment]
Noticed there is no space between Zamunda and Metaverse

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool.pm with your policy ID(s) on there so that I can verify.

**Comment by femhab** [comment]
https://zamunda.io/

https://twitter.com/zamunda_io

https://discord.com/invite/YZmdHTADMG

**Comment by femhab** [comment]
Note: this is just an update to what has been merged. You can verify from the file changed

**Pull request merged**
