### PR TITLE
Create Crypto Clans of Santas

### PR DESCRIPTION
**Pull request by CCoSMarcus**
[
  {
    "project": "CryptoClansOfSantas",
    "tags": [
      "CryptoClansOfSantas"
    ],
    "policies": [
      "436656392419291c4c5eb99888d85988a1e2d293eaff3f00998b51a2"
    ]
  }
]

### CODE REVIEW

**Comment by CCoSMarcus** [comment]
Hello

Website: https://cryptoclansofsantas.webflow.io/
Twitter: https://twitter.com/ClansOfSantas
Discord: https://discord.gg/YaRu7qekaC

**Comment by CCoSMarcus** [comment]
Hello

Website: https://cryptoclansofsantas.webflow.io/
Twitter: https://twitter.com/ClansOfSantas
Discord: https://discord.gg/YaRu7qekaC

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
