### PR TITLE
Ash and Tray Season 1

### PR DESCRIPTION
**Pull request by veopixelado**
Hi @TomStray following your instructions, I have created this new policy in the Projects folder.I want to verify my project, I created a monthly comic strip, using NFT-MAKER pro tools and I want to drop on December, 2.

These are project social links and website:

twitter: https://twitter.com/ashandtraycomic
discord server: https://discord.gg/KygaSfJP
website: https://pixelado.art/projects/ash-and-tray-comic-strip-cardano-nft/

I am adding a link to the tweet https://twitter.com/ashandtraycomic/status/1462877054018502661?s=20

### CODE REVIEW

**Comment by HRumson** [comment]
Dear Contributor, please use the new JSON format in the Readme file on the home page.

**Comment by veopixelado** [comment]
Hi @TomStray I don't know why I keep getting this json error (I don't have any coding skill so can't understand it..) but I just copy-pasted the project policy template, changed policy id for mine (created on NFT-MAKER Pro) and didn't use any special character in name.. could you please guide me? thank you in advance!

**Comment by veopixelado** [comment]
> Dear Contributor, please use the new JSON format in the Readme file on the home page.

@HRumson Do i need to create a new pull request? I don't know how to edit this...

**Comment by veopixelado** [comment]
Hey, can you please assist me with these process, I am lost with last
changes and I don't know if my last pull request for project "Ash and Tray
Season 1" is good or not. Also couldn't create a new one because the name
is in use so, I don't know what to do... Thank you for your time!

**Pull request closed without merging**
