### PR TITLE
Added BitMarks

### PR DESCRIPTION
**Pull request by BitMarks**
www.bitmarks.net
@cardanobitmarks

### CODE REVIEW

**Comment by Dean00K** [comment]
Hey, the file is invalid, can you take another look please. use this tool https://jsonlint.com/
Also, your policy ID never locks. What's the plans with this?

**Comment by BitMarks** [comment]
Hi there,

Sorry about that, I have updated the file and validated that it should be fine.

Didn’t lock the policy ID as I am looking to do other limited run releases based off of the same style. i.e. Christmas, easter, New Years themes.
I’m not sure when that will happen so I decided not to lock on that premise.

Let me know if you need anything else or there is a better way to do things.

Thanks,
Dan

**Comment by Dean00K** [comment]
It's just that people try to stay away from "never locked" policy IDs, because one could go back in and mint more and more diluting the NFTs available on the market (this may be something you need to manage as a creator if the questions get asked of you). But the website looks good and excited for your project. good luck!

**Comment by BitMarks** [comment]
Agh yep, that makes sense. 
Appreciate the insight, first project so I’m learning a fair bit along the way.

Thanks!

>

**Pull request merged**
