### PR TITLE
DrKimo added 7 NFTs

### PR DESCRIPTION
**Pull request by DrKimo1**
Alonzowelcome, Hydraascension, TheGambit05, Itallstartssomewhere, Theeyeofthebeholder, destructionoflondoneth, letitgrowandbecomeaADAstar

https://www.instagram.com/drkimo/
https://twitter.com/ImraanU

### CODE REVIEW

**Comment by DrKimo1** [comment]
Project- DrKimo

**Comment by TomStray** [comment]
Dear Contributor, as you have multiple projects, you will need to put it into the form of :

Multiple Projects under one name:
[
    {
        "project": "Example 1",
        "policies": [
            "Example1",
            "Example2"
        ]
    },
    {
        "project": "Example 2",
        "policies": [
            "Example 2"
        ]
    }
]

**Comment by DrKimo1** [comment]
I hope this is correct. 

Thanks

**Comment by DrKimo1** [comment]
done.

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs somewhere onto your twitter so that I can verify they are yours.

**Pull request closed without merging**
