### PR TITLE
Picasso'd-Woman

### PR DESCRIPTION
**Pull request by romeox7**
https://twitter.com/JediJerome00/status/1465386965411450888?s=20
https://cnft.io/token/6181435e3ff43a2e406e1b96

What else can I provide you for proof? This is my first time doing this.
Just an NFT I minted after creating it via generative art algorithm.

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, in order for your JSON file to be valid, please rename your request and code names so that there is no '-' or any similar characters in the title.

**Comment by romeox7** [comment]
Can you please update this, as I've fixed the issue with the title.
thanks

**Comment by romeox7** [comment]
> Dear Contributor, in order for your JSON file to be valid, please rename your request and code names so that there is no '-' or any similar characters in the title.

I've fixed the title as requested. Please advise further steps?

thanks
Jerome

**Review by romeox7 — COMMENTED** [review]
I've changed the name, removed the '-' as requested.
Any other steps?

**Pull request closed without merging**
