### PR TITLE
flame Collection

### PR DESCRIPTION
**Pull request by nftitalia**
https://twitter.com/flame_nft_it

https://cnft.io/token/61a3954fe8739c97c59771ee

### CODE REVIEW

**Comment by nftitalia** [comment]
> https://twitter.com/flame_nft_it
> 
> https://cnft.io/token/61a3954fe8739c97c59771ee

**Comment by nftitalia** [comment]
@nicolasayotte

**Comment by nftitalia** [comment]
@Padierfind

**Comment by nicolasayotte** [comment]
> @nicolasayotte How long does it take to get an answer??

Who are you??? I don't work for cnft.io!!!

Why are you bothering Patrick Tobler with this?

You know what, I usually help but you are so entitled I will leave you to fix your own stuff.

Good luck.

**Comment by nicolasayotte** [comment]
> @nicolasayotte How long does it take to get an answer??

Due to impoliteness and bothering people that don't even work for CNFT.io I should actually not even tell you that you have a trailing comma in your policies.

Patrick Tobler is a very busy man and doesn't work for CNFT.io either, please never tag us again.

**Comment by nftitalia** [comment]
> > @nicolasayotte How long does it take to get an answer??
> 
> Due to impoliteness and bothering people that don't even work for CNFT.io I should actually not even tell you that you have a trailing comma in your policies.
> 
> Patrick Tobler is a very busy man and doesn't work for CNFT.io either, please never tag us again.

I apologise, how should I be verified?

**Comment by nftitalia** [comment]
https://twitter.com/flame_nft_it/status/1466098942660202506?s=20

**Pull request closed without merging**
