### PR TITLE
Added Cyberpunks verification.

### PR DESCRIPTION
**Pull request by Habacef**

### CODE REVIEW

**Comment by Dean00K** [comment]
Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership by way of tweeting your pull request from your project’s twitter account and provide the link here as a comment. Alternatively provide project website URL which contains Policy IDs within. Thank you.

**Comment by Habacef** [comment]
https://discord.gg/7Dcmnt5T

Here in our discord the policy IDs are stated!

**Comment by Dean00K** [comment]
Cool, it's not really my job to go and join your discord server to figure out information that is requested to be provided at the time of verification submission. One of your policy IDs is unlocked. What's happening with that? Obviously I need to conduct adequate due diligence. cheers.

**Comment by Habacef** [comment]
Hey Dean,

I am Sorry, I did not know this isn’t your job..
.
Everything is organized through our discord, thus this is the only place where both policies are located. Also I was a bit confused because I already validated in April on your CNFT discord and thought this may be easy then on the website too... so sorry for causing trouble...

The open policy is intended. The golden and diamond punks get only minted when people achieve them... this was part of our first game idea... 

All the best, 
Leon

**Comment by Dean00K** [comment]
No worries, Hey I had to remove the tag "game" - it's too broad.. if anyone else had that word in their project / description, it would show up as "NOT A REAL CyberPunks"

**Pull request merged**
