### PR TITLE
Candles

### PR DESCRIPTION
**Pull request by NaonaoPresent**

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please remove the comma at the end of line 5.

**Comment by NaonaoPresent** [comment]
hello could you please finish the verification. Cheers

**Comment by MaxJewell** [comment]
Please may you provide a link to where we can find all policy ID's you are trying to merge. 
Thanks.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
