### PR TITLE
Updated Mosie-Marks policies (and sorted them)

### PR DESCRIPTION
**Pull request by the-Minister-0001**
Hi,

here's the pull request for my friend @ImMosie and his projects.
There's a ton of policies so I sorted them in order to keep future updates easier to track down and current ones easier to verify.

There's public proof from his twitter account in order to make sure that it really is his list of policies here:
https://twitter.com/MosieAlong/status/1463220038844964879

If there's something else you need please don't hesitate to let me know.

### CODE REVIEW

**Comment by the-Minister-0001** [comment]
The JSON is definitely valid but the previously non-compliant file name breaks the validation.
This last commit will make the project compliant with the requirement to not use dashes in the filename.

**Comment by MaxJewell** [comment]
f13e37d89aeb34339c70a49a1339f7dc253f61432ee11df4121cf1b9

**Comment by MaxJewell** [comment]
Please use the new JSON format in the Readme file on the home page.

**Comment by the-Minister-0001** [comment]
The JSON format is correct. Please see my above comment on why the test fails.

This affects more projects than only this one.

**Pull request closed without merging**
