### PR TITLE
added Project "Rotatoes"

### PR DESCRIPTION
**Pull request by Rotatoes**

### CODE REVIEW

**Comment by Dean00K** [comment]
Hey man, you need to remove the comma from the end of the policy ID line

**Comment by Dean00K** [comment]
Whats the plans for this project? the policy ID is always open?

**Comment by Rotatoes** [comment]
Hey :-) where do i need to click to edit it again ? 
Plans for this project is to add more Rotatoes with unsigns i own. The policy is always open
The original sale is here: https://easycnft.art/en/flash/72
Twitter is: https://twitter.com/RotatoesNFT

**Comment by Dean00K** [comment]
now line 2 needs a comma. :)
check this tool https://jsonlint.com/

**Comment by Rotatoes** [comment]
fixed 🙂

**Comment by Rotatoes** [comment]
Hey Dean, i made a new Rotatoes collection and added an new policy number. did i do everything correct? greetings --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 21.08.21, 15:25 schrieb Dean00K ***@***.***>:

   
  Whats the plans for this project? the policy ID is always open?

**Pull request merged**
