### PR TITLE
MonaLittleVampire

### PR DESCRIPTION
**Pull request by jrgongora**

### CODE REVIEW

**Comment by jrgongora** [comment]
I'm still working on the discord channel and twitter account.

**Review by jrgongora — COMMENTED** [review]
Twittter account is set: https://twitter.com/ADALittleMona

**Comment by MaxJewell** [comment]
Afternoon,
File MonaLittleVampire is not in projects directory!
Please make a new pull request with this change. Make sure to include the file name in the commit too.

**Comment by jrgongora** [comment]
Hello, fixed, thank you!

**Pull request closed without merging**
