### PR TITLE
Updating new policy ID

### PR DESCRIPTION
**Pull request by deveerei**
This policy ID is for season 2, launching soon. Policy ID uploaded on the website too: https://cadabears.com/

### CODE REVIEW

**Review by deveerei — COMMENTED** [review]
Updating JSON

**Comment by AnOnlineGuy** [comment]
We have made another change to GitHub that you should be aware of. 

I need you guys today to go through all the PRs and close them with this message. 

‘Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by deveerei** [comment]
Ah, I see. Everything moved after my submission? Got it, submitting a new
one. Thanks!

**Comment by deveerei** [comment]
New submission: https://github.com/Cardano-NFTs/policyIDs/pull/4003, thanks!

**Pull request closed without merging**
