### PR TITLE
Noir

### PR DESCRIPTION
**Pull request by Brittenbritten**
Twitter.com/britrndma
https://twitter.com/britrndma/status/1429053675264221193?s=21

https://pool.pm/addr1q92xjas94zd7ka9uwmz8x3nvxx7kpvsva6zyklgyg8u2rr2j3cp3mg2wwrf5ta9qmgvplk78wqcg46p48u37yhd2um6ssmk2e6

### CODE REVIEW

**Comment by Brittenbritten** [comment]
https://twitter.com/britrndma/status/1428627855370510336?s=21

https://pool.pm/addr1q92xjas94zd7ka9uwmz8x3nvxx7kpvsva6zyklgyg8u2rr2j3cp3mg2wwrf5ta9qmgvplk78wqcg46p48u37yhd2um6ssmk2e6

**Comment by Dean00K** [comment]
Hey - There are some issues with your file, it's invalid. Tool - https://jsonlint.com/
Also, can you delete that merge branch you did. not sure what happened there, but your first "added project Noir" file is the one i want to merge when that file is fixed up. cheers.

**Comment by Brittenbritten** [comment]
Well seems like I failed at deleting the merge branch and instead created a new one? I'm sorry, I'm horrible at this, I'll try to google my way through this. I think I did manage to fix the file "Create Noir".

**Comment by Brittenbritten** [comment]
I'll try from the start with a new pull request!

**Pull request closed without merging**
