### PR TITLE
Added Horrocubes

### PR DESCRIPTION
**Pull request by AngelCastilloB**
Proof with policy ID:
[Website](https://horrocubes.io/verify)
[Twitter](https://twitter.com/Horrocubes)
[Discord](https://discord.gg/UHQaCPjNDQ)

### CODE REVIEW

**Comment by AngelCastilloB** [comment]
Tweed proof https://twitter.com/Horrocubes/status/1458989505722011648

**Comment by AngelCastilloB** [comment]
BTW we have a big number of policies because we are a smart-contract project, all our NFTs are minted with Plutus scripts, we recently created a new script to minimize the number of policies, but we already had minted several with the original script. If you want to know the details I explain everything here: https://www.youtube.com/watch?v=vHraLcvECmQ and here is a link to the project git repositories: https://github.com/Horrocubes

**Comment by bogy196** [comment]
@CNFT-io , can this PR please be checked?

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
