### PR TITLE
AdD list (UPDATED, PLEASE CHECK!)

### PR DESCRIPTION
**Pull request by Serpant1**
Adding to policy registrar
https://adoodles.fun/ PolicyID on bottom
https://twitter.com/Adoodlesfun

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by Serpant1** [comment]
> Dear Contributor,
> 
> Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

Hello,
Please check the bottom of the website. Thanks!
https://adoodles.fun/

**Review by Serpant1 — COMMENTED** [review]
https://adoodles.fun/ PolicyID on bottom

**Comment by KaiNFT** [comment]
It says the domain has expired

**Comment by MaxJewell** [comment]
Due to inactivity on this pull request we will have to close this request. 
Feel free to open a new request when you have gathered everything you need to be verified.

**Pull request closed without merging**
