### PR TITLE
Added CARDANO CATZ

### PR DESCRIPTION
**Pull request by CNFT4Humanity**
https://twitter.com/ADAForHumanity

Thanks :)

### CODE REVIEW

**Comment by CNFT4Humanity** [comment]
Hi Dean, could you please transfer this exchange to the new person in charge of the verification?

It is not mentioned anywhere that the policy needs to be locked to be verified.
This said, I accept to use a locked policy in the future but I think that an exception should be made for the policy of the series 1.

Can we find a solution?
As said, we can delete the keys so that you are sure that we will not issue any additional tokens.

Thanks.

**Comment by Dean00K** [comment]
This exchange remains on github for anyone to pick it up (the comments remain there), i don't know who is going to be doing it in the future sorry. I don't know if they have anyone yet.
________________________________

**Comment by CNFT4Humanity** [comment]
Thank you. Waiting for the feedback of the new person in charge. I have also sent a DM to Stale on Twitter.

**Comment by CNFT4Humanity** [comment]
Hi there, any chance to have a feedback from the new person in charge?
Thanks.

**Pull request closed without merging**
