### PR TITLE
Create worldofhk

### PR DESCRIPTION
**Pull request by dawadog**

### CODE REVIEW

**Comment by dawadog** [comment]
{
    "project": "WorldOfHK",
    "policies": [
        "63344564d72aa4bd16bb6b6d4e96335567aaf099c6196a9d86f0b13a"
        
    ]
}

**Comment by dawadog** [comment]
https://twitter.com/wldofhkfirearms

**Comment by dawadog** [comment]
https://t.co/zh9BDQpppY?amp=1

**Comment by MaxJewell** [comment]
Policy in the commit is not on the twitter page you have provided.
Please try again and I will get back to you as soon as possible.

Many thanks

**Comment by dawadog** [comment]
Updated the policy id.

**Comment by dawadog** [comment]
Update

**Comment by MaxJewell** [comment]
The policy ID in the commit is still not on the twitter link you have provided.

**Comment by dawadog** [comment]
udpated twitter page with policy id 

https://twitter.com/wldofhkfirearms/status/1443618581581897731

**Comment by MaxJewell** [comment]
The policy ID you have provided does not match the policy ID in the commits.

**Comment by dawadog** [comment]
Hi.

I literally copy/pasted the commit from this (pull request) page and
posted/pinned to my Twitter page and provided a link on this pull request
to the pinned tweet. I’m not sure how it doesn’t match.

Am I missing something?

Thanks
Max

**Comment by dawadog** [comment]
Ok I see now.

**Pull request closed without merging**
