### PR TITLE
Pull request

### PR DESCRIPTION
**Pull request by auteio**

### CODE REVIEW

**Comment by auteio** [comment]
hi stale, 
: )

**Comment by auteio** [comment]
: )

**Comment by itsmestale** [comment]
Suite gallery format is strange and won't work.

**Comment by auteio** [comment]
i understand. it is a gallery in berlin. suitegallery.de
which is surely no project. there is actually another 
gallery who want to sell. under which name can they do so?
and can you please confirm the HolyMountain project for me?

**Pull request merged**
