### PR TITLE
ARARE Gallery

### PR DESCRIPTION
**Pull request by Doenyas**

### CODE REVIEW

**Comment by Doenyas** [comment]
https://twitter.com/AdaRarePool/status/1458161244981051400

**Comment by TomStray** [comment]
Dear Contributor, please provide links to your twitter or website/CNFT.io/Pool with your policy ID(s) on there for your policy IDs on lines 5, 11 and 12.

**Comment by Doenyas** [comment]
line 13 : https://twitter.com/AdaRarePool/status/1456352853103046667
line 12 : https://twitter.com/AdaRarePool/status/1451605157729357827
line 11 : https://twitter.com/AdaRarePool/status/1450962392221827075
line 5 : https://twitter.com/AdaRarePool/status/1435311214578454528

**Comment by Doenyas** [comment]
> Dear Contributor, please provide links to your twitter or website/CNFT.io/Pool with your policy ID(s) on there for your policy IDs on lines 5, 11 and 12.

is that ok?

**Pull request merged**
