### PR TITLE
Add SkulloopistFirstDrop

### PR DESCRIPTION
**Pull request by gabrielgaldinomagalhaes**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by gabrielgaldinomagalhaes** [comment]
Do you have any example of twitter account with the policies on it? Or a
website with the policies on it?

I can do it for sure. I just want to see a reference to do it in the same
way.

**Comment by MaxJewell** [comment]
Just tweeting the policy ID's out or in the bio is perfect

**Comment by gabrielgaldinomagalhaes** [comment]
> Just tweeting the policy ID's out or in the bio is perfect

Done!!!

I've twiteed all of the 8 policies on my twiteer. This is the link to my profile:
https://mobile.twitter.com/Gabriel98876827

Is it right ?

**Comment by gabrielgaldinomagalhaes** [comment]
Done!!!

I've Twitted all the 8 policies on my Twitter account.

The link is this:
https://mobile.twitter.com/Gabriel98876827


Is it right ??

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by gabrielgaldinomagalhaes** [comment]
How do I do it ?

**Pull request closed without merging**
