### PR TITLE
Added CryptoDragons

### PR DESCRIPTION
**Pull request by minaryumae**

### CODE REVIEW

**Comment by minaryumae** [comment]
https://twitter.com/Crypto_Dragons/status/1430212996341637123

**Comment by Dean00K** [comment]
Heya, I need you to remove the tags "dragon" and "dragons". These are too broad and widely used, if another project wanted to use the name dragon in their title or description, it would show up as "NOT A REAL CryptoDragons"
Also, moving forward, I suggest minting all your dragons under one single policy ID.
Cheers.

**Comment by minaryumae** [comment]
Added the 4th policy id and will mainly use it for future mint

**Comment by crypto-dragons** [comment]
@itsmestale Hi! Could you please approve our request? We have 1800+ CryptoDragons listed on CNFT. Thank you so much for your help!!

**Pull request merged**
