### PR TITLE
Add Project Pigy Genetics

### PR DESCRIPTION
**Pull request by TheLegendaryRainbowWarrior**
Add Project Pigy Genetics

### CODE REVIEW

**Comment by Dean00K** [comment]
Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership by way of tweeting your pull request from your project’s twitter account and provide the link here as a comment. Alternatively provide project website URL which contains Policy IDs within. Thank you.

**Comment by TheLegendaryRainbowWarrior** [comment]
https://twitter.com/pigytoken/status/1428730660827631620

**Comment by Dean00K** [comment]
I think your policy ID might be incorrect?

**Comment by TheLegendaryRainbowWarrior** [comment]
> I think your policy ID might be incorrect?

Yes sorry it was my mistake. i change the policy ID to the right ID.

**Comment by Dean00K** [comment]
yep cool, that policy ID shows up now. It sounds like this is a utility token to be traded on DEXs, not an NFT. Can you confirm that? What are we looking at here? a utility/governance token being certified on a CNFT marketplace? That's not what we are doing.

**Comment by TheLegendaryRainbowWarrior** [comment]
> yep cool, that policy ID shows up now. It sounds like this is a utility token to be traded on DEXs, not an NFT. Can you confirm that? What are we looking at here? a utility/governance token being certified on a CNFT marketplace? That's not what we are doing.

So Pigy Token itself is a utility/governance token therefore not a NFT.

The PIG images are randomly generated by a minting process (https://genetics.pigytoken.com) but even there is not the uniqueness it needs for a NFT.

We also explain this on our website:

"The pig-image tokens are not NFTs. In particular (and by design), when blending tokens, there is some chance to create an “identical twin” of a previous pig-image token."

We just thought if there is the possibility to sell our pigs pictures at cnft then at least the right project should be behind it. Maybe you build a rule that such tokens may not be traded?

https://cnft.io/marketplace.php?search=PIG

So Pigy Token itself is a token which can also be traded on exchanges. The Pig Images are more of a feasibility study or just a fun game on the cardano blockchain.

So we can understand if you do not accept the pull request :-)

**Comment by Dean00K** [comment]
Ok, sounds good, I have another similar request at the moment that I've forwarded to the team who are still currently trying to figure out what the policy is on fungible tokens with IPFS etc etc.. I'll wait to hear back from them, likewise if you haven't heard from me for a 5ish days/a week or so, maybe comment again? Cheers.

**Pull request closed without merging**
