### PR TITLE
Digital Syndicate Policy Keys

### PR DESCRIPTION
**Pull request by huths0lo**
Digital Syndicate is the partnership between Huth S0lo and Edwardo Diaz.  Please contact either of us for proof of provenance.

### CODE REVIEW

**Comment by Dean00K** [comment]
Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership. Either by way of tweeting your pull request from your project’s twitter account and providing a link here, providing a link to the project's website URL which contains Policy IDs within, or providing a pool.pm link to the wallet containing your NFTs so we can verify. Thank you.

**Comment by Dean00K** [comment]
Also, your file is just 2 lines. If you need a reference point, there are examples in the readme.md file mentioned in the above comment.

**Comment by Dean00K** [comment]
remove comma from line 4

**Comment by Dean00K** [comment]
Can i get some more information please - like a twitter account or website? Those policy IDs aren't much to go off.

**Comment by huths0lo** [comment]
Had to change the two policies because of 777 standard requirements.  The policy ID's are on their respective websites, in the footer of each page:

kmfdm.io
lordsofacid.io

**Review by nicolasayotte — APPROVED** [review]
Verified. Thanks

**Pull request merged**
