### PR TITLE
Create CARDANO BULL & BIRDS

### PR DESCRIPTION
**Pull request by fisch192**

### CODE REVIEW

**Comment by fisch192** [comment]
Official Project website with Policy 
https://southtyrolpool.it/it/southtyrol-cardano-pool-it/cardanobullbirds/

**Comment by Dean00K** [comment]
Hey - I need you to take the word "Bull" out of your tag please.

**Comment by fisch192** [comment]
ok done !

**Comment by Dean00K** [comment]
Noice!

**Comment by Dean00K** [comment]
It was too broad dude - anyone else with the name "Bull" in their NFT would have "NOT A REAL Cardano Bull & Birds" auto populate next to their NFTs

**Pull request merged**
