### PR TITLE
The dummyboyz NFT

### PR DESCRIPTION
**Pull request by Hiroto168**

### CODE REVIEW

**Comment by MaxJewell** [comment]
This is a good start.
What I will need you to do is to give me a link to a twitter/webpage with the Policy ID's on them to verify your identity.

Many thanks.

**Comment by Hiroto168** [comment]
@MaxJewell Thank you so much for your time .

This is my Twitter: https://twitter.com/hiroto_hekima

Project name: The dummyboyz

and Policy ID's :  b5c958709161e37c115e057997967302a7108940be60c6596633467c


Big thank 😀

**Comment by MaxJewell** [comment]
I will need the Policy ID on the twitter page somewhere to confirm your identity.

Thanks.

**Comment by Hiroto168** [comment]
@MaxJewell   Thank you for your time.

Twitter: https://twitter.com/hiroto_hekima

Please check the Policy ID on my Twitter bio.

Big thank.

**Pull request merged**
