### PR TITLE
Added TGWP Policy ID

### PR DESCRIPTION
**Pull request by arxheryyy**
I used the template for multiple projects under one name because there will be more in the future.

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

**Comment by arxheryyy** [comment]
twitter.com/tgwp_cnft , website is yet to be done but will be launched soon

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your twitter or discord.

**Comment by arxheryyy** [comment]
some changes are being discussed about the project. 
thank you for your help TomStray

**Pull request closed without merging**
