### PR TITLE
Added two projects by @Elamite_Art: NFTea and CARDANO ICONS

### PR DESCRIPTION
**Pull request by Elamite-Art**

### CODE REVIEW

**Comment by Dean00K** [comment]
Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership by way of tweeting your pull request from your project’s twitter account and provide the link here as a comment. Alternatively provide project website URL which contains Policy IDs within. Thank you.

**Comment by Elamite-Art** [comment]
> Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership by way of tweeting your pull request from your project’s twitter account and provide the link here as a comment. Alternatively provide project website URL which contains Policy IDs within. Thank you.

Done, thanks @Dean00K !

**Comment by Dean00K** [comment]
Can you paste a link here for me pls.

**Comment by Elamite-Art** [comment]
> Can you paste a link here for me pls.

Hi @Dean00K

Please find the linked tweet below, have a great day!

https://twitter.com/Elamite_Art/status/1426541849368477706

-Elamite_Art

**Pull request merged**
