### PR TITLE
Ada Sharks!

### PR DESCRIPTION
**Pull request by Huryashin**
https://adasharkscnft.com/
https://twitter.com/Ada_SharksCnft

### CODE REVIEW

**Comment by TomStray** [comment]
The policy ID’s that are on the commit are different to your website and twitter. Please amend this.

**Comment by Huryashin** [comment]
Should be good now. I posted the policy ID on Twitter and on our site.

**Comment by Huryashin** [comment]
Sorry, we are new to this. We posted the policy ID to the Twitter im not sure if that amended the problem or not.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Huryashin** [comment]
How do we know when we are good?

**Comment by Huryashin** [comment]
Are we verified? Tried checking and still not showing yellow check mark. Is there something else we need to fix

**Comment by Huryashin** [comment]
Are we verified yet? Not sure how to check if we are

**Comment by Huryashin** [comment]
Could you make sure we are verified please😊😊☺️

**Pull request merged**
