### PR TITLE
$SAMMY Launch Collection

### PR DESCRIPTION
**Pull request by SAMMYToken**
https://ada-sammy.io

@Samoyed_ADA Twitter

https://twitter.com/Samoyed_ADA/status/1478775393326936067

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

The Policy ID listed on your website is not the same ID listed in your JSON file, please make the necessary adjustments.

**Comment by SAMMYToken** [comment]
@KaiNFT  Updated.  NFT Policy now on website.

**Review by SAMMYToken — COMMENTED** [review]
Should be complete now.

**Review by SAMMYToken — COMMENTED** [review]
@KaiNFT fixed json

**Pull request merged**
