### PR TITLE
Shades

### PR DESCRIPTION
**Pull request by unparalleledvisuals**
www.instagram.com/uparalleled.visuals

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

The link you sent does not work.

**Comment by unparalleledvisuals** [comment]
Sorry I am new to all this. I copied the policy ID from the listing on CNFT. IO. Is that not correct?

**Comment by unparalleledvisuals** [comment]
https://twitter.com/unparalleledpnw
https://cnft.io/token/61d762c7cb6c47a202fc9e2c
https://twitter.com/unparalleledpnw/status/1479338608746131457?s=20

**Comment by unparalleledvisuals** [comment]
https://twitter.com/unparalleledpnw/status/1479897241099780096?s=20

**Pull request merged**
