### PR TITLE
Updated project with new policyID

### PR DESCRIPTION
**Pull request by NonFungibleBUBZ**
Added policy ID for Wonder ADA

### CODE REVIEW

**Comment by NonFungibleBUBZ** [comment]
Can we also get the old policy ID file "Non-Fungible POP" deleted from the repo, please? It is causing a conflict.
We've deleted the fork and tried to merge in order to delete the file, but no luck.
Kindly assist.
Thanks in advance.

**Comment by TomStray** [comment]
Dear Contributor, please give me the pull request number of the file you want deleted and i'll see what I can do.

Many Thanks,

**Comment by NonFungibleBUBZ** [comment]
Hello, 

Thanks for getting back to me. 

The pull request number is: **#239**
The filename is: **Non-Fungible POP**
And it was handled by: **Dean00k**

I've also made another commit to the new file 'Non-Fungible BUBZ', so can you help merge with the main again, please.

Thanks in advance.

TM

**Comment by NonFungibleBUBZ** [comment]
Any update on this, please? Project launching and its still not verified.

**Comment by KaiNFT** [comment]
Dear Contributor,

Apologies for the late response however there is conflicting files on your pull request, meaning that your file is a duplicate to one that has already been published on the branch.

**Comment by NonFungibleBUBZ** [comment]
Hello, Thanks for the feedback. 

Yes. We already created the file and successfully merged it with the main branch. We've added some new policy ID to the document and are trying to add it to the old project file.

Is there any other way to get that done, because its just more Policy IDs being added to the same project.

Kindly advise.

**Comment by KaiNFT** [comment]
Duplicate Post

**Pull request closed without merging**
