### PR TITLE
Create BitsServe

### PR DESCRIPTION
**Pull request by yopkub**
Add PolicyIDs to BitsServe for verify

Twitter : https://twitter.com/BitsServe

### CODE REVIEW

**Comment by yopkub** [comment]
@Dean00K 
Done, Right ?

**Comment by Dean00K** [comment]
Yep, looks good. Thanks - Still waiting to hear back from the website owners - different sides of the world :)

**Comment by Dean00K** [comment]
got approval. Woohoo!

**Comment by yopkub** [comment]
Thank you very much for your support. bro

**Pull request merged**
