### PR TITLE
Created Atmospheres-IDs

### PR DESCRIPTION
**Pull request by Jez-Atmospheres**
Atmospheres Underwater are the first NFT's released by photographer Jez Tryner.
https://atmospheres.tv/
https://twitter.com/AtmospheresArt/status/1437597654725234695
https://pool.pm/stake1u8uvaz3snxahv0ucydk9zzductkm9zuvkywq78rv0naktvqddmh96
https://www.instagram.com/AtmospheresArt

### CODE REVIEW

**Comment by Jez-Atmospheres** [comment]
Any idea how long this will take and is this how to get the yellow tick next to your NFTs ?

**Comment by Jez-Atmospheres** [comment]
https://pool.pm/stake1u8uvaz3snxahv0ucydk9zzductkm9zuvkywq78rv0naktvqddmh96

**Comment by Jez-Atmospheres** [comment]
https://www.instagram.com/jez_tryner_photography/

**Comment by Jez-Atmospheres** [comment]
https://twitter.com/JezTryner/status/1435425179639844864

**Comment by MaxJewell** [comment]
This is a great start.
I will need to ask for you to indent all of the Policy ID's twice so the code is able to compile. 
Do to this you need to use the TAB key.
Keep me updated when you have done so.

Thanks.

**Comment by Jez-Atmospheres** [comment]
I am sorry, I don't know how to or what this means.. 
"I will need to ask for you to indent all of the Policy ID's twice so the code is able to compile."
What is this ?
I am new to GitHub, can you help ?

**Review by Jez-Atmospheres — COMMENTED** [review]
I think I figured it out @MaxJewell ...is this correct ?

**Comment by Jez-Atmospheres** [comment]
@MaxJewell does this mean my NFTs are now verified?
Thank you!￼

**Comment by Jez-Atmospheres** [comment]
@MaxJewell - why are the tags not included for searching ?...is it not like a keyword search ?
I cannot even search my project name and find it ?

**Review by Jez-Atmospheres — COMMENTED** [review]
@MaxJewell - why are the tags from my file not included on your site for searching ?...is it not like a keyword search ?
I cannot even use the search to find my project name
Screenshot 2021-10-01 at 10 24 39
Screenshot 2021-10-01 at 10 26 36
 
Screenshot 2021-10-01 at 10 27 32
?

**Comment by Jez-Atmospheres** [comment]
Hi, 
how can someone else add an NFT using my project name ?
There is one NFT that is nothing to do with my project but is using my name and is also verified somehow, how do I stop this ?
It is making my project look bad
Thanks in advance

Screenshot 2021-11-09 at 10 33 01


Screenshot 2021-11-09 at 10 39 24

**Pull request merged**
