### PR TITLE
TwoFacesMS

### PR DESCRIPTION
**Pull request by MiguelistaNFT**
https://twitter.com/MiguelistaNFT/status/1503042203823874059

### CODE REVIEW

**Comment by MiguelistaNFT** [comment]
[
  {
    "project": "TwoFaces",
    "policies": [
      "3bd6a0416447e6982e89b434426985d9eb793814274c18201691ec86",
    ]
  }
]

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by MiguelistaNFT** [comment]
[{

            "project": "TwoFaces",

            "policies": [

                           "3bd6a0416447e6982e89b434426985d9eb793814274c18201691ec86"

            ]
}]

**Comment by MiguelistaNFT** [comment]
Thanks for the info!,

I already checked the json file and put the new one thank you.



A quarta, 16/03/2022, 10:43, KaiNFT ***@***.***> escreveu:

**Comment by KaiNFT** [comment]
Dear Contributor,

The error code is; SyntaxErrorUnexpected token ] in JSON at position 121

**Comment by KaiNFT** [comment]
Closed due to inactivity

**Pull request closed without merging**
