### PR TITLE
Create BLOCKZERO

### PR DESCRIPTION
**Pull request by idoncarewatchuthink**
Please verify project in the marketplace

### CODE REVIEW

**Comment by KaiNFT** [comment]
Hi Contributor,

Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

**Comment by idoncarewatchuthink** [comment]
https://twitter.com/generalxtitus/status/1461145964291366912?s=21

**Comment by idoncarewatchuthink** [comment]
> Hi Contributor,
> 
> Please can you provide evidence of your Policy ID/s via website/social media so I can merge the pull request.

https://twitter.com/generalxtitus/status/1461145964291366912?s=21

**Comment by idoncarewatchuthink** [comment]
Hi any updates on this?

**Pull request closed without merging**
