### PR TITLE
Update and rename DeepVision by VisionAI to DeepVision

### PR DESCRIPTION
**Pull request by SamGCURIOM**
Rebranding from DeepVision by VisionAI to DeepVision

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by SamGCURIOM** [comment]
Oh for sure, my bad.
https://twitter.com/gcuriom
https://discord.gg/hjQ3fUs9jG

**Comment by MaxJewell** [comment]
If you could add the policy ID in your commit, into your discord I can merge you.

**Comment by SamGCURIOM** [comment]
If you go in the policyid channel they're there.

**Pull request merged**
