### PR TITLE
Added TC Cardano NFT Project

### PR DESCRIPTION
**Pull request by ThianchaiNFT**
These are contains 2 projects. The first one is TCCardanoNFT with 2 policies. And the second one is TCCardanoNFT2 which have 5 policies.

### CODE REVIEW

**Comment by ThianchaiNFT** [comment]
Here is my tweet.
https://twitter.com/thianchaiqpf/status/1457763232903417858?s=21

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs to your twitter so that I can verify them.

**Comment by ThianchaiNFT** [comment]
Policy ID on my twitter (1/2)
https://twitter.com/thianchaiqpf/status/1458101493790281740?s=21

**Comment by ThianchaiNFT** [comment]
Policy ID on my twitter (2/2)
https://twitter.com/thianchaiqpf/status/1458101950860468247?s=21

**Comment by ThianchaiNFT** [comment]
> Dear Contributor, please add your policy IDs to your twitter so that I can verify them.

Am I do it right?

**Comment by ThianchaiNFT** [comment]
All my project policy ID on twitter.

https://twitter.com/thianchaiqpf/status/1458104091771486209?s=21

**Comment by ThianchaiNFT** [comment]
Thank you so much.

**Pull request merged**
