### PR TITLE
Hallucinogenics

### PR DESCRIPTION
**Pull request by rafek47**
Project made by PSYA - Psychedelic Pool 
https://twitter.com/psyadapool

### CODE REVIEW

**Comment by rafek47** [comment]
[https://twitter.com/psyadapool/status/1458262688157642761](url)

**Comment by KaiNFT** [comment]
Dear Contributor,

The link you provided as evidence is no longer working, can you please make the necessary adjustments to ensure I can merge the pull request.

**Comment by rafek47** [comment]
Hi, please try again
https://twitter.com/psyadapool/status/1458262688157642761

**Comment by rafek47** [comment]
> Dear Contributor,
> 
> The link you provided as evidence is no longer working, can you please make the necessary adjustments to ensure I can merge the pull request.

Hi, kindly ask for merging this one, please. The correct link was already provided. The recent one was incorrectly pointing to Github. 

Thank you.

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
