### PR TITLE
Create Cardano Harry Potter

### PR DESCRIPTION
**Pull request by LunaLove1576**
{
    "project": "Cardano Harry Potter",
    "policies": [
         "681edc5fb5ed9348eaef6f697f3ff6c82e5349b9992080eeb8918731",
         "f6e1dfa4ec7c5008e84c8ecfb0db2bc2dee68ffbe87fb19c21870a21",
         "aad7439babd9fc548dd97291fe1fd9c386dfa7b02f50f515628ce86c",
         "f1f08a2da7824f6008fd30b0d3744cd9226004062a546895889c4413",
          "5a042b696adeab096a85b59bcdd45c21778a5b2e7baf635f484c1bc2",
          "e7a2ab172266fab89337b5c7a84832fc1ebaf09125781a8c1d6163ba",
          "f4dbce5b49eaf1841aaf274aac47262d393263f32673bb2693d1126a",
          "78f6f85a94e232af13bad7a88f7fb6b9860db89992b72b07ece93152",
          "1009414ac48e083e344c69a961e7b962bf79589afa8f8a952c3d8ea1",
          "681edc5fb5ed9348eaef6f697f3ff6c82e5349b9992080eeb8918731",
          "6a6eb93e830c4d777db685fc0701b11d85af1efe036f21d9d54aa70c",
          "a73f30825f29106fd9db1e9f79a239c7cb83c1fd8184d2b00b152ad4",
          "c29a86ad240ee0154602ed5921e1a0908569c7d57b9f39bb367f438b", 
          "0be036383764defecbeb3b940b06ac7b5c90cb519acb5fd7f9e7233f",
          "e5aec75a3cbec1dda32d00fe3aa6959845b7b18b8ecffbabcaffa031",
          "f8a01694ab04c046c6a6d8675770f1560ffdc4cdd68ec184df80a763",
          "cddee886c6b7c24f37378243767f4a8b2e22060e9e267b93bb440b34";
          "c459faf28abd0b82ca53cb1a510ccb91a80dd76160c3bdd7fb29430d",
          "db721df25ad449ef5fb97b34c1b8dad3e8da6fbea8f55d5efc97dfdc",         
          "52f638d034f770eee2941393658179204c55a33bdf2fdfdadb3e7ca2"
    ]
}

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy IDs on there.

**Comment by LunaLove1576** [comment]
https://twitter.com/ADAHarryPotter
https://www.harrypottercardano.com/

**Comment by LunaLove1576** [comment]
https://twitter.com/ADAHarryPotter
https://www.harrypottercardano.com/

**Comment by LunaLove1576** [comment]
Thank you!
Does this mean we get the check mark now?
Officially verified?

**Comment by TomStray** [comment]
Yes, they are verified :)

**Comment by LunaLove1576** [comment]
Yay! We are soooo happy!
Going forward for the next ones. Do I just do the same thing and they will
automatically be verified?

**Comment by LunaLove1576** [comment]
Also, most of our nfts are verified except some of our first ones.
Should I open another pull and put their policy numbers back in?

**Comment by LunaLove1576** [comment]
Hi, I hope you are well.
I added all policy Ids for our remaining nfts.
Do you have any estimated time of when they will be verified?
Or maybe I didn't do it correctly?

Thank you (:

**Comment by TomStray** [comment]
Dear Contributor, the time it takes for your policy IDs to be verified will vary based on the number of your request. We are going through the oldest ones first so if your number is in or around the 2000 mark, this will take longer to be verified. We are working through them but there are a lot of requests to go through.

Please bare with us, hope this helps.

**Comment by LunaLove1576** [comment]
Hi,
Thank you so much for your response. I know you are very busy and we are
waiting patiently but we have been waiting for almost a month now. I just
wanted to check in and make sure I am doing things correctly. Any help or
advice would be greatly appreciated.

https://github.com/Cardano-NFTs/policyIDs/compare/main...LunaLove1576:patch-2

https://www.harrypottercardano.com/
https://twitter.com/ADAHarryPotter

Thank you so much

**Pull request merged**
