### PR TITLE
Update CryptoFruits

### PR DESCRIPTION
**Pull request by JHurles**
Policy Numbers Edited as there were errors, I hadn't entered entire policy number

### CODE REVIEW

**Comment by Dean00K** [comment]
yeah it's fine, but these are fungible tokens though, you do realise?

**Comment by JHurles** [comment]
As in the policy’s are not locked?

**Comment by Dean00K** [comment]
No, the policies have a locking date, so they are not locked at the moment. But what you're issuing is not an NFT. Non-Fungible Token vs. Fungible Token.
an NFT is unique, there is only one. Fungible Tokens are a mass produced token - for example, your token here - https://pool.pm/5a72a4cbbf3432c48bec2901493791ce64a6f921d7dcc66e3b97dbe4.CryptoFruitEggplantPOPSilver under quantity it has 97. All NFTs are a quantity of 1.

**Comment by Dean00K** [comment]
there is no unique metadata... they are just 97 photocopies of something... but that something doesn't exist.. because this is Fungible.

**Comment by JHurles** [comment]
The intent was to always have multiples of certain tokens, but limit the number that would exist, eg, CryptoFruitBananaSilver has 97 copies, all equal in initial value but never more than that made. Only the 1 off fruits are complete unique, eg the ADABoy collab. Is this an issue?

**Comment by Dean00K** [comment]
yeah - 100% it's an issue.. not for me to verify you, but as an avid NFT collector, no one will want your work.. you've essentially created a native token on cardano with a GIF and then gave it a quantity of 97 vs. creating unique individual NFTs with their own asset numbers and metadata. Here is an example - this is a link to my wallet https://pool.pm/addr1q8626yy2as2mjzt7q7lcnz22fqd4mwufp3t9wr58mw8n0t624uwgdkrkf3nxlnr2sk3aphyr5v4zc9yzpesv2hwaff5qtnz7pe/831cf7ca you can see 5 NFTs there at that link. each an individual NFT with its own metadata and asset number, but same policy ID. They all have the number "1" underneath the image because they are all a 1 of 1 individual NFT. If this was your asset, it would only have 1 single Fungible Token with the number "97" underneath it. All exact copies of each other. Hope that makes sense.. for collectors this is a big deal.

**Comment by JHurles** [comment]
Hi, I have re-minted everything, individually so now they will all be true NFTs. I will update policy numbers later. Thanks for all your help so far.

**Pull request merged**
