### PR TITLE
Create Covidabsurds

### PR DESCRIPTION
**Pull request by podajmelon**
I don't have twitter account.

### CODE REVIEW

**Comment by MaxJewell** [comment]
Could we have a link to a twitter/website/CNFT with the Policy ID's on them.

Thanks.

**Comment by podajmelon** [comment]
I'm not sure if I understand your reqest.
Is https://podajmelon.github.io/pools/policyids.txt enough? or what else should I do?

**Comment by MaxJewell** [comment]
Have you got any form of social media/presence for us to verify that these NFT Policy ID's are you.

**Comment by podajmelon** [comment]
I don't have any social media. I also don't think having social media with policy is is a proof, that this is me. I can create any social media I want adding this policy id to it. It proofs nothing. I just made 1 nft, that's it, I don't want to create social media for 1 simple nft.

**Comment by MaxJewell** [comment]
We request a social media to proof that you are an active member in the NFT community. With out this is we cannot come to a decision if you are stealing someone else's work.

Hope this makes sense.

**Pull request closed without merging**
