### PR TITLE
Chimpion Club

### PR DESCRIPTION
**Pull request by chimpionclubcnft**
{
    "project": "Chimpion Club",
    "tags": [
        "Chimpion"
    ],
    "policies": [
        "5d880807f558fc441a05024765120e769456ca79c828eba9ce7c5fbf"
          ]
}

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by chimpionclubcnft** [comment]
hey Kai,

We have updated on the website, instagram, Discord as well as twitter,
please help us check!

Appreciate the support.

**Comment by KaiNFT** [comment]
Dear Contributor,

Your file name has forbidden characters "(" ")", please make the necessary adjustments in order for me to merge the pull request.

**Comment by chimpionclubcnft** [comment]
hey Kai can you help re run 1 more time? we'll be launching in no time so
that would be very helpful

Thanks

**Pull request closed without merging**
