### PR TITLE
The Sleepy IceCream

### PR DESCRIPTION
**Pull request by sleepyicecream**
https://www.instagram.com/thesleepyicecream

https://twitter.com/sleepyicecreamz

### CODE REVIEW

**Comment by MaxJewell** [comment]
The Policy ID will need to be on the tweets too. 
Thanks

**Comment by sleepyicecream** [comment]
So i need to tweet my policy ids ? Thank you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KaiNFT** [comment]
Yes

**Comment by sleepyicecream** [comment]
Done :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by itsmestale** [comment]
Removed verification, your policyId is not your own, you have provided the planetpalz policyId.

**Pull request merged**
