### PR TITLE
Create cryp7ocr3ations

### PR DESCRIPTION
**Pull request by cryp7ocr3ations**
https://www.cryp7ocr3ations.com/policy-ids
https://www.cryp7ocr3ations.com/collections

### CODE REVIEW

**Comment by Dean00K** [comment]
Heya - your file is invalid. Use this tool if you want to locate errors https://jsonlint.com/

**Comment by cryp7ocr3ations** [comment]
> Heya - your file is invalid. Use this tool if you want to locate errors https://jsonlint.com/

Ok I think I fixed it very sorry about that. It says there is duplicate key "project" still though is that ok? I'm guessing thats because I added the collaboration project to the file? Trying to figure out how to update the file now lol...

**Comment by Dean00K** [comment]
wow, i dont know what that means either

**Comment by Dean00K** [comment]
Fixed it - update it for me - cheers

[{
		"project": "cryp7ocr3ations",
		"tags": [
			"cryp7ocr3ations",
			"On Planet Cardano",
			"ADA Rising",
			"Cardano Cowgirl",
			"Ring of Fire",
			"Smokin",
			"Crypto Queen 01",
			"Smell The Flowers",
			"Southwestern Storm 01",
			"The Wanderer",
			"Stormy Skies",
			"Cosmic Toker",
			"House of Whatever Nicki Minaj",
			"Western Diamondback 01",
			"Western Diamondback 02",
			"Share Love",
			"Lookin At You",
			"Just for Laughs",
			"The Firestarter 01",
			"The Firestarter 02",
			"Enchantress 01",
			"Enchantress 02",
			"No Escape",
			"Kryptonite",
			"The Road There",
			"Cloaked Beauty",
			"Hidden Life",
			"Into the Blue 4k",
			"Beautiful Storm",
			"Desert Night",
			"Snake Eyes",
			"Sonoran Life",
			"Wild Horses 4k",
			"Southwestern Wildlife Collection",
			"Shelter in the Desert",
			"Desert Dreamland",
			"Firedance 01",
			"Saguaro Bloom",
			"Of Myth and Mystery",
			"The Bump in the Night",
			"Land of the Lost",
			"The Road There 02",
			"Into the Unknown",
			"Saguaro Garden",
			"The Morning View",
			"Cabin in the Woods",
			"Enchanted Beauty",
			"Desert Moonrise",
			"The Awakening",
			"Happiness Cube",
			"Cryp7o Booty Koin",
			"Cryp7o Booty Koin 2.0",
			"Beautiful Trip",
			"Beach Vibes",
			"Trip Time Skull",
			"Witching Hour",
			"Celestial Beauty",
			"The Wall",
			"Oh Hey!"
		],

		"policies": [
			"8ac4bc9f6017ebc42f4578b9737fd2e09bede9f5979b56aeb6c30ab7",
			"1fc3a6e2146ba4007e8b51756dffbd8e941886f0f4cf1ecc3b694563",
			"d1f94d8d9b80055a3d880906c3b9731b41265e79bb46898267752698",
			"1dc5ddece74dc9e6ac06cfbfe6033c6e0eed7e2c936cdb4fde137fa9",
			"6b7de66147ac9985016423e254fa8879f67af660feee7d648980bffb",
			"ebd626943344ade9a67c28c5834fa6fe600f132ee2cd238c44fd98c9",
			"3d3d3c7f94071086a2e079011f1e741b601f16c859a47bef5ee79055",
			"31fd03a0eb5fc59f1bebaea224ab573da72b926e4dbc1480d581bd74",
			"3e230e067bcf10d332886a57f92b280521d4fa5dd87de22145799b01",
			"df55d89912d09158fc28927a7bd864c8fa25a616f971a80a6975f4a6",
			"d4ceae0ecbe86de82a39658e8eee603026d111313afa3b7223222403",
			"9dabcee67e53b37b29a582efb83d8f8fe6f64f83b87c1a9311b6172d",
			"8223dc1da366da0bda214e557d6ea9d2066ea5557f9ffa2d2691b106",
			"a2f17dbb7ec0e97df9360c3c783ae49826ab18d36dded16d08a087d9",
			"8187cb8ea8d4be7505c7a6cb1144f02d0d0724a5179fcc47c674a4f4",
			"b375e5d64936ece167d1c400465f665993ccd9d01cf7937cbc0cfb5c",
			"eac287b700c9d043f7629f114a401a1b905af85809ffdf8b2dc5ceb8",
			"edbc364f180a87486a782aa9d80d9a58a7c5978586244526f901365d",
			"aeb4e30a40378701fe605072239a5bcda8635b245214e4db2ed2da61",
			"79fbca4616b6ab3a1ce78c48b58f65e4b608460929cc9de2f9731283",
			"5315e250e240e37dca5e278fe766e9db0047bde7f816efccd9e17f69",
			"570759bebc0e6b305484819d18cd1695c70d69bc1a0e7be5c9e8d496",
			"b9a6a6ce51c6a70aec7686d77073385d6e7862e31646bb6d59d06c28",
			"e18f212ab024f19b32507074c08d5082f6ac8f261903c7cb143314bf",
			"500eb610ba63cc259c494239e84e43d1a9427937a00ab08b28fb7733",
			"971d31e2560e266e4a3de0d4c56587d18bea58aa7a1f5d6263b276a1",
			"d12eca789bdc9a9901e7d10c116527e27831e5b262cfa50e6111667f",
			"9dad2b86b6fdc0e7cb3f84579256a2b84e37c47b962259ce8ae574af",
			"a4574bcfb3210e9d0a36aa5a53de06c22b9b28cbea20034d89992941",
			"7e875eec5c0d4785aa2be7267baa8ee5a85ddef5782fbf0c1e995d27"
		]
	},
	{
		"project": "VanityTrophiesxcryp7ocr3ations",
		"tags": [
			"Vanity Trophies x cryp7ocr3ations"
		],

		"policies": [
			"5edd05fb06c1fa3f0c9df501983f449019b4b9cfc494248ed89d7e26"
		]

	}
]

**Comment by cryp7ocr3ations** [comment]
> Fixed it - update it for me - cheers
> 
> [{
> "project": "cryp7ocr3ations",
> "tags": [
> "cryp7ocr3ations",
> "On Planet Cardano",
> "ADA Rising",
> "Cardano Cowgirl",
> "Ring of Fire",
> "Smokin",
> "Crypto Queen 01",
> "Smell The Flowers",
> "Southwestern Storm 01",
> "The Wanderer",
> "Stormy Skies",
> "Cosmic Toker",
> "House of Whatever Nicki Minaj",
> "Western Diamondback 01",
> "Western Diamondback 02",
> "Share Love",
> "Lookin At You",
> "Just for Laughs",
> "The Firestarter 01",
> "The Firestarter 02",
> "Enchantress 01",
> "Enchantress 02",
> "No Escape",
> "Kryptonite",
> "The Road There",
> "Cloaked Beauty",
> "Hidden Life",
> "Into the Blue 4k",
> "Beautiful Storm",
> "Desert Night",
> "Snake Eyes",
> "Sonoran Life",
> "Wild Horses 4k",
> "Southwestern Wildlife Collection",
> "Shelter in the Desert",
> "Desert Dreamland",
> "Firedance 01",
> "Saguaro Bloom",
> "Of Myth and Mystery",
> "The Bump in the Night",
> "Land of the Lost",
> "The Road There 02",
> "Into the Unknown",
> "Saguaro Garden",
> "The Morning View",
> "Cabin in the Woods",
> "Enchanted Beauty",
> "Desert Moonrise",
> "The Awakening",
> "Happiness Cube",
> "Cryp7o Booty Koin",
> "Cryp7o Booty Koin 2.0",
> "Beautiful Trip",
> "Beach Vibes",
> "Trip Time Skull",
> "Witching Hour",
> "Celestial Beauty",
> "The Wall",
> "Oh Hey!"
> ],
> 
> ```
> 	"policies": [
> 		"8ac4bc9f6017ebc42f4578b9737fd2e09bede9f5979b56aeb6c30ab7",
> 		"1fc3a6e2146ba4007e8b51756dffbd8e941886f0f4cf1ecc3b694563",
> 		"d1f94d8d9b80055a3d880906c3b9731b41265e79bb46898267752698",
> 		"1dc5ddece74dc9e6ac06cfbfe6033c6e0eed7e2c936cdb4fde137fa9",
> 		"6b7de66147ac9985016423e254fa8879f67af660feee7d648980bffb",
> 		"ebd626943344ade9a67c28c5834fa6fe600f132ee2cd238c44fd98c9",
> 		"3d3d3c7f94071086a2e079011f1e741b601f16c859a47bef5ee79055",
> 		"31fd03a0eb5fc59f1bebaea224ab573da72b926e4dbc1480d581bd74",
> 		"3e230e067bcf10d332886a57f92b280521d4fa5dd87de22145799b01",
> 		"df55d89912d09158fc28927a7bd864c8fa25a616f971a80a6975f4a6",
> 		"d4ceae0ecbe86de82a39658e8eee603026d111313afa3b7223222403",
> 		"9dabcee67e53b37b29a582efb83d8f8fe6f64f83b87c1a9311b6172d",
> 		"8223dc1da366da0bda214e557d6ea9d2066ea5557f9ffa2d2691b106",
> 		"a2f17dbb7ec0e97df9360c3c783ae49826ab18d36dded16d08a087d9",
> 		"8187cb8ea8d4be7505c7a6cb1144f02d0d0724a5179fcc47c674a4f4",
> 		"b375e5d64936ece167d1c400465f665993ccd9d01cf7937cbc0cfb5c",
> 		"eac287b700c9d043f7629f114a401a1b905af85809ffdf8b2dc5ceb8",
> 		"edbc364f180a87486a782aa9d80d9a58a7c5978586244526f901365d",
> 		"aeb4e30a40378701fe605072239a5bcda8635b245214e4db2ed2da61",
> 		"79fbca4616b6ab3a1ce78c48b58f65e4b608460929cc9de2f9731283",
> 		"5315e250e240e37dca5e278fe766e9db0047bde7f816efccd9e17f69",
> 		"570759bebc0e6b305484819d18cd1695c70d69bc1a0e7be5c9e8d496",
> 		"b9a6a6ce51c6a70aec7686d77073385d6e7862e31646bb6d59d06c28",
> 		"e18f212ab024f19b32507074c08d5082f6ac8f261903c7cb143314bf",
> 		"500eb610ba63cc259c494239e84e43d1a9427937a00ab08b28fb7733",
> 		"971d31e2560e266e4a3de0d4c56587d18bea58aa7a1f5d6263b276a1",
> 		"d12eca789bdc9a9901e7d10c116527e27831e5b262cfa50e6111667f",
> 		"9dad2b86b6fdc0e7cb3f84579256a2b84e37c47b962259ce8ae574af",
> 		"a4574bcfb3210e9d0a36aa5a53de06c22b9b28cbea20034d89992941",
> 		"7e875eec5c0d4785aa2be7267baa8ee5a85ddef5782fbf0c1e995d27"
> 	]
> },
> {
> 	"project": "VanityTrophiesxcryp7ocr3ations",
> 	"tags": [
> 		"Vanity Trophies x cryp7ocr3ations"
> 	],
> 
> 	"policies": [
> 		"5edd05fb06c1fa3f0c9df501983f449019b4b9cfc494248ed89d7e26"
> 	]
> 
> }
> ```
> 
> ]

Thank you so much! I committed the change. I am sorry you had to take your time to fix that, I appreciate it very much! Thank you for everything you and your team do for this community!

**Pull request merged**
