### PR TITLE
PACHARPOOM CNFT MONSTERPROJECT GIVEAWAY EVENT

### PR DESCRIPTION
**Pull request by PACHARPOOM**
gmail : pacharpoommuenpetza@gmail.com
twitter : https://twitter.com/PACHARPOOM
IG : https://www.instagram.com/pacharpoom/

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by PACHARPOOM** [comment]
gmail : ***@***.***
twitter : https://twitter.com/PACHARPOOM
IG : https://www.instagram.com/pacharpoom/

ในวันที่ จ. 6 ธ.ค. 2021 เวลา 21:06 KaiNFT ***@***.***>
เขียนว่า:

**Comment by PACHARPOOM** [comment]
> Dear Contributor,
> 
> Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.
>I already posted it on Twitter, you can go check it out.
gmail : pacharpoommuenpetza@gmail.com
twitter : https://twitter.com/PACHARPOOM
IG : https://www.instagram.com/pacharpoom/

**Comment by MaxJewell** [comment]
You must include the policy ID number in the post to be able to be verified.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
