### PR TITLE
Create Rabid Raccoon Club

### PR DESCRIPTION
**Pull request by DeocsMarco**
https://twitter.com/RabidRaccoonNFT
https://www.rabidraccoon.club/
https://discord.com/invite/DNak5VMsau

### CODE REVIEW

**Comment by DeocsMarco** [comment]
> https://twitter.com/RabidRaccoonNFT https://www.rabidraccoon.club/ https://discord.com/invite/DNak5VMsau

policy id is on the website as well as my linked in

**Comment by KaiNFT** [comment]
Hi Contributor, 

Please can you make the necessary adjustments to the JSON file so I can merge the pull request.

**Comment by DeocsMarco** [comment]
updated!

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
