### PR TITLE
Chimpion Club

### PR DESCRIPTION
**Pull request by chimpionclubcnft**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by chimpionclubcnft** [comment]
Website: https://chimpionclub.com/
Twitter: https://twitter.com/ChimpionClubNFT
Discard: https://discord.gg/vHNKzgK5Ng
Instagram: https://www.instagram.com/chimpion_club

Please help us check!

**Comment by chimpionclubcnft** [comment]
please help us check as soon as possible, thanks!

**Comment by chimpionclubcnft** [comment]
Thanks!

**Pull request merged**
