### PR TITLE
Dognuts

### PR DESCRIPTION
**Pull request by verouverou**
https://twitter.com/CryptoDognuts/status/1466716767200366596?s=20
https://twitter.com/CryptoDognuts
www.cryptodognuts.com

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request.

**Comment by verouverou** [comment]
Hi,

I think I need help. This is the second time I try to verify my project without success. can you help me? I have followed the tutorial but I can't get it right.

Thanks,
V

**Comment by TomStray** [comment]
Dear Contributor, on line 3, please change the characters around Dognuts so that they are speech marks. Like this: "Dognuts"

**Comment by verouverou** [comment]
Done :) Thank you sooo much for helping!

**Pull request merged**
