### PR TITLE
ADAm 

### PR DESCRIPTION
**Pull request by crzycuban**
pull request to twitter.

### CODE REVIEW

**Comment by crzycuban** [comment]
http://twitter.com/Crzycuban17

**Comment by crzycuban** [comment]
I didn't? I've been waiting. only thing I did was fetch it up stream like it says. I'm waiting on this so I can meet with a management team of hip hop artist.  I really need this done? What can I do. PleaseSent from my T-Mobile 4G LTE Device
-------- Original message --------From: TomStray ***@***.***> Date: 10/14/21  5:59 AM  (GMT-05:00) To: Cardano-NFTs/policyIDs ***@***.***> Cc: crzycuban ***@***.***>, State change ***@***.***> Subject: Re: [Cardano-NFTs/policyIDs] ADAm  (#1493) 
Closed #1493.

**Comment by crzycuban** [comment]
Thank you. Waiting on my gold check then I can set my meeting.  They want to see that I can get a project verified. Much appreciated. Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: TomStray ***@***.***> Date: 10/14/21  6:10 AM  (GMT-05:00) To: Cardano-NFTs/policyIDs ***@***.***> Cc: crzycuban ***@***.***>, State change ***@***.***> Subject: Re: [Cardano-NFTs/policyIDs] ADAm  (#1493) 
Reopened #1493.

**Comment by TomStray** [comment]
Dear Contributor, please change lines 5 and 6 of your "Update Celebrate Alonzo" code so that it is parallel with lines 2 and 3.
As well as this, please click before the speech marks at the start of lines 7 to 10 and press the Tab key to indent them once.

When I was talking about removing the "policy", I mean remove it from the speech marks so that it is just the policy ID by itself. This is on line 4 of the "ADAm" code, don't worry about line 3 of the code as that is fine.
image

**Comment by TomStray** [comment]
Dear Contributor, your twitter is perfect but I have not had new or updated code through for your "ADAm" update.

Don't worry about making mistakes, if you verify any more policy IDs, hopefully the journey will be a bit smoother for you.

**Comment by crzycuban** [comment]
ADAm #1493 Opencrzycuban wants to merge 26 commits into Cardano-NFTs:main from crzycuban:main+13 −0  Conversation 14 Commits 26 Checks 0 Files changed 1Changes from all commits File filter Conversations Jump to  0 / 1 files viewedReview changes  13  Celebrate Alonzo Viewed@@ -0,0 +1,13 @@{    "project": "CelebrateAlonzo",    "tags": [         "ADAm"    ],    "policies": [        "115b2d208d6e62fdcf4d7283e3b3cd4b9a32f7b306d498180e1b5f73",        "6aef50c5baf6c51604381702f69bb8cc178f4ae2c31362488efb99f5",        "861b5e3087b1ee5824f76de9dfe08b60e17826c0c76ca6d861eb8af9",        "580d623615e7e9026f2c91270bd0830f3ef73ef7cafc859b8cb4d764"     ]}This is what I see. I am not sure what to correct? I cant find the original only this 1.   Angel H. Martinez From: TomStraySent: Monday, October 18, 2021 9:05 AMTo: Cardano-NFTs/policyIDsCc: crzycuban; State changeSubject: Re: [Cardano-NFTs/policyIDs] ADAm (#1493) Dear Contributor, please send a link to your twitter.Also, please copy this on your "ADAm" code.—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Review by crzycuban — COMMENTED** [review]
up to date ADAm #1493

**Pull request closed without merging**
