### PR TITLE
RequestOfHelp Project

### PR DESCRIPTION
**Pull request by TheCodingPassion**
New Projects
twitter handler @theGamingPassi1

### CODE REVIEW

**Comment by TheCodingPassion** [comment]
https://twitter.com/theGamingPassi1

**Comment by TheCodingPassion** [comment]
Website is being developped

**Comment by TheCodingPassion** [comment]
https://twitter.com/theGamingPassi1
https://twitter.com/theGamingPassi1/status/1486694528899858438?s=20

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs on lines 8, 9 and 10 to your twitter.

**Comment by TheCodingPassion** [comment]
Done
https://twitter.com/theGamingPassi1/status/1488517456045953026?s=20&t=TBSsoUdDjjoA9dlnCb45bQ

**Pull request merged**
