### PR TITLE
Added CoinWarsCardano001

### PR DESCRIPTION
**Pull request by Cardano-Polska**
https://twitter.com/CardanoPoland/status/1463525518981091339/

### CODE REVIEW

**Comment by Cardano-Polska** [comment]
https://twitter.com/CardanoPoland/status/1463525518981091339/

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your website so that I can verify.

**Comment by Cardano-Polska** [comment]
Here you are. Link below.

https://www.cardano-polska.org/pl/informacje/nft/



W dniu 30/11/21 o 12:40, TomStray pisze:

**Comment by KaiNFT** [comment]
Dear Contributor,

The link you have submitted displays a policy ID that does not correlate with the policy ID you have submitted in the commit, please can you make the appropriate changes to fix this.

**Comment by Cardano-Polska** [comment]
My mistake. I threw the policy of the previous project on GitHub. It 
should be okay now.

W dniu 02/12/21 o 13:41, KaiNFT pisze:

**Pull request merged**
