### PR TITLE
Update Cadagirls

### PR DESCRIPTION
**Pull request by Fledermaus29**
Added giveaway policies from single-minted nfts

https://twitter.com/Cadagirls/status/1438205088401661963

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to the tags area if you do not have any tags to put in as it is causing conflicts.

**Comment by Fledermaus29** [comment]
Thank you MaxJewll. I have done this now :)

**Comment by MaxJewell** [comment]
What you will need to do is remove the whole line as you have no tags to use.

**Comment by Fledermaus29** [comment]
Hi MaxJewell,  but I have added in tags as you can see from the top section. Could you help edit this for me please? I am scared that I will do something wrong. When I open the file and make a change as a 'new commit' this issue does not show up.

**Comment by Fledermaus29** [comment]
This is what I see when I last made a new commit. 

policy commit

**Pull request closed without merging**
