### PR TITLE
Update galactic7

### PR DESCRIPTION
**Pull request by acoesdividendos**
add dara policy

### CODE REVIEW

**Comment by MaxJewell** [comment]
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by acoesdividendos** [comment]
here you have the tweet with the new policy: https://twitter.com/Galactic7_Art/status/1457793818447650821
and the website with both: https://galactic7.com

**Comment by acoesdividendos** [comment]
Hey @MaxJewell can you please check the PR?

**Comment by KaiNFT** [comment]
Dear Contributor,

Thank you for your patience, your request has now been merged.

**Pull request merged**
