### PR TITLE
Rckstr Coin

### PR DESCRIPTION
**Pull request by RckstrStakePool**
https://twitter.com/RckstrStakePool

### CODE REVIEW

**Comment by RckstrStakePool** [comment]
need help?! it isnt verified on the website

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs to your twitter so I can verify.

**Comment by RckstrStakePool** [comment]
How can i add the policy IDs to twitter?

**Comment by RckstrStakePool** [comment]
https://rckstr.io/nft

**Pull request merged**
