### PR TITLE
Fortune Cookie

### PR DESCRIPTION
**Pull request by DragonPavilion**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please correct the error in the json file and provide proof of product ID via website or social media so I can merge the pull request.

**Comment by DragonPavilion** [comment]
https://twitter.com/DragonPavilion

this is the twitter. 

May i know what is incorrect about the json file please?

**Comment by KaiNFT** [comment]
Dear Contributor, 

This is the syntax error that has been a result of the file check.

"SyntaxErrorUnexpected token ] in JSON at position 134"

**Comment by DragonPavilion** [comment]
Sorry, following the example here, which part is position 134  (we're very lost) 


image

**Comment by DragonPavilion** [comment]
i cannot understand what is incorrect though


image

**Comment by KaiNFT** [comment]
Dear Contributor, 

Sorry about the confusion, what happens is the JSON validator checks the old files so it thinks there is an issue however you have already corrected it, I have rectified this by removing the old files and I will now merge your request.

**Comment by DragonPavilion** [comment]
YEY !! thank you so much !!!
appreciate your help heaps!! 
been at this 24 hrs now.. lol super fail. 
thank you once again.

**Pull request merged**
