### PR TITLE
Add policies for my two projects.

### PR DESCRIPTION
**Pull request by honungsburk**
I've one generative art project "Stained Glass" and then another containing all my digital paintings. The policy to lock my digital paintings is fairly long-lived, maybe that isn't the best idea? Hope it's fine. I'm using nft-maker.io/pro if that information is of any use.

Website: www.frankhampusweslien.com (I'll add policies to my website shortly)

I named the file after myself since I'm planning on creating more projects in the future.

### CODE REVIEW

**Comment by honungsburk** [comment]
https://twitter.com/HampusFrank/status/1429828665139937285

**Comment by Dean00K** [comment]
Hey Frank, they second policy doesn't exist, is it not minted yet?

**Comment by honungsburk** [comment]
That is correct. I will allow people to buy/mint within a day or two.

**Comment by Dean00K** [comment]
just remove the comma from the end of line 5 and I'll merge

**Pull request merged**
