### PR TITLE
Hopefully I did it right

### PR DESCRIPTION
**Pull request by ArtsciVisions**

### CODE REVIEW

**Comment by ArtsciVisions** [comment]
Please verify or tell me what is wrong

**Comment by ArtsciVisions** [comment]
Accidently closed

**Comment by MaxJewell** [comment]
This is a good start.
What I will need you to do is to give me a link to a twitter/webpage with the Policy ID's on them to verify your identity.

Many thanks.

**Comment by ArtsciVisions** [comment]
Hello,
Thank you very much. This is the link: https://twitter.com/ArtsciVisions

**Pull request closed without merging**
