### PR TITLE
Chibi Kids

### PR DESCRIPTION
**Pull request by Steakcnft**
Discord : https://discord.gg/MkRbnpZz3r
Website : https://chibikids.io/
Twitter : https://mobile.twitter.com/ChibiKidsNFT

### CODE REVIEW

**Comment by Steakcnft** [comment]
Discord : https://discord.gg/MkRbnpZz3r
Website : https://chibikids.io/
Twitter : https://mobile.twitter.com/ChibiKidsNFT

**Comment by MaxJewell** [comment]
Afternoon, 
File Chibi Kids is not in projects directory!
Make sure you make this change in the directory and in the commit. 
Thanks.

**Comment by Steakcnft** [comment]
Have fixed it now please let me know if it worked.

**Comment by MaxJewell** [comment]
The issue has not been resolved. I will close this now, please try again on a new pull request.

**Pull request closed without merging**
