### PR TITLE
Jordi Leitao

### PR DESCRIPTION
**Pull request by JordiLeitao**
https://twitter.com/RandomS27921635/status/1468672071035244544

https://twitter.com/RandomS27921635

https://doit4llguy.wixsite.com/jordileitao (This is a temporary website that I dont want to share at twitter. I will have a better one later)

Last time I made this Pull request I made with the correct Readme that you just canceled me and said I needed to use.

I want to create more series other than "Genesis". But want them to show as a different name at CNFT.io. Is this the way to do it?

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning,
Please edit your Pull Request, the new file must be within the 'Projects' directory. 
Please check the README.md file for further information: 
https://github.com/Cardano-NFTs/policyIDs/blob/main/README.md

**Comment by JordiLeitao** [comment]
I cannot or dont know how to Edit :\ What can I do? Cant do a new pull request also , since it says a pull request with the same name is already created.

**Comment by MaxJewell** [comment]
If you can delete this pull request do so, then create a new one following the new steps. 

Many thanks.

**Comment by JordiLeitao** [comment]
I think my policy ID was already verified by another admin?

**Pull request closed without merging**
