### PR TITLE
Create Mazzanti NFT

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
4 Project bundle

### CODE REVIEW

**Comment by GabrielMazzanti** [comment]
Hey again. Final Version

**Comment by GabrielMazzanti** [comment]
also : Twitter @gabrielmazzant3, My personal asset wallet is : addr1qy9xgqaqkash3wj90ad26qfm8qy837m8f387rncx2d02hnmexu7umnn2eu26y0mqcrty2zrhsfx3kq4je0hpqskm2desy7te04

Gabriel.texier@yahoo.fr
gabriel texier (facebook) with piano cover on it

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs to your twitter or send a link to your website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

**Comment by GabrielMazzanti** [comment]
Done i put thé whole pull request on twitter. It IS me (ive teied 7 Times
to submit)

**Pull request merged**
