### PR TITLE
Added PunksOnAda Special Edition pre sale policy

### PR DESCRIPTION
**Pull request by Brandonnft**

### CODE REVIEW

**Comment by cryptokraken11** [comment]
This project is a scam. Same scam team that runs "trippy" degen ape academy.

degen academy:

https://www.degenape.academy/

their ripoff site:

https://www.trippyacademy.com/


They take existing succesful projects and rip them off. 

Their site is a joke and screams scam too. 

https://www.punksonada.com/

**Review by Brandonnft — COMMENTED** [review]
updated

**Comment by cryptokraken11** [comment]
brandon is a ripoff scam artist. highly recommend you DON'T verify their project.

**Comment by CNFT-io** [comment]
We are looking into this.

**Pull request closed without merging**
