### PR TITLE
Ridiculous NFTs

### PR DESCRIPTION
**Pull request by jc010816**
www.ridiculous-nfts.com

### CODE REVIEW

**Comment by jc010816** [comment]
www.ridiculousnfts.com

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by jc010816** [comment]
> Dear Contributor,
> 
> Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

Hello

Website has been uploaded with Policy ID assigned.

**Comment by jc010816** [comment]
Good afternoon,

The website has been updated to reflect the Policy iD.

Kind regards.

________________________________

**Comment by jc010816** [comment]
Good afternoon

Can you confirm if you have merged the pull request and also confirm when the project name 'Ridiculous NFTs' will become available on CNFT.io as it currently states 'Unknown Project', the url is https://cnft.io/token/61d6df3a4597aa5a345f9ac2.
[https://infura-ipfs.io/ipfs/QmYHufts6YYiaNHixC5h8DKVXTWfhxpT9PEHik83Bh1z38]<https://cnft.io/token/61d6df3a4597aa5a345f9ac2>
CNFT.IO - (i). Rise of the beast<https://cnft.io/token/61d6df3a4597aa5a345f9ac2>
CNFT.IO is a marketplace for Cardano Non-Fungible Tokens, launched in July 2021 from a team decentralised across the world, we can officially say we are the first marketplace on Cardano.
cnft.io


Thanks
________________________________

**Comment by jc010816** [comment]
Good afternoon,

I have updated the Policy IDs file for the project Ridiculous NFTs on Cardano-NFTs/policyIDs<https://github.com/Cardano-NFTs/policyIDs>. #7003.

Please let me know if there is anything you may need.

Many thanks.

**Pull request merged**
