### PR TITLE
 Create The Psychedelic 

### PR DESCRIPTION
**Pull request by ThePsychedelicMan**

### CODE REVIEW

**Comment by ThePsychedelicMan** [comment]
https://twitter.com/ThePsycheMan?s=09

**Comment by ThePsychedelicMan** [comment]
https://cnft.io/token.php?id=6138c2f539e8404cb44ca3d3

**Comment by ThePsychedelicMan** [comment]
I do not have a website yet but will be starting soon, I tweeted the pull back request please check into it.
Thanking you in Advance.

**Comment by ThePsychedelicMan** [comment]
Information

project: ThePsychedelic

Policy IDS : 
43b5fb96b9657331798999991fca2522aa285c992e61bf26d6cd5534
2870cccb6127793af0df733e74175d077ff7414c1c5b7063f61e449f
23584c64008e60bb945ff000a9e60d45af84c10eda28a2d920f45df5
67d7a65bcb029654860315e26678bd894f3c268e8675735a3530abb3
cf886004be21294339e3ff4e0073f8f3fb415f17a696a34e075492ac

**Comment by ThePsychedelicMan** [comment]
@Dean00K @itsmestale

**Comment by ThePsychedelicMan** [comment]
The website, its not perfect yet but I am still working on it, this is just a preview, will hire a professional once my NFTs are up and running. Thank You.
https://thepsychedelic751724571.wordpress.com/

**Comment by ThePsychedelicMan** [comment]
Hey man, am I doing something wrong? Can you just let us know?

**Comment by Fl4tl4nd** [comment]
> Information
> The Psychedelic is a unique project minted on the blockchain. The project gives you the visuals your brain produces when you take psychoactive substances. As a medical student psychedelics is something that has fascinated me a lot and thus the project was created. It took me a month's work to get this work ready and to post it finally on the cnft.io. Would really appreciate it you could verify, feel free to email me if you have more enquires. [varunp998@gmail.com](mailto:varunp998@gmail.com)
> I would be happy to help you guys out!
> 
> Project Twitter : https://twitter.com/ThePsycheMan?s=09
> 
> I tweeted the pull back.
> https://twitter.com/ThePsycheMan/status/1436311346212073480?s=19
> 
> The website, its not perfect yet but I am still working on it, this is just a preview, will hire a professional once my NFTs are up and running.
> https://thepsychedelic751724571.wordpress.com/
> 
> Minted using nft-maker.io
> 
> project: ThePsychedelic
> 
> Policy IDS :
> 43b5fb96b9657331798999991fca2522aa285c992e61bf26d6cd5534
> 2870cccb6127793af0df733e74175d077ff7414c1c5b7063f61e449f
> 23584c64008e60bb945ff000a9e60d45af84c10eda28a2d920f45df5
> 67d7a65bcb029654860315e26678bd894f3c268e8675735a3530abb3
> cf886004be21294339e3ff4e0073f8f3fb415f17a696a34e075492ac
> 
> Thanking you,
> ThePsychedelicMan

These two belong to another project, please remove them.

67d7a65bcb029654860315e26678bd894f3c268e8675735a3530abb3
23584c64008e60bb945ff000a9e60d45af84c10eda28a2d920f45df5

**Pull request merged**
