### PR TITLE
Create CardanoDivers

### PR DESCRIPTION
**Pull request by CardanoDiver**
We are waiting for you to join our adventures.
https://twitter.com/SpearosNft

### CODE REVIEW

**Comment by CardanoDiver** [comment]
https://twitter.com/SpearosNft/status/1490052356343533568?s=20&t=4oURLw7k2CrEHgRpi40sGQ

**Comment by CardanoDiver** [comment]
https://twitter.com/SpearosNft/status/1489680619328180225?s=20&t=4oURLw7k2CrEHgRpi40sGQ

**Comment by CardanoDiver** [comment]
https://cnft.io/token/620025ad59e4ac4f448116a2

**Comment by CardanoDiver** [comment]
https://tokhun.io/hasansunear

**Comment by CardanoDiver** [comment]
https://twitter.com/SpearosNft/status/1491461829586997250?s=20&t=3bHtw_NBecBlsz4scmME3A

**Comment by CardanoDiver** [comment]
Policy ID commented on Twitter account : https://twitter.com/SpearosNft/status/1491461829586997250?s=20&t=3bHtw_NBecBlsz4scmME3A

**Comment by KaiNFT** [comment]
Dear Contributor, 

This request will now be closed, make a new ticket with the following criteria; the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
