### PR TITLE
Delete old CryptonicCreations project then Re-Add as Cryptonic Creations

### PR DESCRIPTION
**Pull request by rbcrypto78**
Please delete the original Cryptonic Creations project as it has never worked, then re-add as Cryptonic Creations.

### CODE REVIEW

**Comment by rbcrypto78** [comment]
Both PolicyIDs were already verified, but her eis the tweet again if needed...
https://twitter.com/Crypto_Krazie/status/1463868028240777222

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request.

**Comment by rbcrypto78** [comment]
Hello, I was requesting to have the original policy project completely
removed and readied with the new job file that is attached.  Please contact
me in Discord Crypto_Krazie for more information.   The original has never
worked.

**Comment by rbcrypto78** [comment]
No longer required, everything appears to be working

**Pull request closed without merging**
