### PR TITLE
Create J0K3R

### PR DESCRIPTION
**Pull request by Ivaanajo**

### CODE REVIEW

**Comment by RedArchfiend** [comment]
Please provide Links to social/website that shows your Policy ID.

**Comment by Ivaanajo** [comment]
Tweet Referencing this Pull Request https://twitter.com/RulingJoshua/status/1444539030360584192?s=20
Tweet of Git Hub: https://twitter.com/RulingJoshua/status/1444573019616145414?s=20

**Comment by Ivaanajo** [comment]
https://twitter.com/RulingJoshua/status/1444672404614041601?s=20

**Comment by Ivaanajo** [comment]
any update on this Im waiting

**Comment by Ivaanajo** [comment]
Hi
Updated the PR with the social linked to the policy ID
waiting for update for the update

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Ivaanajo** [comment]
update

**Comment by Ivaanajo** [comment]
PR Posted in Twitter 
https://twitter.com/RulingJoshua/status/1445170850177552386

**Pull request merged**
