### PR TITLE
Create RajPalzMarketPlace

### PR DESCRIPTION
**Pull request by dhiraj165**
First Market Place Project.

### CODE REVIEW

**Comment by dhiraj165** [comment]
Hello All, We are still waiting on an action from the maintainer on our pull request. Can someone kindly look into the request and take action? Here are the asset IDs

Here are the Asset Links of CNFT 👍 
https://cnft.io/marketplace?st=ADAMinions
https://cnft.io/marketplace?st=ADAGODESS

**Comment by TomStray** [comment]
Dear Contributor, please amend your links as when I click on them, this is what I can see:

image

Many thanks,

**Comment by dhiraj165** [comment]
Can you kindly explain how to amend the links? 

When I go in my CNFT.IO profile, I can see my listings and when i click it, i can go to the appropriate asset, see below.

However, through Marketplace, i am not able to find it. Can you kindly help if there is any process to correct it?

image

image

**Comment by dhiraj165** [comment]
> Dear Contributor, please amend your links as when I click on them, this is what I can see:
> 
> image
> 
> Many thanks,

Can you kindly explain how to amend the links? 

When I go in my CNFT.IO profile, I can see my listings and when i click it, i can go to the appropriate asset, see below.

However, through Marketplace, i am not able to find it. Can you kindly help if there is any process to correct it?

image

image

**Pull request merged**
