### PR TITLE
Create This&That

### PR DESCRIPTION
**Pull request by ThisAndThatNFT**
Collection by the artist This&That

### CODE REVIEW

**Comment by ThisAndThatNFT** [comment]
https://twitter.com/ThisAndThatUK1/status/1459911505554640897

**Comment by ThisAndThatNFT** [comment]
https://pool.pm/23dc58c8d388c75459db9d33ab5dabb06ed0cf63236948a4d4058606.MagpieonaMushroom

**Comment by KaiNFT** [comment]
Dear Contributor,

Please correct the error in the json file so I can merge the pull request.

**Comment by ThisAndThatNFT** [comment]
I believe this should now work fine.

**Pull request merged**
