### PR TITLE
Added artaphakt

### PR DESCRIPTION
**Pull request by artaphakt**

### CODE REVIEW

**Comment by artaphakt** [comment]
Twitter verification
https://twitter.com/artaphakt/status/1429396749886631937?s=20

**Comment by Dean00K** [comment]
Hey mate, can i get a pool.pm link or something? cheers

**Comment by artaphakt** [comment]
I have a Tokhun.io for this one, is all so far...

https://tokhun.io/explore/4f8f6c36f4e985d7fe3ed77af15669c73ecf93b2cc8482f1e3b6edcb.artaphakt

**Comment by Dean00K** [comment]
So it's not minted yet right?

**Comment by artaphakt** [comment]
Strange. It is minted. 
https://cardanoscan.io/token/57d26f1ae8898b427ccc1358fa5dca6cfe302343

I can try to withdraw the asset. Or start over with a new policy not on Tokhun. Perhaps. If that link doesn't help.

**Comment by artaphakt** [comment]
Withdrew the token and it's now in my wallet.

https://pool.pm/4f8f6c36f4e985d7fe3ed77af15669c73ecf93b2cc8482f1e3b6edcb.artaphakt

**Comment by Dean00K** [comment]
ah sweet

**Pull request merged**
