### PR TITLE
Added Moonimals

### PR DESCRIPTION
**Pull request by Moonimals**
Animals were sent to the moon and crashed their rockets on the moon's surface. Luckily, they suited up and survived! They are called, Moonimals!

Twitter: https://twitter.com/Moonimals

### CODE REVIEW

**Comment by Moonimals** [comment]
Discord: https://discord.gg/xxSpFqKHnc

**Comment by Moonimals** [comment]
Good day @MaxJewell, @nicolasayotte and @TomStray 

For your reference, below is our twitter pull request post:
Twitter Pull Request Post: https://twitter.com/Moonimals/status/1440668613422170115?s=20

We will be launching this coming September 30 at 6:00 PM GMT+8. Below is our Nami Wallet address and NFTs to be posted on the marketplace. There will be 21 of them on September 30.
addr1qxgrc4c47dam77uwrq0kzpjdhmq3ux5gctyjzeljjt3jswptuk67l7fnq5rg8md2llpgp348rwslh9xv6mahpx5ek7rqwhpju8

Please do not hesitate to let me know if I'm missing any documents. Thank you.

**Comment by Moonimals** [comment]
Hi @MaxJewell @nicolasayotte @TomStray ,

Greetings!!

We will be listing on 30th September at 10:00 AM UTC. Hoping if you can check our project and can get verified from you.

Thank you so much and looking forward to hear from you very soon.

Regards,
Moonimals

**Comment by MaxJewell** [comment]
Looks good, just need the policy ID in the chat of the channel on your discord and we can go ahead.

Thanks

**Comment by Moonimals** [comment]
Hi @MaxJewell ,

Thank you for the response, this means a lot. We have now put our policy ID in the channel. I hope our project will get verified before we launch it on Sept 30. That would be awesome!🙏 🙌

Regards, 
Moonimals

**Comment by Moonimals** [comment]
Hi @MaxJewell , 

Thank you for verifying our project. May I know how long will it take to reflect in CNFT.IO? 

Regards,
Moonimals

**Comment by Moonimals** [comment]
Hi @MaxJewell  ,

Thank you for verifying our project. We have done some changes in our policy ID since there was an extra comma and our JSON file is invalid. 

Can you help us to check our changes and verify? Appreciate your assistance. 

Thank you.

Regards,
Moonimals

**Comment by MaxJewell** [comment]
Unfortunately you will need to open up another Pull Request and I can go through the merge process with you ASAP.

I apologize for any issues caused.

**Comment by Moonimals** [comment]
Hi @MaxJewell ,

Thank you. I have open up another pull request. Please find below:
Removed comma after the policy ID. #1765

Regards,
Moonimals

**Pull request merged**
