### PR TITLE
Mosie

### PR DESCRIPTION
**Pull request by ImMosie**
Tried fixing the json

### CODE REVIEW

**Comment by nicolasayotte** [comment]
I have not reviewed the policy ids themselves, just helped a friend with the JSON formatting.
- fence

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide proof via website or social media so I can merge the pull request.

**Comment by ImMosie** [comment]
> 
> 
> Dear Contributor,
> 
> Please provide proof via website or social media so I can merge the pull request.

https://twitter.com/MosieAlong
https://www.lolcnft.com/#checkinv

**Comment by ImMosie** [comment]
> 
> 
> > Dear Contributor,
> > Please provide proof via website or social media so I can merge the pull request.
> 
> https://twitter.com/MosieAlong https://www.lolcnft.com/#checkinv

can send my notepad with all information as well, can verify through MarshallChow for random Pooples, can verify with Mermada as well for others :) sorry I am not very effective here.

**Comment by the-Minister-0001** [comment]
@ImMosie could you push that notepad onto pastebin, tweet a link to it with the info that these are the current policies for your NFTs and post the link to that tweet here :)

The less the good folks from CNFT need to do in order to find all the policies the faster they can approve it :)

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
