### PR TITLE
Please create Picasso

### PR DESCRIPTION
**Pull request by effincomputers**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by effincomputers** [comment]
I have links to Twitter and my business wwbsite nft page too

**Comment by effincomputers** [comment]
There are these links already in the request:

https://twitter.com/TmachineNf/status/1481202132091125760?s=20

https://effincomputers.com/NFT-INFO/policy-IDs.html

**Comment by effincomputers** [comment]
Hello. I was doing some additional work, and I noticed that the policy that
you were referring to was not on the website page that I thought I put it
on. But I've just added it here:
https://effincomputers.com/NFT-INFO/policy-IDs.html
Thank you.

**Pull request merged**
