### PR TITLE
Update Rabbitlung

### PR DESCRIPTION
**Pull request by marshallchow**
Added Bunny G

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file format in order for me to merge the pull request.

**Comment by marshallchow** [comment]
Hey sorry I don't understand what is wrong with my JSON format?

>

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please run your JSON file through a JSON validator to point out the specific issue. 

Thanks.

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by marshallchow** [comment]
> Dear Contributor,
> 
> Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

https://twitter.com/honallan/status/1470193255467732996

**Comment by MaxJewell** [comment]
Only one of the policy ID's have been given a link to here. Please add the others before it can be merged.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
