### PR TITLE
Update AIGrafix Collectible

### PR DESCRIPTION
**Pull request by AIGrafix**
we have change the minting tool and have new policy ids

### CODE REVIEW

**Comment by AIGrafix** [comment]
added new policy ids

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

**Comment by AIGrafix** [comment]
this is the twitter link:
https://twitter.com/AIGrafix_art/status/1465654863531028483

**Comment by TomStray** [comment]
Dear Contributor, please put your policy IDs somewhere on your twitter. If you would like, you could send me a link to a link-only tweet so it doesn't have to be on your main page and viewable by everyone.

**Comment by AIGrafix** [comment]
i have put a link back to this post on twitter (there are to many ids to post on twitter)
and i put it on our website: https://aigrafix.art/policy-ids/

**Pull request merged**
