### PR TITLE
CasitaCNFT Iris 

### PR DESCRIPTION
**Pull request by CasitaCNFT**
Discord: https://discord.gg/2CJ9bctX

Twitter: https://twitter.com/CasitaCNFT

website: https://casitacnft.io/

Policy ID: 3dbf6e792fb2359719c26da7ea6d139dfbdf21afb07ca8db18de9d7f

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

The policy ID in your commit appears to be incorrect, please make the necessary adjustments in order for me to merge the pull request.

**Comment by CasitaCNFT** [comment]
Hello there! Is this CNFT.io pull request at github? I dont know why its
wrong if we already minted as well :(

Thank you

**Comment by CasitaCNFT** [comment]
Hello, this is our POLICY ID that we got from nftMakerPro.

3dbf6e792fb2359719c26da7ea6d139dfbdf21afb07ca8db18de9d7f

Hope I can hear from you soon

Thank you

**Comment by MaxJewell** [comment]
The policy ID you are showing is not what is in your commit. Please replace it with the one you have commented withb so we can merge you.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Comment by CasitaCNFT** [comment]
Hello guys, so do you guys want me to pull request again at github to get
verified in CNFT.io?? It must be the same policy ID.. i copy and pasted in
NFT makerPro.

Thank you

**Comment by MaxJewell** [comment]
Yes please a new pull request would be sufficient.

**Comment by CasitaCNFT** [comment]
Sounds good!!

Thank you guys!!

**Pull request closed without merging**
