### PR TITLE
Add project

### PR DESCRIPTION
**Pull request by WLGallery**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

(FreeBeer & WLPXL)

**Comment by WLGallery** [comment]
Hello,

Thank you for your message and apologies for the mistake.

You can find the policy ID for Ars Mathematica at our website: wlgb.io/ma <http://wlgb.io/ma> at the bottom of the page

and also on twitter at: 

https://twitter.com/WL_Gallery/status/1466113770409926671

https://twitter.com/WL_Gallery/status/1466113739661484045 <https://twitter.com/WL_Gallery/status/1466113739661484045>

and pool.pm:

https://pool.pm/addr1q88h9u2zpypd9ghwr5hkpshlm0s78stfy6v9lfcfpksuu675g276q3ltpqcwdrst3rxqq88al82m0qj6lu6ugh8vdztq0ssfsm/0df0e2d8

for the other ones I still need some time, I will provide links as soon as possible.

Many thanks,

Agustin



Auguststr. 86
10117 Berlin
wlgb.io
***@***.***

**Comment by KaiNFT** [comment]
Dear Contributor, 

The website you have provided seems to be down, is there any chance you can sort this from your end?

**Comment by WLGallery** [comment]
ArsMathematica:

Website: 
https://wlgb.io/am/

Social-Media: 
https://twitter.com/WL_Gallery/status/1466113770409926671

**Comment by WLGallery** [comment]
Dear Kai,

thank you for your message.

I’m sorry I wrote the link wrong it’s wlgb.io/am

We have deleted the old requests and submitted a new one just for Ars Mathematica, which is our next drop this Saturday.

We have provided all the relevant links on GitHub but here they are again just in case.

# ArsMathematica: #

Website: 

https://wlgb.io/am/ <https://wlgb.io/am/>


Social-Media: 

https://twitter.com/WL_Gallery/status/1466113770409926671 <https://twitter.com/WL_Gallery/status/1466113770409926671>

https://twitter.com/WL_Gallery/status/1466113739661484045 <https://twitter.com/WL_Gallery/status/1466113739661484045>

Again sorry for the mistake.

Best,

WL_Gallery



Agustin Acevedo Landaluce
Auguststr. 86
10117 Berlin
weitenfeldlandaluce.com
***@***.***

**Pull request merged**
