### PR TITLE
Trybbles

### PR DESCRIPTION
**Pull request by newmindflow**

### CODE REVIEW

**Comment by itsmestale** [comment]
Hey can you please provide some proof you are the creator, a link to your discord etc.

**Comment by newmindflow** [comment]
Hi, sure, here are the links, if you want I can tweet something or post to prove ownership.

[Discord](https://discord.gg/AwEnRpRdcV)
[Twitter](https://twitter.com/trybbles)
[Instagram](https://www.instagram.com/trybbles)
[YouTube](https://www.youtube.com/channel/UCdLCpFEwc5G0sYqIFvdxlEw)
[Telegram](https://t.me/trybbles)
[Website](https://www.trybbles.com)

**Comment by newmindflow** [comment]
Will be posting this tweet

All Trybbles CNFTs are minted under the same policy id: 

d05271dc4748d2a2c69ddf91135d1a712b034f1c1b375d623a12a7d8

Please check this before making any purchases, you can even enter it in the search field on cnft.io to confirm you’re only getting genuine results.

**Comment by newmindflow** [comment]
posted

**Pull request merged**
