### PR TITLE
AdaPaint

### PR DESCRIPTION
**Pull request by Cardanonftada**
Paint ada cardano

### CODE REVIEW

**Comment by Cardanonftada** [comment]
> Paint ada cardano

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

**Comment by Cardanonftada** [comment]
@cardano1988

**Comment by Cardanonftada** [comment]
🙂

**Comment by Cardanonftada** [comment]
Published in my Twitter https://twitter.com/Cardano1988

**Comment by Cardanonftada** [comment]
😉😉

**Comment by Cardanonftada** [comment]
What more should I do?

**Comment by Cardanonftada** [comment]
> Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

Published in my Twitter https://twitter.com/Cardano1988

**Comment by Cardanonftada** [comment]
> Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

Published in my Twitter https://twitter.com/Cardano1988

**Pull request closed without merging**
