### PR TITLE
Update Derp Birds

### PR DESCRIPTION
**Pull request by chafnan**
Updated with policies for the  Derplings and Egg Shard drop

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by chafnan** [comment]
Yes we do. Here is a link to our website.

https://derpbirds.io/policy-ids

**Comment by chafnan** [comment]
@MaxJewell Would you mind taking a looking again. Thanks.

**Comment by chafnan** [comment]
@MaxJewell Just checking back in again. Any chance to get this approved.

**Comment by chafnan** [comment]
@MaxJewell We have the minting on Tuesday. Can you please approve?

**Comment by KaiNFT** [comment]
Dear Contributor,

Thank you for your patience, your request has now been merged.

**Pull request merged**
