### PR TITLE
Mynfties

### PR DESCRIPTION
**Pull request by aouimust**
i hope this time it will succes!

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by aouimust** [comment]
Hallo Sir, what do i have to do? is het possible with telegram or whatsapp?

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by KaiNFT** [comment]
With a website or a twitter/instagram

**Comment by aouimust** [comment]
You mean something like an URL? here is my twitter URL.

https://mobile.twitter.com/zouina_nl

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by TomStray** [comment]
Dear Contributor, please send another link instead of your twitter as it is very new and I unfortunately cannot accept it for verification as it could be used to falsely verify NFTs. Other acceptable link could include a website/CNFT.io listing/Pool.pm listing with your policy ID(s) on there so that I can verify.

**Comment by aouimust** [comment]
Here my pool.pm

https://pool.pm/addr1q9uq872mfg0hssh3encfqx290r7wgzqvslwzvh4cerfrarcf2wh4qet24xn550fpk3j8t492n2dk2mz2cgffnla0d8yq52rnuw

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by MaxJewell** [comment]
Please may you change the Policy ID which is in your commit to whatever the policy ID you are trying to verify as the Policy in your current commit does not exist.

**Comment by aouimust** [comment]
i see this one in my nft in cnft.io
bc7ca2eb2471368c50b811c74c114581f33e4d30440722889373261f

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Pull request merged**
