### PR TITLE
Cardoggo

### PR DESCRIPTION
**Pull request by CardoggoX**
cardoggo.com

https://cardoggo.com/nft/    (includes policy i.d)

https://twitter.com/CardoggoX/status/1473421170691162117  (includes policy i.d)

twitter.com/cardoggox

discord.gg/YJFfg5un

instagram.com/cardoggox   (includes policy i.d)

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by CardoggoX** [comment]
Hi,

We have now added the project.

Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by CardoggoX** [comment]
It is done, now. Could you check please?

Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TomStray** [comment]
Dear Contributor, I believe you need to create a new pull request in order for you to change it to the projects directory.

**Pull request closed without merging**
