### PR TITLE
Savage Rabbits

### PR DESCRIPTION
**Pull request by Dream-RL**
https://twitter.com/SavageRabbitNFT

https://savagerabbits.io

--

I am unable to figure out how to delete the previous failed file with special characters.  This request is formatted correctly.

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please remove all special characters from your "Savage Rabbits - Test Mint" code. In this case it would mean removing the "-"

**Comment by Dream-RL** [comment]
Hi there, I accidentally sent in a pull request with two files.  One contains the “-“ hyphen character and one does not. 

I do not know how to remove the file with the “-“.

Is it possible for you to just use the metadata from the file that does not contain the hyphen?

Thanks,
Joe Koch
https://savagerabbits.io

**Review by Dream-RL — COMMENTED** [review]
The required changes have been made.  Thanks.

**Review by Dream-RL — COMMENTED** [review]
Changed The project Name to match.

**Comment by KaiNFT** [comment]
Dear Contributor,

You're missing a [ at the start of your first file, please make the necessary adjustments to your pull request.

**Review by Dream-RL — COMMENTED** [review]
Added [.  Is there anything we can do to speed this up?  I am not familiar with this process so these mistakes are unfortunate.

**Pull request merged**
