### PR TITLE
Create Wall st Apes

### PR DESCRIPTION
**Pull request by creativequotient**

### CODE REVIEW

**Comment by creativequotient** [comment]
https://discord.com/channels/@me/887914127996104734/904057572162674718

**Comment by WallStreetApesClub** [comment]
[
	{
		"project": "Wall st Apes",
		"policies": [
			"0735a6f68074aac8c0a5a7e186502c89981779298738a20bdab594e6"
		]
	}
]

**Review by WallStreetApesClub — CHANGES_REQUESTED** [review]
Request changes as follows:
[
	{
		"project": "Wall st Apes",
		"policies": [
			"0735a6f68074aac8c0a5a7e186502c89981779298738a20bdab594e6"
		]
	}
]

**Review by WallStreetApesClub — COMMENTED** [review]
[
{
"project": "Wall st Apes",
"policies": [
"0735a6f68074aac8c0a5a7e186502c89981779298738a20bdab594e6"
]
}
]

**Pull request closed without merging**
