### PR TITLE
universmetaverse

### PR DESCRIPTION
**Pull request by MrRonin007**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by MrRonin007** [comment]
Dear  KaiNFT,
How I Can provide evidence of mypolicy ID via social media?

**Comment by MrRonin007** [comment]
I did it just now

**Comment by MrRonin007** [comment]
I did it . please check

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by MrRonin007** [comment]
please approve it

**Comment by KaiNFT** [comment]
Please look at the template given in the README file.

**Comment by MrRonin007** [comment]
please check it

**Comment by KaiNFT** [comment]
Can you re-open another request with just the updated file as it's failing to check it. I'll close this one.

**Comment by MrRonin007** [comment]
I just did it

**Pull request closed without merging**
