### PR TITLE
CardanoToaster

### PR DESCRIPTION
**Pull request by Leon1Art**
https://twitter.com/LeonArtgroup

### CODE REVIEW

**Comment by Leon1Art** [comment]
Proof link : https://twitter.com/leonartgroup/status/1470619090159083521?s=21

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your twitter.

**Comment by Leon1Art** [comment]
I did it ! And SHARE my twitter!

**Comment by Leon1Art** [comment]
> Dear Contributor, please add your policy ID to your twitter.

Hi buddy i did that 3 days ago ! https://twitter.com/leonartgroup/status/1470619090159083521?s=21

**Pull request merged**
