### PR TITLE
Added policy

### PR DESCRIPTION
**Pull request by MaykersCryptoCorner**
Please add policy 7fef75a0e3762ed1c9cc064870aee642cc51044435941b4ce9e4ab91

### CODE REVIEW

**Comment by MaykersCryptoCorner** [comment]
https://twitter.com/MaykersCrypto/status/1429190542726815746?s=19

**Comment by Dean00K** [comment]
Can I get some more information on your project? A twitter account with 6 followers and a single fungible token with a quantity of 3 doesn't really get verification. We are verifying projects with websites and roadmaps.. communities and utility etc.

**Comment by MaykersCryptoCorner** [comment]
It's a simple gnome themed CNFT art project, no real utility planned at the
moment. We just got started so no community to mention. The first series
will be 10 characters. Each series after will revolve around those
characters. Wasn't aware there was prerequisites. Thanks for the info.

**Comment by MaykersCryptoCorner** [comment]
We are in the process of building our website that incorporates the NFT's.
This project is tied to our Etsy store where we sell original sticker
designs and handmade items. We plan to incorporate crypto related products
in the near future. I understand this may not be enough to get verified,
but we definitely aren't scammers if that was the thought process behind
the comment regarding Twitter followers. I will reach back out once the
website is up.

https://www.etsy.com/shop/maykerscorner

Thanks,
Jason

**Comment by Dean00K** [comment]
Yeah, it's a little unclear for all at the moment, and i just need to do as much due diligence as possible. Working on an actualy "verification policy document" so people can have a read beforehand. but hey, that's what we get for being early right? I'll verify for now, good to see you building with us! Cheers.

**Comment by Dean00K** [comment]
oh, just need you to take that comma off the end of line 4.

**Comment by MaykersCryptoCorner** [comment]
Thanks Dean, I appreciate it and completely understand the skepticism. You
guys are doing things the right way by trying to protect the customers.

Thanks,
Jason

**Pull request merged**
