### PR TITLE
Create ADAPunkzMVP

### PR DESCRIPTION
**Pull request by transiti0nary**
Policy ID confirmation:
https://adapunkz.io/mvp

### CODE REVIEW

**Comment by KaiNFT** [comment]
Pending

**Comment by transiti0nary** [comment]
> Pending

Is there any hold up with this?

**Comment by KaiNFT** [comment]
Dear Contributor,

Your project is very similar to a popular project so I'm going to have to close this.

**Comment by transiti0nary** [comment]
Which project? Our MVP project is the only one like it that I've personally seen on Cardano. I'm the developer with ADAPunkz - please see the link in my comment above to the policy ID on our site, our site also links back to our GitHub here where you can see my commits under this account https://github.com/ADAPunkz @KaiNFT

**Pull request merged**
