### PR TITLE
Added project 'autre coeur'

### PR DESCRIPTION
**Pull request by CryptoNadger**

### CODE REVIEW

**Review by thingticketNFT — CHANGES_REQUESTED** [review]
tried to comment but cant display correct syntax in comment

**Comment by CryptoNadger** [comment]
"website: autrecoeur.com
twitter: @autrecoeur"

**Comment by MaxJewell** [comment]
Hello, 
Would you be able to add a link to a twitter account with all the Policy ID's on them.

Many thanks.

**Comment by CryptoNadger** [comment]
Hi Max,
I've just tweeted a thread with them all on: https://twitter.com/autrecoeur/status/1445387654271574026?s=20

You can also see them under Verification in my Discord: https://discord.gg/rMdGPy5wS8

**Comment by MaxJewell** [comment]
The last policy ID is not on the twitter thread.

**Comment by CryptoNadger** [comment]
Hi Max,

Sorry about that. It’s a new policy set up for my next collection, hence its omission from my site. I’ve added another tweet to the thread (https://twitter.com/autrecoeur/status/1445387654271574026?s=20 <https://twitter.com/autrecoeur/status/1445387654271574026?s=20>) with the extra policy ID on it.

Thanks,
ac

**Pull request merged**
