### PR TITLE
Create Panda Banda

### PR DESCRIPTION
**Pull request by pandabandacnft**
https://www.pandabanda.io/
https://twitter.com/PandaBandaCNFT

### CODE REVIEW

**Comment by MaxJewell** [comment]
Would you be able to add the second Policy ID onto the webpage and then I can put you through.

**Comment by pandabandacnft** [comment]
Done!
Thanks

**Comment by pandabandacnft** [comment]
Hi guys, when will you pull us through?
THe policy IDs have been updated on the website.

Kindly check this on priority.

Many thanks
Miranda

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by pandabandacnft** [comment]
Hi,
We have now created a new request and followed the tutorial.
We have posted our policyID on our website twitter and discord
We made sure the JSON format is valid, and here is the request.
https://github.com/Cardano-NFTs/policyIDs/pull/4027

We are releasing in one week, hope you can verify us beforehand.
Thanks and Kind Regards

**Pull request closed without merging**
