### PR TITLE
Update DigitalWifee

### PR DESCRIPTION
**Pull request by DigitalWifeNFTs**
I mint on a new site, that's why I need to add my new policy ID. Thank you.

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by DigitalWifeNFTs** [comment]
https://twitter.com/DigitalWifeNFTs/status/1488167696525058049

V V čet., 27. jan. 2022 ob 10:58 je oseba KaiNFT ***@***.***>
napisala:

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID on line 5 to your twitter.

**Comment by DigitalWifeNFTs** [comment]
Can you please remove old name: !DigitalWifee from visible list of
projects, because it is still visible, policyID is moved to !DigitalGirl

V V čet., 27. jan. 2022 ob 10:58 je oseba KaiNFT ***@***.***>
napisala:

**Pull request merged**
