### PR TITLE
Adding Charli3 Cuties PolicyID

### PR DESCRIPTION
**Pull request by codefly**
Adding Charlie3 Cuties Collection

Main sales website here: https://charli3.canucks-publishing.com

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, your project has forbidden characters in it. This means that you need to remove any special characters from your project name or commit names.

**Comment by codefly** [comment]
Interesting, because this was an already approved project, I'm just adding an additional PolicyID to it. 

Would you recommend creating a new project for the new series we're adding, or rename the Project (which I assume will have the effect of renaming the existing approved project in the frontend)?

**Comment by Guru-Dingus** [comment]
I’m just commenting on the code of this pull request . Won’t pass because
of the issues I pointed out. I would not delete any previous code submitted
and accepted, just amend the current request to allow it to pass. Don’t
delete anything on my advise only. Just wanted to help point out the issues
of this code and how I would fix it.

**Comment by KaiNFT** [comment]
Dear Contributor, 

This request will now be closed, make a new ticket with the following criteria; the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
