### PR TITLE
Added project CardaPoool and project PixyNFTs

### PR DESCRIPTION
**Pull request by d3r3k2010**
Added project CardaPoool and project PixyNFTs

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide proof with a website or social media so I can merge the pull request.

**Comment by d3r3k2010** [comment]
Hi, 

How I have to prove it?
Juat replying on this email is ok?

**Comment by d3r3k2010** [comment]
We have the policy ID on this link:
https://cardapool.com/nft-gratis/

**Comment by d3r3k2010** [comment]
We also put this links on websites, and we will be updating them as well on this repo.
[cardapool.com/policyID.json](url)
[pixynfts.art/policyID.json](url)

**Comment by d3r3k2010** [comment]
> Dear Contributor,
> 
> Please provide proof with a website or social media so I can merge the pull request.

cardapool.com/policyID.json
pixynfts.art/policyID.json

I added it, but it still not added wile merge looks done. I'm doing something wrong?
8 days ago json worked, I just added new project today and it seems to fail json checks but looks like merged is ok.

Any glue will be apreciated, thanks in advance

**Comment by d3r3k2010** [comment]
I'll redo

**Pull request closed without merging**
