### PR TITLE
Add Project ​Mid Way Dog

### PR DESCRIPTION
**Pull request by Oilkibonft**
This project. I created original from  lovely two dogs who stay with me. They are  feral dogs. I love and take care them and wish they happy. Dog is Man Best Friend.
 https://twitter.com/MidWayDog1

### CODE REVIEW

**Comment by MaxJewell** [comment]
The policies you have provided are not on the twitter or website. 
Would you be able to upload the policies onto either or give a link to the https://cnft.io/ website.

Thanks.

**Comment by Oilkibonft** [comment]
https://twitter.com/MidWayDog1/status/1445062280417144840?s=20
please check it out. i update policy id on twitter already.

**Comment by Oilkibonft** [comment]
please check it out. i update policy id on twitter already.
https://twitter.com/MidWayDog1/status/1445068941483667459?s=20

**Comment by Oilkibonft** [comment]
> The policies you have provided are not on the twitter or website. Would you be able to upload the policies onto either or give a link to the https://cnft.io/ website.
> 
> Thanks.

https://cnft.io/ website. Can i send on support? sorry, but i don't know how to give a link to website. Thank you.

**Pull request merged**
