### PR TITLE
Created Celebrity Punks

### PR DESCRIPTION
**Pull request by CelebrityPunks**
Celebrity Punks are hand drawn Fungible Tokens minted on the Cardano Blockchain inspired by the popularized punks 8-bit art. 

Twitter: https://twitter.com/CelebrtyPunks
Website: https://www.celebritypunks.art/
Discord: discord.gg/eVhugUtZ

### CODE REVIEW

**Comment by MaxJewell** [comment]
Would you be able to remove a comma on the end of the last tag and policy ID as it is incorrect. 
Can you let me know when you have done this and we continue.

Many thanks.

**Comment by CelebrityPunks** [comment]
Hello,

Thank you so much for taking my request.
I removed the commas from the last tag and policy ID. Please let me know if
there anything else you need.

**Comment by CelebrityPunks** [comment]
> Would you be able to remove a comma on the end of the last tag and policy ID as it is incorrect. Can you let me know when you have done this and we continue.
> 
> Many thanks.

Hello,

Your request has been fixed, can we please proceed now?

**Comment by CelebrityPunks** [comment]
Hello, I noticed you merged my pull request but i still can't find them verified. It still says Project unknown. Maybe there is something wrong? Shouldn't all those policy ID's appear under project Celebrity Punks? Thank you

**Comment by CelebrityPunks** [comment]
Hello, I noticed you merged my pull request but i still can't find them
verified. It still says Project unknown. Maybe there is something wrong?
Shouldn't all those policy ID's appear under project Celebrity Punks? Thank
you

**Pull request merged**
