### PR TITLE
HaiendoSlothClub

### PR DESCRIPTION
**Pull request by haiendosloth**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning,
File HaiendoSlothClub is not in projects directory!

**Comment by haiendosloth** [comment]
im doing this: 
fork -> fetch -> click project folder -> create new file -> adding code and commit new file -> Contribute and open pull request -> create pull request

**Comment by haiendosloth** [comment]
How do i remove old commits, if you look. One commit is not in the projects folder. but the new one is

**Comment by haiendosloth** [comment]
File: Create HaiendoSlothClub is in the projects folder

**Comment by MaxJewell** [comment]
You will need to make a new pull request.

**Pull request closed without merging**
