### PR TITLE
Create Policy Project RockstarNFTs

### PR DESCRIPTION
**Pull request by SynSixty**

### CODE REVIEW

**Comment by SynSixty** [comment]
Twitter: https://twitter.com/schizoidal

**Comment by SynSixty** [comment]
Updated Policy ID

**Comment by SynSixty** [comment]
Profile info updated

**Comment by SynSixty** [comment]
Policy contains a test NFT. Need to confirm the verification process working before commuting full website and resources to the project

**Comment by MaxJewell** [comment]
If you could make a tweet with the policy ID's on them that would be great.

Many thanks.

**Pull request closed without merging**
