### PR TITLE
(edited) Added Our New Artano Policies - Touréguide

### PR DESCRIPTION
**Pull request by withspaces**
Added new policies for withspaces, SmittyStudio and UGLYSTAR from the recent Artano drop. 
Also changed the title of "(2140)" to "(2140) by withspaces"

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by withspaces** [comment]
Yea sure! These pieces are listed on the Artanos official website. Would these links work? If you need to you can verify the policy themselves by the Mint Hashs listed in the info.

UGLYSTAR
https://artano.io/bazaar/nfts/4f87cf8e-1342-4b85-a76f-91c63b4c919c

withspaces
https://artano.io/bazaar/nfts/510f2a8a-5211-4698-bd2e-aa6152b20a00

SmittyStudio
https://artano.io/bazaar/nfts/1265cdba-932e-4843-8a2a-7ff5efee3cdd

**Comment by MaxJewell** [comment]
None of these links you have provide will not be sufficient as their Policy ID's do not match with any of the ones in your commit.
Please provide links with Policy ID's that are in the commit.

**Comment by withspaces** [comment]
These should be sufficient, you can locate the policy ID by checking the minting hash. Does this help? 
https://twitter.com/TYLRwithspaces/status/1474041841679048704?s=20

**Pull request merged**
