### PR TITLE
CryptoFruits

### PR DESCRIPTION
**Pull request by JHurles**
Initial Policy Numbers for the CryptoFruits NFT Series. More to be added as new ones created!

### CODE REVIEW

**Comment by Dean00K** [comment]
Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership. Either by way of tweeting your pull request from your project’s twitter account and providing a link here or providing a link to the project's website URL which contains Policy IDs within. Thank you.

**Comment by JHurles** [comment]
I'm new to this, so thanks for your patience. I can tweet it but I don't know how to? Do you need me to tweet every policy number? Or is there something here you need me to tweet? thanks

**Comment by Dean00K** [comment]
No need to tweet every policy number, Just tweet this webpage's link and tag us @cnft_io 
Then comment the link in here. Have you got a website or any pool.pm links i can check as well please?

**Comment by JHurles** [comment]
No site just yet, but these are the pool.pm links:

https://pool.pm/0794598abb56ba0a587b9a7c7978af148e52ac37fb479894ac990f04.CryptoFruitBananaPOPSilver
https://pool.pm/d5d13dd4dfb6faf6ead994ab8a27224e66d41a7ccd36ada9205fce81.CryptoFruitBananaPOPGold
https://pool.pm/59171494bd93476bd0ece1fc9ba18e79199c5778086a69864af92ffc.CryptoFruitBananaPOPXADABOY
https://pool.pm/5a72a4cbbf3432c48bec2901493791ce64a6f921d7dcc66e3b97dbe4.CryptoFruitEggplantPOPSilver
https://pool.pm/0485f571482bf8b804ee21ec88f72d4fddc9e71266642765ffe80d62.CryptoFruitEggplantPOPGold

I will tweet this convo too. I will have more Policys once new ones are minted, how will i add those?

**Comment by JHurles** [comment]
Hi,

This is the tweet!

https://twitter.com/cryptofruitsnft/status/1430092453940432897?s=21

**Comment by Dean00K** [comment]
To update new policy ID's you need to go into your file here in github, and fork again, and edit your original commit, then resubmit and pull request again for me to make those changes.

**Comment by Dean00K** [comment]
your file is invalid, use this tool to help you fix it up. https://jsonlint.com/

**Comment by JHurles** [comment]
Great tool, just made changes, all ok now?

**Comment by JHurles** [comment]
Great when will the yellow tick appear?

**Comment by Dean00K** [comment]
couple of minutes

**Comment by JHurles** [comment]
Hi @Dean00K I have now sent an update and new pull request, have I done it right? Thanks for all the help on this. I hadn’t put the full policy numbers in

**Pull request merged**
