### PR TITLE
Added Cardano Bytes

### PR DESCRIPTION
**Pull request by cardano-bytes**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by cardano-bytes** [comment]
Hi Max,

No worries, the Policy ID is located in our Twitter bio. Please see link below...

https://twitter.com/CardanoBytes

Many thanks!

Kind regards,

The Cardano Bytes Team!

This email and attached files are intended for the named addressee only. It contains potentially confidential, legally privileged and copyright protected information. Unless you are the named addressee (or authorised to receive for the addressee) you may not copy, use, or disclose it to anyone else. If you received it in error please notify the sender immediately and then delete it from your system.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by cardano-bytes** [comment]
> Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

Hi Tom, I’m not sure what you mean. This was setup as per the video provided on the CNFT.io website? Please clarify. Thanks.

**Pull request closed without merging**
