### PR TITLE
Feefifofum

### PR DESCRIPTION
**Pull request by Richienic**
https://twitter.com/Ric000000fffle/status/1478407896828243972?s=20
https://twitter.com/Ric000000fffle/status/1478407640292024320?s=20

### CODE REVIEW

**Comment by Richienic** [comment]
Happy New Year

**Comment by Richienic** [comment]
anybody home ?

**Comment by TomStray** [comment]
Dear Contributor, please remove the special characters from your project name and code. Also, please send another link to your twitter or website/CNFT.io/Pool.pm with your policy ID on line 5 on there.

**Comment by Richienic** [comment]
https://twitter.com/Ric000000fffle/status/1478407896828243972?s=20
https://twitter.com/Ric000000fffle/status/1478407640292024320?s=20

**Comment by Richienic** [comment]
bro.. correction done... pl check

**Comment by Richienic** [comment]
Hello bro

**Comment by Richienic** [comment]
OMG what is happening ? y make us w8 so long ?

**Comment by Richienic** [comment]
Tom.. why the validation is failed? what should i do now ?

**Pull request closed without merging**
