### PR TITLE
Cerate Mazzanti's NFT's

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
Hey, This is my 4 projects... I can't seem to get the pull request system so I'm committing it to the main branch... ?

### CODE REVIEW

**Comment by KaiNFT** [comment]
Hi Contributor,

Can you please provide evidence of the Policy ID via a website/social media so I can merge your pull request.

Thanks - Kai

**Comment by GabrielMazzanti** [comment]
Yes : Twitter @gabrielmazzant3, My personal asset wallet is : addr1qy9xgqaqkash3wj90ad26qfm8qy837m8f387rncx2d02hnmexu7umnn2eu26y0mqcrty2zrhsfx3kq4je0hpqskm2desy7te04

Gabriel.texier@yahoo.fr
gabriel texier (facebook) with piano cover on it

**Comment by GabrielMazzanti** [comment]
and gabriel.mazzanti.mineworld@gmail.com, WorldCoin.cardano@gmail.com and github personal gabrieltexier1997

**Comment by GabrielMazzanti** [comment]
I don't have any website. I am doing it the oldfashion way :)

**Comment by GabrielMazzanti** [comment]
thank you 
Gabriel

**Comment by GabrielMazzanti** [comment]
Sorry, also on discord I'm Gabriel Mazzanti Texier with a Vetruve Man

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by GabrielMazzanti** [comment]
Okay, Thanks. I did but it failed to validate while the new Mazzanti's
NFtit is a copy of the other one...

**Pull request closed without merging**
