### PR TITLE
create eeArt

### PR DESCRIPTION
**Pull request by florinel**
create eeArt collection

### CODE REVIEW

**Comment by CNFT-io** [comment]
Please share, your website, social media and ensure your policy IDs are published.

**Comment by CriptFLO** [comment]
Twitter account: https://twitter.com/EeaNft

**Comment by CriptFLO** [comment]
please ensure name of project is just eeA, the name of our artist.  Thank you

**Comment by florinel** [comment]
Closing this, new pull request will be submitted by CriptFLO

**Pull request closed without merging**
