### PR TITLE
Binarylotusart09

### PR DESCRIPTION
**Pull request by lotusart09**
Welcome to the binary world of lotus_art09, drawings made by lotus_art09, mangaka, pencil sketches, alcohol markers coloring, scanning, incrementing keywords.

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by lotusart09** [comment]
Good afternoon 
Excuse me i have no Twitter account ou website. What do tou need exactly ?
Thanks

Envoyé de mon iPhone

**Comment by KaiNFT** [comment]
We can't process your NFT without a website or social media with proof of policy ID listed.

**Comment by lotusart09** [comment]
I have a tiktok : 

https://vm.tiktok.com/ZML87Qh1q/


Is it ok ? 

Thanks 


Envoyé de mon iPhone

**Comment by KaiNFT** [comment]
No sorry we need a social media or a website that has your policy ID's directly posted.

**Comment by KaiNFT** [comment]
Closed due to inactivity

**Pull request closed without merging**
