### PR TITLE
Cardoonz Special

### PR DESCRIPTION
**Pull request by Cardoonz**
https://cardoonz.com

https://twitter.com/Cardoonz/status/1484108757693083648?s=20

https://discord.gg/Fd9Vk2xuBN

### CODE REVIEW

**Comment by Cardoonz** [comment]
Pls help with JSONs validation

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by Cardoonz** [comment]
The thing is that it shows me that JSON is Valid at  https://jsonlint.com/, pls re-check .

**Comment by KaiNFT** [comment]
It's an automated checker, "type should be array"

**Comment by Cardoonz** [comment]
File updated, all checks passed

**Pull request merged**
