### PR TITLE
Added Cardano Elite

### PR DESCRIPTION
**Pull request by Qasmi95**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Hello, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by Qasmi95** [comment]
I am just new to the NFT platform and I don't know what steps to follow as I just followed a video.

**Comment by Qasmi95** [comment]
> Hello, Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.
> 
> Many thanks.

**Comment by Qasmi95** [comment]
Hello,
Thank you for responding. I have only my twitter account: @Qasmi95. And the policy id for this NFT is :94f2efeaeb9d8e3eb4f8c321605db060ee770766f532639157c4490c

Thanks

**Pull request closed without merging**
