### PR TITLE
Create covid19

### PR DESCRIPTION
**Pull request by eezork**
https://twitter.com/Eezork06

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

Your social media is very new, do you have another form of social media or a website I can use to verify you?

**Comment by eezork** [comment]
Hello,

I could make a facebook page with my art? but i am verry new into this.
Just made a twitter acount

Op do 3 feb. 2022 11:06 schreef KaiNFT ***@***.***>:

**Comment by KaiNFT** [comment]
You need some sort of social media or a website with your Policy ID's posted on that advertises the NFT's.

**Comment by KaiNFT** [comment]
Closed due to inactivity

**Pull request closed without merging**
