### PR TITLE
Yummi Pool

### PR DESCRIPTION
**Pull request by EnactPoolDavid**
Hello I David

https://twitter.com/YummiUniverse

https://yummiuniverse.com/

https://discord.gg/yummiuniverse

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file format in order for me to merge the pull request.

**Comment by EnactPoolDavid** [comment]
Hey mate, sorry I'm not sure what that means to be honest, it looks alright
with me

Any tips?

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by EnactPoolDavid** [comment]
>

**Pull request closed without merging**
