### PR TITLE
Policy ID update

### PR DESCRIPTION
**Pull request by Huryashin**
New policy ID being added to the Ada Sharks pool
https://twitter.com/Ada_SharksCnft
Starting new Policy ID for Devi8t3d.
https://twitter.com/Devi8t3d_cnft

### CODE REVIEW

**Comment by Huryashin** [comment]
What conflicts are there? Not showing anything?

**Comment by Huryashin** [comment]
What's the issue or conflict?

**Comment by Huryashin** [comment]
What's the issue??

**Comment by joelclaudio** [comment]
It looks like you're trying to commit the same file that you already committed on another pull request:
https://github.com/Cardano-NFTs/policyIDs/blob/main/Ada%20Sharks

**Comment by Huryashin** [comment]
We are adding a new one too the existing ones.

**Comment by Huryashin** [comment]
be66a6f925b49d89a028c086d2b7180066125a223f2070defa3bf341

**Comment by joelclaudio** [comment]
It seems to me that you're adding a new policy ID to an already existent project, which should end in 3 policy IDs for the Ada Sharks, right?

What I would suggest is for you to merge your fork by pulling the new updated main of Cardano-NFTs/policyIDs, update your project file "Ada Sharks" with the added policy ID and do a new pull request.

The conflict is happening because you're trying to replace your "Ada Sharks" file that already exists in the main branch of Cardano-NFTs/policyIDs, like I said in a previous comment.

I am not the owner of the project, I am just giving my opinion as I've seen you struggle, so don't take my word as final. :)

**Comment by joelclaudio** [comment]
@Huryashin If what is intended is to have 3 policies, your final file should look like this:

{
    "project": "Ada Sharks",
    "policies": [
        "a787854eeea7bb900e58b4c299830ab3a2de1609af2b3a8dac77cb0b",
        "1ff52c88fdef75d25b967d03672be83d146cf479ad1c484c69810d43",
        "be66a6f925b49d89a028c086d2b7180066125a223f2070defa3bf341"
    ]
}

**Comment by Huryashin** [comment]
Ok thanks for the help!!!

**Comment by Huryashin** [comment]
Could you verify pleease today pretty please ☺️☺️

**Comment by Huryashin** [comment]
Please verify my new policy id ☺️☺️☺️

**Comment by Huryashin** [comment]
Todays the day I'm feeling lucky☺️

**Comment by Huryashin** [comment]
Today is the day☺️☺️☺️

**Review by Huryashin — COMMENTED** [review]
Could you please send the new policy through for Ada sharks

**Comment by Huryashin** [comment]
Could you send my pull request through please ☺️☺️

**Comment by Huryashin** [comment]
Please send it through please😁😁😁

**Comment by Huryashin** [comment]
Please verify new policy for Ada sharks

**Comment by Huryashin** [comment]
Today is the day😁

**Comment by Huryashin** [comment]
Please verify❤️❤️❤️

**Pull request closed without merging**
