### PR TITLE
added krypto_kush

### PR DESCRIPTION
**Pull request by Krypto-Kush**

### CODE REVIEW

**Comment by Krypto-Kush** [comment]
https://twitter.com/krypto_kush

**Comment by MaxJewell** [comment]
Would you be able to post Policy ID's on this account please.

Thanks

**Comment by Krypto-Kush** [comment]
I posted them on my Twitter like I was asked ???

**Comment by Krypto-Kush** [comment]
https://mobile.twitter.com/krypto_kush

**Pull request closed without merging**
