### PR TITLE
Ada Gang Hero

### PR DESCRIPTION
**Pull request by FuturisticCoins**
https://twitter.com/FuturisticCoins

https://drive.google.com/drive/u/0/folders/1AdkvRxf_EedlwdAqOx_IEgpyTcOh0plv

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 

The policy ID included in your file does not match with the policy ID listed on your social media/website.

**Comment by FuturisticCoins** [comment]
Hello

I am new to this but I am willing to learn. Can you explain to me how I can
fix this problem?
My work is authentic. I just do not understand how to properly list in
regards to the
policy id, social media, and website.

Best Regards,
John

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by MaxJewell** [comment]
Due to inactivity on this pull request we will have to close this request. 
Feel free to open a new request when you have gathered everything you need to be verified.

**Pull request closed without merging**
