### PR TITLE
Create AI Art

### PR DESCRIPTION
**Pull request by PaxRomanArt**
twitter.com/pax_art
https://linktr.ee/PaxRomanArt

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by PaxRomanArt** [comment]
moved to Project folder.  I hope this is okay

**Comment by KaiNFT** [comment]
Dear Contributor, 

According to the json validation, your file is still not registered in the Projects directory, please make necessary adjustments in order for me to resolve this or please attempt to re-submit the pull request.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
