### PR TITLE
Created NeverTrumper

### PR DESCRIPTION
**Pull request by 1jackyleung**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Hello, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by 1jackyleung** [comment]
> Hello, Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.
> 
> Many thanks.

Yes, my Twitter is: https://twitter.com/hanamichy

**Comment by MaxJewell** [comment]
I need the Policy ID's on the twitter account

**Comment by 1jackyleung** [comment]
> I need the Policy ID's on the twitter account

Yes just added now as a Tweet, this is my first time thanks for your patience in teaching me. https://twitter.com/hanamichy

**Pull request merged**
