### PR TITLE
Creating Mazzanti NFT

### PR DESCRIPTION
**Pull request by GabrielMazzanti**
Hey I cleaned up my old fork, to retry submitting this one

### CODE REVIEW

**Comment by GabrielMazzanti** [comment]
https://twitter.com/GabrielMazzant3

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by GabrielMazzanti** [comment]
I just did the pool request is pined on my twitter profile

**Comment by GabrielMazzanti** [comment]
pull

**Comment by GabrielMazzanti** [comment]
I can send an email with all my policy's gabriel.mazzanti.mineworld@gmail.com

**Comment by GabrielMazzanti** [comment]
> Dear Contributor,
> 
> Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

Just for you to receive my messages

**Pull request merged**
