### PR TITLE
Please create ClownApe

### PR DESCRIPTION
**Pull request by effincomputers**
Available for children's birthday parties, as long as they're not being held at a zoo, and stags!

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by effincomputers** [comment]
I'm not sure I understand why this has to be done, but here you go.

https://effincomputers.com/NFT-INFO/policy-IDs.html

**Comment by effincomputers** [comment]
https://twitter.com/TmachineNf/status/1480663332696772612?s=20

**Comment by effincomputers** [comment]
https://twitter.com/TmachineNf/status/1480663332696772612?s=20

**Comment by effincomputers** [comment]
Thank you!!

**Pull request merged**
