### PR TITLE
Added first NFT

### PR DESCRIPTION
**Pull request by MushroomManNFT**
Creating my first request for MushroomManNFT

### CODE REVIEW

**Comment by MushroomManNFT** [comment]
https://twitter.com/MushroomManNFT/status/1437038258039439363?s=20

**Comment by MaxJewell** [comment]
On line 3 of the new mushroom man request, can I just ask for you to add a space so it aligns correctly.

Many Thanks.

**Comment by MushroomManNFT** [comment]
I will do it right now.

**Comment by MaxJewell** [comment]
If you know how to do it on computer please do so and I will get back to you as soon as I can.

**Comment by MushroomManNFT** [comment]
I will complete when I get home from work. I apologize for the
inconvenience and I appreciate you reaching out.

**Pull request closed without merging**
