### PR TITLE
Added CardanoMonsters & Policies 1/2

### PR DESCRIPTION
**Pull request by CardanoMonsters**

### CODE REVIEW

**Comment by Dean00K** [comment]
Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership by way of tweeting your pull request from your project’s twitter account and provide the link here as a comment. Alternatively provide project website URL which contains Policy IDs within. Thank you.

**Comment by CardanoMonsters** [comment]
Validation URL: https://www.cardanomonsters.com/validate

**Comment by CardanoMonsters** [comment]
Thank you my friend!

**Comment by Dean00K** [comment]
sweet, taking a look now.

**Pull request merged**
