### PR TITLE
added projects cardapool an pixynfts

### PR DESCRIPTION
**Pull request by d3r3k2010**
added projects and websites links, also let them here:
https://cardapool.com/policyID.json
https://pixynfts.art/policyID.json

### CODE REVIEW

**Comment by AnOnlineGuy** [comment]
Can you add links to your social media accounts and also a tweet with you Policy IDs

**Comment by d3r3k2010** [comment]
> Can you add links to your social media accounts and also a tweet with you Policy IDs

Can not, because we dont use tweeter, just telegram. On README.md says "Alternatively... website"

**Important: You must show proof of your project by tweeting your pull request to your projects twitter and linking in your pull request Alternatively, provide adequate proof such as a direct link to project website with policies**

**Comment by AnOnlineGuy** [comment]
Then please provide your website. Having just telegram is not enough.

**Comment by d3r3k2010** [comment]
> Then please provide your website. Having just telegram is not enough.

I already did it.
Direct links to policyID
https://cardapool.com/policyID.json
https://pixynfts.art/policyID.json

Web links:
[](https://cardapool.com) or [](https://cardapool.com/nft-gratis/)
[](https://pixynfts.art) this one is in development

**Comment by HRumson** [comment]
Dear Contributor, please add your Policy IDs to your website.

**Comment by d3r3k2010** [comment]
> Dear Contributor, please add your Policy IDs to your website.

Seriously, they already are

**Comment by HRumson** [comment]
Dear Contributor, the Policy IDs from your website, and the code you provided, do not match, as seen in these screenshots. We cannot use your top two direct links in your screenshot, as they are just text files. 

Screenshot 2021-11-25 100930

Screenshot 2021-11-25 100807

**Comment by d3r3k2010** [comment]
As you see, you are looking for policyID from pixynfts and checking them to cardapool. 

Just check them on each website like project cardapool on website cardapool, and project pixynfts on website pixinfts and they will match

**Comment by TomStray** [comment]
Dear Contributor, we have found the policy IDs for project "Cardapool", however, we cannot use your text/JSON files as they could be created by anyone. Therefore, we will need your "PixyNFTs" website to be up and running before this can be merged. 

Alternatively, you could briefly put your "PixyNFT" policy IDs onto your "Cardapool" website or send another link to your twitter/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

**Comment by d3r3k2010** [comment]
> 

twitter.com/CNFT.io/Pool doesn't exists
imagen

I've post on twitter th policyID's for projects from pixynfts (I'm sorry if I done something wrong but I never used twitter before)
here is https://twitter.com/pixynfts/status/1463822830878048264

If you need anything more, just ask me to do it or chage it, thanks for your patience

**Comment by MaxJewell** [comment]
Please use the new JSON format in the Readme file on the home page.

**Comment by d3r3k2010** [comment]
Dears collaborators, stop messing with this, we have been for long to just verify it.

-JSON format is same as Readme file.
-Both have been checked with "Validate your code before requesting: https://jsonformatter.curiousconcept.com/#"
-You just asked me to validate the pixyNFTs on twitter and it's done. 
-Cardapool just was verified a few hours ago.

Why you close it??

**Pull request closed without merging**
