### PR TITLE
Update Crypto_Monstars

### PR DESCRIPTION
**Pull request by noem9studio**
[
  {
    "project": "Monstars_Club",
    "tags": [
        "Monstars_Club"
    ],
    "policies": [
      "4c7e60af227a133d27ebd9f974e39f7930ad95e1fce1eccaf6913c5b",
     
    ]
  }
]

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide proof of Policy ID via website or social media so I can merge the pull request.

**Comment by noem9studio** [comment]
We have the policy ID on our Discord channel: https://discord.com/channels/898144156692656179/902333919754596383

Let me know if that works, otherwise I will post it on our Twitter account.

Thanks!

**Comment by MaxJewell** [comment]
Please use the new JSON format in the Readme file on the home page.

**Comment by noem9studio** [comment]
https://twitter.com/Monstars_Club/status/1460662773692735491?s=20

**Pull request closed without merging**
