### PR TITLE
Update dystoblock policy

### PR DESCRIPTION
**Pull request by Dystoblock**
@CNFT-io
Update Drop 3 on CNFT

Thank you

### CODE REVIEW

**Comment by Dystoblock** [comment]
Sor

**Comment by CNFT-io** [comment]
DONE!

**Comment by Dystoblock** [comment]
Thank you

**Comment by Dystoblock** [comment]
Why can't see the yellow checkmark in my project, l doing something wrong?
Policy :
8dbbcc1c0c5c7af09dbe4f086ebb1d1df352e4c714c0c37928e4bb64", "ebddb983c4d8bd0e333662bb131309c8e77e15b834840c9c8d26a62a", "a54ff09b92097b3c262ba2a4f7c0fc12c9abd485fba9f041708af0e2", "ab942642d06451ed02864ca7e016e733062ae1f796b16b4dd20d79ea
Thx Bro !

**Pull request merged**
