### PR TITLE
Create WatercolorArts

### PR DESCRIPTION
**Pull request by kris-art-nft**
https://twitter.com/kris_art_nft
https://instagram.com/kris_art_nft/
https://www.youtube.com/user/krisCanDream

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by kris-art-nft** [comment]
oh i don have a tweeter account yet. ok ill make one

**Comment by kris-art-nft** [comment]
whoops wrong spelling of twitter.. it goes to show that i dont use it... lol

**Comment by kris-art-nft** [comment]
https://twitter.com/kris_art_nft
https://instagram.com/kris_art_nft/
https://www.youtube.com/user/krisCanDream

**Comment by MaxJewell** [comment]
Would you be able to add the policy ID's you want merged onto the twitter please.

**Comment by kris-art-nft** [comment]
oh do you mean add my policy ID in my twitter as a twit? or add it to the committed file like? 
"policies": [
      "59b9d8e605db2ad910b41f9ff941e893533669f1b9500624097d41a8",
      "bbccd630673198f7ac266bf09ed2b7ffee039f2ed6f1c3c65aae60d8"
    ]
    "twitter": "https://twitter.com/kris_art_nft" 
    
    i'm sorry i'm kinda new at this so i'm still learning stuff.

**Comment by kris-art-nft** [comment]
ah got it. will do.. oh btw do i need to create a new twitter account for a new project? or i can put multiple policy ID in the twitter bio for all projects

**Comment by kris-art-nft** [comment]
oh nvm i can only put 160 characters in the bio... so i just tweeted it.

**Pull request merged**
