### PR TITLE
Added Retro Relaxation-Moonlit Journey

### PR DESCRIPTION
**Pull request by Rich4rd1000**

### CODE REVIEW

**Comment by Rich4rd1000** [comment]
Twitter account with post:
https://twitter.com/RetroRelaxCNFT

**Comment by TomStray** [comment]
Dear Contributor, please remove the comma at the end of line 4.

**Comment by Rich4rd1000** [comment]
updated and removed the comma

**Comment by Rich4rd1000** [comment]
I have added the policy ID to my twitter profile here:
[https://twitter.com/RetroRelaxCNFT]

**Pull request merged**
