### PR TITLE
Added Ada-Monsterz

### PR DESCRIPTION
**Pull request by AdaMonsterz**

### CODE REVIEW

**Comment by itsmestale** [comment]
please read the readme and provide proof

**Comment by AdaMonsterz** [comment]
Hi Stale, 
I've added the Policy ID to the website: https://adamonsterz.com/buy-now 
and it's also on the FAQ section: https://adamonsterz.com/faq

Also linked to it on my twitter Bio: https://twitter.com/AdaMonsterz

Please let me know if there is anything else you need.

Thanks,
André 
Ada-Monsterz

**Comment by AdaMonsterz** [comment]
Hi Stale,
I've added the Policy ID to the website: https://adamonsterz.com/buy-now

and it's also on the FAQ section: https://adamonsterz.com/faq

Also, linked to it on my twitter Bio: https://twitter.com/AdaMonsterz

Please let me know if there is anything else you need.

Thanks,
André
Ada-Monsterz

________________________________

**Comment by AdaMonsterz** [comment]
Thank you so much.

Got the check mark and project name on my listings.

Best,
André
________________________________

**Pull request merged**
