### PR TITLE
Add additional policy id - StudioKfez

### PR DESCRIPTION
**Pull request by studiokfez**
add new policy id.

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool.pm with your policy ID(s) on there so that I can verify.

**Comment by studiokfez** [comment]
Thanks!

https://twitter.com/Studio_Kfez/status/1486053917842677764?t=Xjkegp4lTWBGAPqu4_IfOA&s=19


Let me know if that works to verify this policy id!

Kfez

**Comment by TomStray** [comment]
Dear Contributor, please add all of your policy IDs to your twitter so that I can verify.

**Comment by studiokfez** [comment]
there is not enough room in my bio but here is a tweet:
https://twitter.com/Studio_Kfez/status/1488557424445472768

thanks!

Kfez

**Pull request merged**
