### PR TITLE
Updated with new policy id's

### PR DESCRIPTION
**Pull request by bevanamit**
Updated with new policy id's

### CODE REVIEW

**Comment by bevanamit** [comment]
www.twitter.com/itsmes_art

**Comment by bevanamit** [comment]
Updated with new policy id's

www.twitter.com/itsmes_art

**Comment by KaiNFT** [comment]
Dear Contributor,

Can you provide another form of evidence of policy ID due to the fact that your twitter is very new, you can submit a website if applicable.

**Comment by bevanamit** [comment]
Sorry I do not own a website. My personal twitter id is
www.twitter.com/bevanamit

**Comment by bevanamit** [comment]
Updated project name

www.twitter.com/itsmes_art

**Comment by bevanamit** [comment]
Hi Team,

please check I have updated my @bevanamit twitter account (personal one)
with the pull request and the policy id's.

Regards
Amit A Bevinakatti

**Comment by bevanamit** [comment]
Hi Team, please check on this.
I have updated my @bevanamit twitter account (personal one)
with the pull request and the policy id's.

thanks
Amit

**Pull request merged**
