### PR TITLE
Kripz

### PR DESCRIPTION
**Pull request by CardanoFreaks**
Twitter: https://twitter.com/CardanoFreaks
webpage: https://cardanofreaks.art/kripy-kripz/

### CODE REVIEW

**Comment by CardanoFreaks** [comment]
Wohoho :)

**Comment by TomStray** [comment]
Dear Contributor, please add your policy ID to your twitter or website.

**Comment by MaxJewell** [comment]
Please make the change by adding the policy ID into your website or twitter so we can merge your request.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
