### PR TITLE
Create Mutant Corgi Club

### PR DESCRIPTION
**Pull request by Rmdougal**
My art: 0144f5edce7424a1a7866f5b2e306280949fd31372c660142d833ec9

### CODE REVIEW

**Comment by Rmdougal** [comment]
Website: [](https://www.ryandougal.com/)

**Comment by Rmdougal** [comment]
https://www.ryandougal.com/

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request.

**Comment by TomStray** [comment]
Dear Contributor, please click at the start of line 5, just before the first speech mark, and press the Tab key twice to indent this line twice.

**Comment by Rmdougal** [comment]
> Dear Contributor, please click at the start of line 5, just before the first speech mark, and press the Tab key twice to indent this line twice.

I have made the adjustment and also changed the project name to 'Mutant Corgi Club'. Thank you for helping me.

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request.

**Comment by Rmdougal** [comment]
[{
	"project": "Mutant Corgi Club",
	"policies": [
		"0144f5edce7424a1a7866f5b2e306280949fd31372c660142d833ec9"
	]
}]

**Comment by KaiNFT** [comment]
Dear Contributor,

Please run your file through a JSON validator in order to find the specific issue.

**Pull request closed without merging**
