### PR TITLE
Create Corn Gang by Corn 'n Friends

### PR DESCRIPTION
**Pull request by Corn-n-Friends**
Resubmitted :)  Proof of project ownership posted on https://www.twitter.com/cornandfriends

### CODE REVIEW

**Comment by Corn-n-Friends** [comment]
More direct link to proof --> https://twitter.com/CornAndFriends/status/1457773964332130304

**Comment by MaxJewell** [comment]
The Policy ID in the commit is not the same as what is in the tweet.

Would you be able to make the change and get back to me.

Thanks

**Comment by Corn-n-Friends** [comment]
Yeah would that be for both the commits?


This one below is for the Corn Gang by Corn 'n Friends project

https://twitter.com/CornAndFriends/status/1457773964332130304


I commented on the same thread just now to show the commit for the Corn 'n Friends - Logo Airdrop (I can make this a fresh post as well if you'd like)

https://twitter.com/CornAndFriends/status/1458913716783628302



________________________________

**Comment by Corn-n-Friends** [comment]
Checking in :)

**Comment by KaiNFT** [comment]
Dear Contributor,
 
Thank you for your patience, your request has now been merged.

**Pull request merged**
