### PR TITLE
NFT Wonderland

### PR DESCRIPTION
**Pull request by MalSLim8**
[
  {
    "project": "Wonderland",
    "policies": [
        "8ae8e8661af7bbb2e45239c45ceae67d16164837de9ed1a4fe535a86",
        "3bbfc66ad107cf655b31fe94f79e8f91385538f049198f9b60188629",
        "bb1047bae40e1225030ecfb646654ff793e97b4013c27e36da1fad1c",
        "c6b2c59f129acb4da13a1301901b62edafda45fe035746f64a7a5e67",
        "a163471f7d3d488854520b09f52a5d2fdfcc15a7f8199df8d52dd020",
        "db270501988c1a1729f307955f27efdee460a807e7fd136d1fa116cc"
    ]
  }
]

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please remove the duplicate lines in your file in order for me to merge the pull request.

**Comment by MalSLim8** [comment]
Sorry, new to this. Do you mean the gaps in the file or should there be only one policy ID?

**Comment by MalSLim8** [comment]
I can see in the failed pull request details that there were 2 identical line but this did not show up in the window above. I have deleted and redone all 6 lines of policy ID's. Hope this works.

**Comment by MalSLim8** [comment]
Twitter @mal_slim

**Comment by MalSLim8** [comment]
Ran it through the JSON formatter

**Pull request closed without merging**
