### PR TITLE
CelDivision Project Created

### PR DESCRIPTION
**Pull request by CelDivision**
and one policy removed from other project

### CODE REVIEW

**Comment by CelDivision** [comment]
link to the tweet https://twitter.com/pew36/status/1440652844462346255?s=20
link to my twitter account https://twitter.com/pew36
link to my instagram https://www.instagram.com/celdivision/?hl=en

**Comment by CelDivision** [comment]
i removed my NFT policy from the ADALEGO project because it belongs to the CelDivision Project.

**Comment by CelDivision** [comment]
Hey folks @MaxJewell  @nicolasayotte  @TomStray ,
Would you mind verifying my project please and removing the policy from someone else's project. no idea how that happened.

Twitter Pull Request Post 1 : https://twitter.com/pew36/status/1440679577559310342?s=20


Please do not hesitate to let me know what I am lacking and thanks for your time much love CelDivision

**Comment by CelDivision** [comment]
AMAAAAZING! thanks @CNFT-io  .....any idea how long it takes to update the marketplace listing to the correct project? im so happy right now

**Comment by CNFT-io** [comment]
30 mins or so

**Pull request merged**
