### PR TITLE
Create Digikin

### PR DESCRIPTION
**Pull request by CryptoDrag0n**
Individually created, uniquely drawn, progressive digital art images.

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request. Also remove the "," on line 8.

**Review by CryptoDrag0n — COMMENTED** [review]
https://twitter.com/CryptoD97050898/status/1479393729886760966?s=20

**Comment by CryptoDrag0n** [comment]
I have no idea WTH to do about this.  I am no programmer lol

***@***.***

But here is tweet

https://twitter.com/CryptoD97050898/status/1479393729886760966?s=20

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by CryptoDrag0n** [comment]
https://twitter.com/CrypticDragon/status/1479396108979818497?s=20

Opps sent from wrong twitter – here is new tweet

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by KaiNFT** [comment]
Can you run your file through a JSON validator to fix the issues please

**Comment by CryptoDrag0n** [comment]
How do I do that exactly? Like I didn't see that in the youtube I was watching to get this far lol.

**Comment by KaiNFT** [comment]
https://jsonlint.com/

Paste your file code into this and it will tell you what to fix

**Comment by CryptoDrag0n** [comment]
I think I got it! Am I all good?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by CryptoDrag0n** [comment]
WOOT!!! Thanks soo much! Sorry I was such a pain.! Happy New Year!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Pull request merged**
