### PR TITLE
Added "ThreadPunks Halloween Drop"

### PR DESCRIPTION
**Pull request by Zerpimikey**
A mint of 50 tokens with special Halloween designs made and given as a gift to the most supporting members of our community

### CODE REVIEW

**Review by Zerpimikey — COMMENTED** [review]
Just copypasted formatted JSON Data, my apologies, didn't know that step

**Comment by Zerpimikey** [comment]
GD everyone

**Comment by tbd22** [comment]
> Just copypasted formatted JSON Data, my apologies, didn't know that step

how did you do that?????????

**Comment by tbd22** [comment]
> > > Just copypasted formatted JSON Data, my apologies, didn't know that step
> > 
> > 
> > how did you do that?????????
> 
> hey, there's this page where u can check it out:
> 
> https://jsonformatter.curiousconcept.com/#
> 
> Hope that helps! Cheers!

thank you

**Review by Zerpimikey — COMMENTED** [review]
Hi! I see we haven't been verified yet, JSON was showing as verified as of yesterday

Can anybody help?

**Review by Zerpimikey — COMMENTED** [review]
I see this was properly verified but it shows otherwise now?

Any help will be much appreciated! GD everyone

**Pull request closed without merging**
