### PR TITLE
Added Stamps of Cardano

### PR DESCRIPTION
**Pull request by StampsOfCardano**
Added Policy ID for Stamps of Cardano (www.StampsOfCardano.io) Series One. Twitter: @StampsOfCardano.

Proof of PolicyID for Series One can be found on our website: https://www.stampsofcardano.io/seriesone

### CODE REVIEW

**Comment by StampsOfCardano** [comment]
Hi just wanted to make sure we'd done this correctly?

**Comment by StampsOfCardano** [comment]
Add Stamps of Cardano Series One
Twitter : https://twitter.com/StampsOfCardano
Policy ID tweet : https://twitter.com/StampsOfCardano/status/1467147706615443458
The project website : https://www.stampsofcardano.io

Thanks and look forward to hearing from you

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by StampsOfCardano** [comment]
> Dear Contributor,
> 
> Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

Hi , sorry I'm not quite sure what you mean. Are you able to offer more details please?

**Comment by StampsOfCardano** [comment]
> Dear Contributor,
> 
> Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

Sorry, cancel what I wrote above. Believe I've now done this!

**Comment by StampsOfCardano** [comment]
Hey

Think this is sorted now. Thanks for that and sorry for the mistake.

Cheers 

Robbie

**Comment by TomStray** [comment]
Dear Contributor, in order to put the pull request in the 'projects' directory, you will need to open a new pull request.

**Comment by StampsOfCardano** [comment]
Hi Tom

Think that’s it done now. Sorry for the mistake!

https://github.com/Cardano-NFTs/policyIDs/pull/4660

All the best

Robbie

**Pull request closed without merging**
