### PR TITLE
Wonderland

### PR DESCRIPTION
**Pull request by MalSLim8**
[
{
"project": "Wonderland",
"policies": [
"8ae8e8661af7bbb2e45239c45ceae67d16164837de9ed1a4fe535a86",
"3bbfc66ad107cf655b31fe94f79e8f91385538f049198f9b60188629",
"bb1047bae40e1225030ecfb646654ff793e97b4013c27e36da1fad1c",
"c6b2c59f129acb4da13a1301901b62edafda45fe035746f64a7a5e67",
"a163471f7d3d488854520b09f52a5d2fdfcc15a7f8199df8d52dd020",
"db270501988c1a1729f307955f27efdee460a807e7fd136d1fa116cc"
]
}
]

### CODE REVIEW

**Comment by MalSLim8** [comment]
Twitter @mal_slim

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by MalSLim8** [comment]
> Dear Contributor,
> 
> Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

Hi and thanks for the feedback. I have run the above file through the json validator and it shows that it is a valid json file. Could it be to do with the original file that had duplicate lines?

**Comment by MalSLim8** [comment]
> > Dear Contributor,
> > Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/
> 
> Hi and thanks for the feedback. I have run the above file through the json validator and it shows that it is a valid json file. Could it be to do with the original file that had duplicate lines?

I have tried to follow the validation run and the only thing that i can see a possible name validation fail? Should i close the pull request and delete the file completely?

**Comment by MalSLim8** [comment]
Hi and thanks for the feedback. I have run the file through a json validator and it shows as a valid json file. I tried to follow the validation run and the only thing that i can see is a possible name conflict. I did edit the name after creating the pull request. Should I delete everything and start again? Cheers, Mal.

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by MalSLim8** [comment]
tried to delete everything but no luck. if you can please

**Comment by TomStray** [comment]
Dear Contributor, please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
