### PR TITLE
Create Cardaniart

### PR DESCRIPTION
**Pull request by Audiemar**
Various animated art. Hybrid hand drawn on paper brought it to bring to life.

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website also make the correct adjustments to the JSON file format in order for me to merge the pull request.

**Comment by Audiemar** [comment]
> Dear Contributor,
> 
> Please provide evidence of your policy ID via social media or a website also make the correct adjustments to the JSON file format in order for me to merge the pull request.

I have posted on my Twitter. 
Thanks
https://twitter.com/audmaphone/status/1466434346072563716?s=20

**Comment by Audiemar** [comment]
> > Dear Contributor,
> > Please provide evidence of your policy ID via social media or a website also make the correct adjustments to the JSON file format in order for me to merge the pull request.
> 
> I have posted on my Twitter. Thanks https://twitter.com/audmaphone/status/1466434346072563716?s=20

Also I have been banging my head trying to figure out the issue and sadly I can not. I have tried to do this before and got same issue I wish I know where to look to resolve.

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by Audiemar** [comment]
> Dear Contributor,
> 
> Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

Not sure if I did it right but created the project

**Comment by KaiNFT** [comment]
Dear Contributor, 

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Pull request closed without merging**
