### PR TITLE
Upgrades

### PR DESCRIPTION
**Pull request by declouxaproductions**
Hey guys hope its okay I add some files as I go ! cheers

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool.pm with your policy IDs on there so that I can verify.

**Comment by declouxaproductions** [comment]
I have tweeted ! thank you <3

**Comment by declouxaproductions** [comment]
my twitter.com/aaron_decloux has the policy ids pinned as my tweet !

**Comment by declouxaproductions** [comment]
twitter.com/aaron_decloux for links on pinned

**Comment by declouxaproductions** [comment]
Hello ! any chance you can help me update my git hub ? I have submitted the
pull request ( I think ) and am just trying to update some files ! Thanks
<3

**Comment by declouxaproductions** [comment]
Hey ! Any chance you can update my policy when you have some time. Also if
you send me your ada handle Id love to tip you ! I may need your services
in the future ! Hehe. Thx

Declouxa policy

**Pull request merged**
