### PR TITLE
Adding CardanoKitchen 

### PR DESCRIPTION
**Pull request by electromaniac0**
want to add our Policy for our new project Cardanokitchen.io which will be released October and our Satire-Project DefinietlyNotACNFTProject which will feature different CNFT-Projects in an persiflage

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please can you put the policy ID on your website or twitter so that I can verify.

**Comment by electromaniac0** [comment]
Hello,
sorry for my late answer.
Unfortunately i think we have to change the pull request.

You can delete "definetly  not a cnft project" . It was overrun by another
similar project. We wont carry on with this.

Our mayor focus is on CardanoKitchen.

But in the meantime we changed our publisher for cardano kitchen and so we
will also change our policy ID.

We are now going with buffybot as publisher and they gonna mint a new
policy for us.
I think they are well known in the cnft scene.
We will start minting promos with the new policyid on the 30th of
september.
Maybe you can arrange that we get a fast verification process for
cardanokitchen on this day because we will be dropping our NFTs at 2nd of
October.
I would really appreciate it when we could be verified at the drop date.

We already got nearly 700 followers on twitter, trying to ramp up marketing
and activity in discord as well.
We are have submitted our drop date already to cnft.social, cnftcalendar,
wencnft.
We will start advertising on cnftanalytics with 28th of september.

Check out:
Http://cardanokitchen.io
Http://twitter.con/CardanoKitchen

Short Description:
You pulled Bit after Bit, you caught sharks in spacesuits, you traded
Kidz-Cards on the cnft market but all this activity makes you hungry?

Introducing World’s first edible NFT… Well, at least kinda.
Description:

5000 juicy ingredients (incl 100 for promotion purposes), based on 45
different, self designed ingredients. from common food like potatoes to
more rare ones, like a delicious steak. With a bit luck, you will pull one
of our super rare ingredients, like beluga caviar or truffles. And there
are even rarer ones

Phase 2:
You will be able to “cook”/burn your ingredients when you got the recipe to
make a delicious dish!
This gonna mix up the rarity significantly!



TomStray ***@***.***> schrieb am Di., 21. Sep. 2021, 12:05:

**Review by electromaniac0 — COMMENTED** [review]
changed policy for cardanokitchen

**Comment by electromaniac0** [comment]
> Dear Contributor, please can you put the policy ID on your website or twitter so that I can verify.

Could you please verify us we are dropping at 2nd of October with buffbot
https://cardanokitchen.io/
policyid: 70ab22ae70717c90079e6ba9c4a9f23eecc800c4abcc306b742432f8

**Pull request merged**
