### PR TITLE
Create Little Super Heros

### PR DESCRIPTION
**Pull request by Franbajo**

### CODE REVIEW

**Comment by Franbajo** [comment]
https://twitter.com/magicalcrow01/status/1508108368967344131

**Comment by Franbajo** [comment]
https://twitter.com/magicalcrow01/status/1508108368967344131

**Comment by Franbajo** [comment]
https://twitter.com/magicalcrow01/status/1508108368967344131

**Comment by KaiNFT** [comment]
Dear Contributor,
  
This request will now be closed, make a new ticket with the following criteria; the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
