### PR TITLE
CardanoSesang

### PR DESCRIPTION
**Pull request by CardanoSesang**
twitter.com/CardanoSesang/

twitter.com/CardanoSesang/status/1466119749826457603

https://www.cardanosesang.com/

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request.

**Comment by CardanoSesang** [comment]
Hi Kai,

What kind of adjustments can I do?  I am not familiar with Json.  I am a
designer/illustrator, not a coder. 😥

Would you please help me with this?  Thank you so much.

**Comment by KaiNFT** [comment]
"SyntaxErrorUnexpected token “ in JSON at position 21"

**Comment by CardanoSesang** [comment]
I am so sorry.  I really don't understand this.  I basically copied and
pasted from the READ file and added a project name "CardanoSesang" and the
policy IDs.  Where dan I find position 21?

I apologize for my ignorance.  Thanks.

**Comment by TomStray** [comment]
Dear Contributor, on line 3, please make sure you have two of the same speech marks around CardanoSesang. For example: "CardanoSesang".

**Comment by CardanoSesang** [comment]
> Dear Contributor, on line 3, please make sure you have two of the same speech marks around CardanoSesang. For example: "CardanoSesang".

I just copied and pasted "CardanoSesang".  Fingers crossed.  Thank you so much.

**Pull request merged**
