### PR TITLE
Added CryptoMerman

### PR DESCRIPTION
**Pull request by CryptoMerman**

### CODE REVIEW

**Comment by MaxJewell** [comment]
This is a good start.
What I will need you to do is to give me a link to a twitter/webpage with the Policy ID's on them to verify your identity.

Many thanks.

**Comment by CryptoMerman** [comment]
Hi yes my policy id is on my website cryptomerman.com

My policy I am minting everything under now is

dc689521df2e721f4828d8212e98745107456664c718d7a93ee17e4a


I’ve been minting under this one policy ID now-  NFT maker.I’m minted a
couple under different policy numbers. I minted a couple under the policy I
submitted on the pull request - did you need those also?

**Comment by MaxJewell** [comment]
The policy ID's you have provided are not on the website. Would you be able to add them in and we can put you through.

Many thanks.

**Comment by CryptoMerman** [comment]
the policy ID is in this link : https://www.cryptomerman.com/copy-of-about

but are you asking me to add the one policy ID i am minting under to the pulll request or just add it to the website? 

The current policy I am minting under that I am trying to get verified is : dc689521df2e721f4828d8212e98745107456664c718d7a93ee17e4a

Also if you click on the images in this link : https://www.cryptomerman.com/home

You will see that those match with the policy number above.

**Pull request closed without merging**
