### PR TITLE
Added GenerativeDrop

### PR DESCRIPTION
**Pull request by FullmetalAlgorist**
My first NFTs!

### CODE REVIEW

**Comment by FullmetalAlgorist** [comment]
https://twitter.com/fullmetAlgorist
https://mariah.tech/shadertest/
https://www.instagram.com/fullmetalalgorist/

**Comment by TomStray** [comment]
Dear Contributor, please add the policy IDs you have on lines 7 and 13 to your twitter or Pool.pm.

**Comment by FullmetalAlgorist** [comment]
https://twitter.com/fullmetAlgorist/status/1455581622535741441?s=20

**Comment by FullmetalAlgorist** [comment]
Done! Yeah! Thanks so much!
https://twitter.com/fullmetAlgorist/status/1455581622535741441?s=20

**Pull request merged**
