### PR TITLE
Update CardanoKitchen with new Policy for Dishes

### PR DESCRIPTION
**Pull request by electromaniac0**
Updated CardanoKitchen with new policy for dishes

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool.pm with your policy ID(s) on there so that I can verify.

**Comment by KaiNFT** [comment]
Closed due to inactivity.

**Comment by electromaniac0** [comment]
Argh sorry missed this can we reopen it?

KaiNFT ***@***.***> schrieb am Mo., 17. Jän. 2022, 11:09:

**Comment by electromaniac0** [comment]
Hello @KaiNFT 
didnt expected that we have to send it again as we are already verified with our first collection but here you are

our homepage https://cardanokitchen.io
our twitter https://twitter.com/cardanokitchen

**Pull request closed without merging**
