### PR TITLE
Added ProjectIsekai

### PR DESCRIPTION
**Pull request by LordPanda10**
Project: Slime Research and Project: ADA Item Shoppe

### CODE REVIEW

**Comment by LordPanda10** [comment]
https://twitter.com/LordPanda24

**Comment by LordPanda10** [comment]
Idk if CNFT cares about the extensive variations I went with to reserve the tags Slime Research, Project Isekai and ADA Item Shoppe but if it causes any issues let me know.

I don't plan on minting the ADA Item Shoppe nft's until I've got my website up and running.

**Comment by LordPanda10** [comment]
Mental list to self (Just so I can keep myself on track)

- [ Get Projects Verified] 

- [Release next round of slime policies while finishing site ] 

- [Work on ADA Item Shoppe policies ]

**Comment by TomStray** [comment]
Dear Contributor, please use the new JSON format in the Readme file on the home page.

**Comment by LordPanda10** [comment]
Hello, not really sure why you closed my pull request since it's not letting me edit the json now.

And I am unable to find the "Home Page" that has the readme file you mentioned. I used this info here: https://support.cnft.io/article/verify-your-project


And I saw others using the same format and their PR went through. Do you think I just need to remove the majority of tags? If so I can once you re-open the pull request. Thank you

**Comment by LordPanda10** [comment]
If I need to open a new pull request and remove the tag format completely I can, but I need some confirmation from you before I continue just to cause less issues.

**Pull request closed without merging**
