### PR TITLE
Create Crypto Bowls

### PR DESCRIPTION
**Pull request by CryptoBowls**
Crypto Bowls Season 1

Crypto Bowls tells the story of how after a mysterious freakish accident. One which fused regular people, animals, or other unidentified species with their cereal bowl. Combining Digital Art with Real life, we live their adventures through this NFT.

### CODE REVIEW

**Comment by CryptoBowls** [comment]
Hello, We are launching today. Here is a picture of the Policy ID on a test
mint.

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

**Comment by CryptoBowls** [comment]
cryptobowls.net - Minting <https://www.cryptobowls.net/minting>

**Comment by CryptoBowls** [comment]
Hello, if I need to add a new policy ID would I need to do the Github again?

**Comment by CryptoBowls** [comment]
Hello, it says closed but my project is still not verified. Help

**Pull request closed without merging**
