### PR TITLE
Please update FatDragons policy JSON

### PR DESCRIPTION
**Pull request by jleveille1337**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by KaiNFT** [comment]
Dear Contributor,

Thank you for your patience and your request has been merged.

**Comment by jleveille1337** [comment]
> 
> 
> Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.
> 
> Many thanks.

@MaxJewell 
Kimberly has put this page up on her website: https://www.drawnbykim.com/nft-projects
It contains the policyid that matches what I put into github here.  It also includes some artwork samples.

**Comment by jleveille1337** [comment]
Yellow check mark achieved!  Thank you!

**Pull request merged**
