### PR TITLE
Added Project Absolem

### PR DESCRIPTION
**Pull request by Makishima09**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Could we have a link to a twitter or website with the Policy ID's on them.

Thanks.

**Comment by Makishima09** [comment]
Yes, of course
Here the link:
https://cnft.io/token.php?id=6137cd46fae18a4cbc8e0863

Thanks!

**Comment by MaxJewell** [comment]
Have we got a twitter link to verify your identity?

Thanks.

**Comment by Makishima09** [comment]
Sure
https://twitter.com/AbsolemCNFT

Thank you

**Pull request merged**
