### PR TITLE
Kro0ozty

### PR DESCRIPTION
**Pull request by kro0ozty**
First project based on Marseille Tarot 10 versions of each deck, each deck containing 22 different cards with 666 of each card available. Other unrelated personal NFT art works also available in last policy id.

### CODE REVIEW

**Comment by kro0ozty** [comment]
https://twitter.com/kro0ozty?s=09

**Comment by kro0ozty** [comment]
https://pool.pm/addr1q9r2vnshgh3cv7f759njg2v0cw0jmtzz5z5ledp0dzcjxvagrzkmavhxppjsq6wejqn6emnxfnn35sn9ttp7qaygh36q4333ul/aafd0fd4

**Comment by kro0ozty** [comment]
You can contact me at donkrozty@gmail.com

**Comment by kro0ozty** [comment]
Changed name as tokens were not nft but rather fungible due to the amount of them.

**Comment by kro0ozty** [comment]
Is there a way to change the project name as well as adding additional policy IDs? Or should I start from scratch?

**Comment by TomStray** [comment]
Dear Contributor, please add commas to the end of lines 4 and 5. As well as this, please put your policy IDs on your twitter so that I can verify.

**Comment by kro0ozty** [comment]
Policies have been posted on Twitter as well.

**Comment by kro0ozty** [comment]
My artano artamint NFTs are showing on cnft as skyline project which they are not. Let me know if I should remove that policy id. I don't really mind.

**Pull request merged**
