### PR TITLE
Added 3 tokens

### PR DESCRIPTION
**Pull request by AdirondackDoc**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Please could you leave a link to a twitter/webpage with the policy ID's.

**Comment by AdirondackDoc** [comment]
Thanks for the reply! Hopefully these links suffice. The policy scripts
have been saved on pool.pm and can be viewed below. If not please let me
know what else you might need. I can send info from cardanoscan if need be.
Thanks!

1.
https://pool.pm/83096ed231a4dc54b4e871758818ba12d214ad6ede5feff858604685.SMALLDBRO

2.
https://pool.pm/d5247f55e9095a2c9e6baa3f5a90acac76aa0f513d1ba66c70f7db7e.BIGDBRO

3.
https://pool.pm/6bedcddc92bc1ef9f056c36695d510105d6cfbe87cfe63312882d79c.HUGEDBRO

**Comment by AdirondackDoc** [comment]
Awesome, thanks! How long do you think it will take for them to be verified
on cnft.io?

Thanks greatly!

**Comment by AdirondackDoc** [comment]
Boom took an hour but they are verified now. Awesome. Thanks man. Can't
wait to see you make the youtube rounds. Cardano live. Cardano with paul.
Karen. Etc

Take care and let me know if you're hiring a semi technical person for a
non dev position haha.

Best

Mike

**Pull request merged**
