### PR TITLE
cNFT Goon Squad

### PR DESCRIPTION
**Pull request by Shortsyd**
Each of the policies can be verified utilizing the search bar at the original minting website: https://cardano-tools.io/latest

For convenience, here is a link for each search:
https://cardano-tools.io/latest?q=b3e0970dc00bc8c646b060d24dfa6e718aeab1d7df1d57c4e155f29a
https://cardano-tools.io/latest?q=84ee25d3c07b6acbcb8fe9bf27e75e409d74077979eb381229a1b8f5
https://cardano-tools.io/latest?q=6d1b50a749bd91534dd644fd2909637fbc0bc7279a4f0cc7a78de779
https://cardano-tools.io/latest?q=2f15fe11cc14e6013e1cd74d816e4ed60b6de428106a17e452bbefd9

### CODE REVIEW

**Review by Shortsyd — COMMENTED** [review]
Updated name and policies.  The pull request contained the links to verify the mints under each policy and that project name.

**Review by Shortsyd — COMMENTED** [review]
Can locate at https://cardano-tools.io/latest?q=1b1287109423ad1c0beab5acda1983c529cdd10925b4ff1877adb03b

**Comment by MaxJewell** [comment]
‘Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information. ’

**Comment by Shortsyd** [comment]
I am really unfamiliar with GitHub.  I tried watching the Stale video and it assumes someone has at least rudimentary knowledge.  Is there a step-by-step tutorial?

Thanks!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Pull request closed without merging**
