### PR TITLE
NinjaBoyz

### PR DESCRIPTION
**Pull request by NinjaBoy2021**
Create NinjaBoyz CNFT

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy IDs on there so that I can verify. Also, please click on line 6 just before the speech mark and press the Tab key to indent it once. As well as this, please remove the comma from the end of line 20.

**Comment by NinjaBoy2021** [comment]
https://cnft.io/token.php?id=615c8994864c1506ad75a170

**Comment by NinjaBoy2021** [comment]
https://cnft.io/token.php?id=615c8994864c1506ad75a170

**Comment by NinjaBoy2021** [comment]
https://twitter.com/NinjaBoyzNFT/status/1445442089324527617

**Comment by NinjaBoy2021** [comment]
https://twitter.com/NinjaBoyzNFT/status/1445442089324527617

**Pull request merged**
