### PR TITLE
Update Cardano Dragonz Collection

### PR DESCRIPTION
**Pull request by Necromancerx**
Additional collection added

Tweet: https://twitter.com/CardanoDragonz/status/1468897441311490048
Discord: https://discord.com/channels/889690000562745415/894323260706132029/901157307671531602
Website: Soon

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by Necromancerx** [comment]
We will post it on Twitter later and on the Website soon. In the meantime, this is our policy-id on discord: https://discord.com/channels/889690000562745415/894323260706132029/901157307671531602

**Comment by MaxJewell** [comment]
None of the policy ID's you are trying to merge are in the discord. Would you be able to add them to the discord chat please.

**Comment by Necromancerx** [comment]
It's on the #📌policy-id channel

https://discord.com/channels/889690000562745415/894323260706132029/901157307671531602

image

**Comment by Necromancerx** [comment]
Here's our tweet for that update https://twitter.com/CardanoDragonz/status/1468897441311490048

**Pull request merged**
