### PR TITLE
Rotatoes

### PR DESCRIPTION
**Pull request by Rotatoes**
Rotatoes Series 1 was allready veryfied - this is the new collection 
https://twitter.com/RotatoesNFT

### CODE REVIEW

**Comment by Rotatoes** [comment]
Hey :-) did i submit it correct ?

**Comment by Rotatoes** [comment]
any updates on the verification ??

**Comment by MaxJewell** [comment]
This is a good start.
What I will need you to do is to give me a link to a twitter/webpage with the Policy ID's on them to verify your identity.

Many thanks.

**Comment by Rotatoes** [comment]
Hey :-) thank you so much. So this is the official twitter: 
https://twitter.com/RotatoesNFT

These are the links to EASYCNFT were the last two Series were sold:
https://easycnft.art/en/flash/634
https://easycnft.art/en/flash/749

These are two links to my wallet which holds one of each Series. You can see the policy there:'

https://pool.pm/cad4ba2871ae168d91440e3ad1c77af4fa4cdab55bc9a3e9d472e130.blueedition11
https://pool.pm/cad4ba2871ae168d91440e3ad1c77af4fa4cdab55bc9a3e9d472e130.prismaedition48

Thank you so much

**Comment by Rotatoes** [comment]
We were verified yesterday: 
https://ibb.co/MnGXSdV
today all NFTs are unknown again ? 
Can you pls give me an update on that ?

**Comment by Rotatoes** [comment]
Hey Max, what happend to the verification? --Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 28.09.21, 17:36 schrieb MaxJewell ***@***.***>:

   
  Merged #848 into main.

**Comment by Rotatoes** [comment]
We were verified yesterday:
https://ibb.co/MnGXSdV
today all NFTs are unknown again ?
Can you pls give me an update on that ?

**Pull request merged**
