### PR TITLE
Artist Club

### PR DESCRIPTION
**Pull request by ArtistClubCNFT**
ARTIST CLUB

A collection of well known Artist of Music, Movie, Sport & Technologie. WPAPs - handmade with Love !

https://Twitter.com/Kroneworld

https://artistclub.vip

https://discord.gg/JSbfN92zzC 

https://twitter.com/KroneWorld/status/1496180334270066696

Policity iD: 60b770ac723bbaa765a2bff47d2a55655d6d871936c2b0fa6b38d55b

### CODE REVIEW

**Comment by KroneArt** [comment]
let me know if you need more Informations. We started the selling today. So we are "on chain" :-)

**Comment by ArtistClubCNFT** [comment]
i changed the twitter Neme to:

Twitter.com/ArtistClubNFT

it fits better to our Project ;-)

**Comment by TomStray** [comment]
Dear Contributor, please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by ArtistClubCNFT** [comment]
Hi Tom…

I have done it exactly like in the video. We are not Pros in these programming Things. We are Artists and try to release our already running Project. I don´t know how to get the project into an other folder, sorry. When i try to make an project in the folder „projects“ i cant find it anymore. We have the PolID on our website, we are minting though NFT Maker Pro, the sale starts without any problems, only the Verify Prozess is not possible. I think we need your support.

Thanks, have a nice day.

Krone

**Pull request closed without merging**
