### PR TITLE
Added Pandalogy

### PR DESCRIPTION
**Pull request by Pandameth**
Collection of unique 101 panda characters for phase 1
This project have storytelling

### CODE REVIEW

**Comment by Pandameth** [comment]
https://twitter.com/pandalogy101/status/1429070917393555458?s=21

**Comment by Pandameth** [comment]
https://twitter.com/pandalogy101/status/1429889902133465108?s=21

**Comment by Dean00K** [comment]
Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership. Either by way of tweeting your pull request from your project’s twitter account and providing a link here or providing a link to the project's website URL which contains Policy IDs within. Thank you.

**Comment by Pandameth** [comment]
https://twitter.com/pandalogy101/status/1429070917393555458?s=21

Policy ID in my Twitter profile history

**Pull request merged**
