### PR TITLE
Create ChimpHouse

### PR DESCRIPTION
**Pull request by chimpionclubcnft**

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool.pm with your policy ID(s) on there so that I can verify.

**Comment by chimpionclubcnft** [comment]
Website: https://chimpionclub.com/chimphouse/
Twitter: https://twitter.com/ChimpionClubNFT
Discord: https://discord.gg/vHNKzgK5Ng

Please help us check!

**Comment by chimpionclubcnft** [comment]
Dear team,
Please help us check!
Thank you so much.

**Comment by chimpionclubcnft** [comment]
Please help us check as soon as possible, thanks!

**Pull request merged**
