### PR TITLE
Added Golden Purrito Coins

### PR DESCRIPTION
**Pull request by camscoderepo**
Added Golden Purrito Coins to the list. Feel free to ask around about us and hope to contribute more in the future.

### CODE REVIEW

**Comment by Dean00K** [comment]
Dear contributor, as per the readme.md please provide adequate proof of policy ID ownership. Either by way of tweeting your pull request from your project’s twitter account and providing a link here or providing a link to the project's website URL which contains Policy IDs within. Thank you.

I'm not asking around about you. Please provide the information I need to conduct due diligence on your project. cheers.

**Comment by camscoderepo** [comment]
twitter: https://mobile.twitter.com/PurritoCoin

tweet: https://mobile.twitter.com/PurritoCoin/status/1427403434089607178

discord: https://discord.gg/DATTJfY7

Please let me know if anything else is needed.

**Comment by camscoderepo** [comment]
https://mobile.twitter.com/PurritoCoin/status/1430177530393337868 that is the official Pull request tweet, sorry for what was added above.

**Comment by Dean00K** [comment]
I've merged, but just wanted to let you know that your policy ID is set to never lock. Maybe look at changing that for series 2 or something? food for thought anyway, cheers.

**Comment by Dean00K** [comment]
ahhh shoot, i can't merge you yet, file is invalid, please remove the comma from the end of line 4.

**Comment by camscoderepo** [comment]
I agree with the Policy lock thing and will definitely be locking policies in the future. I made a mistake on that and that is my fault. Also was simply busy when uploading yesterday and should of seen the comment in the readme about twitter that is my bad. I thank you for your help with this. cheers.

**Pull request merged**
