### PR TITLE
Create ADAMON

### PR DESCRIPTION
**Pull request by Spectruhh**
Twitter: https://twitter.com/ADAMONRPG

Website: https://www.adamon.io/

### CODE REVIEW

**Comment by Spectruhh** [comment]
Tweeted out the Pull for verification : https://twitter.com/ADAMONRPG/status/1457851020290052099

**Comment by TomStray** [comment]
Dear Contributor, please add your policy IDs on lines 11 and 17 to your website or Twitter so that I can verify.

**Comment by Spectruhh** [comment]
Hi Tom, if you go to the Adamon Discord and go to the policy ids channel
you will see a list of each policy. https://discord.gg/Q8vecQy3

I also tweeted out the pull request on twitter, and the website will be
updated either tonight or tomorrow.

Here is the link to that tweet:
https://twitter.com/ADAMONRPG/status/1457851020290052099

**Comment by Spectruhh** [comment]
Thank you, There also seems to be an issue where there are two other Adamon
projects on the site that are tied to the Adamon - Founders Edition. Is it
possible to get those two removed just to keep everything clean

**Pull request merged**
