### PR TITLE
Create EL Matador

### PR DESCRIPTION
**Pull request by ELMatador69**
https://twitter.com/EL_MatadorNFT
[discord.gg/WK3YME3Z](https://t.co/u5xVVt4kDZ)
[
](https://t.co/u5xVVt4kDZ)

https://twitter.com/el_matadornft/status/1507327119172554754?s=21

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor, 
You must have a valid website that's directly linked to your project in order for me to verify this request.

**Comment by ELMatador69** [comment]
> Dear Contributor,
> You must have a valid website that's directly linked to your project in order for me to verify this request.

https://twitter.com/el_matadornft/status/1507327119172554754?s=21

**Comment by ELMatador69** [comment]
https://twitter.com/el_matadornft/status/1507327119172554754?s=21
Will this work ? I was under the impression it could also be a tweet from
our official Twitter with the policy iD and pull request link… we have
chosen not to use a website but it it is an absolute requirement we will
make one..

**Comment by ELMatador69** [comment]
Are you there?

**Pull request merged**
