### PR TITLE
Mr.Cooper

### PR DESCRIPTION
**Pull request by MrCoopernft**
Updated multiple policies.

https://mrcoopernft.wixsite.com/mrcoopernft

### CODE REVIEW

**Comment by Dean00K** [comment]
just getting to it now

**Comment by Dean00K** [comment]
Hey - So you need to add multiple projects in the one file - this is a single file with essentially five updated versions, but its the last file (add friday the 13th) that would be merged if i were to merge it. You need to go back in and include all the names of your projects and policy IDs in the one file as per the example given in the readme.md - https://github.com/Cardano-NFTs/policyIDs#readme

**Comment by MrCoopernft** [comment]
All set, can you delete my previous requests

**Comment by Dean00K** [comment]
Invalid JSON file MrCooper

**Comment by MrCoopernft** [comment]
I don’t know what that means

**Comment by Dean00K** [comment]
https://jsonlint.com/

put your inputs into this tool , it will help you out

**Review by MrCoopernft — COMMENTED** [review]
Attempted again.

**Comment by Dean00K** [comment]
It's not closed off correctly mate. still an invalid file, did you use the tool?

**Comment by MrCoopernft** [comment]
Yes I used the tool and I still am unable to get it to work. It’s frustrating that this process is not streamlined or you can’t add a comma, bracket or whatever it needs to fix it.

**Comment by Dean00K** [comment]
Okay, I'm flat out verifying other peoples requests mate, backlogged for days. you got anyone you can ask for help?

**Comment by MrCoopernft** [comment]
I understand you’re busy, likely because of the process that has been put in place. I have now submitted my policies multiple times. I am asking you for help.

**Comment by Dean00K** [comment]
If this process is too difficult to figure out maybe you're in the wrong industry, or maybe you should wait for the ecosystem to be built out more and easier for you to use.
This is the process for now. It's difficult because the Alonzo HFC hasn't happened yet. we are early, we are pioneers. I don't have time to help you get your CNFT project off the ground mate. We all have things to do. maybe hire someone to get your backend all good and working.

**Pull request closed without merging**
