### PR TITLE
Added Gold Edition project

### PR DESCRIPTION
**Pull request by firdauszahrin**
Added Gold Edition project

### CODE REVIEW

**Comment by firdauszahrin** [comment]
Added Gold Edition project

**Comment by MaxJewell** [comment]
Morning,
Please use the new JSON format in the Readme file on the home page.
https://github.com/Cardano-NFTs/policyIDs/blob/main/README.md

**Comment by Cryptoboy123** [comment]
I tweeted the pull request on Twitter. 
https://twitter.com/firzzahrin/status/1470780449077317636

**Comment by firdauszahrin** [comment]
I tweeted the pull request on twitter. 
https://twitter.com/firzzahrin/status/1470780449077317636

**Comment by MaxJewell** [comment]
There are still conflicts in your commit.
Please use the new JSON format in the Readme file on the home page.
https://github.com/Cardano-NFTs/policyIDs/blob/main/README.md
After this make a new pull request, following the read me.

**Pull request closed without merging**
