### PR TITLE
PS Max Zaxster

### PR DESCRIPTION
**Pull request by PSMaxZaxster**

### CODE REVIEW

**Comment by PSMaxZaxster** [comment]
https://twitter.com/PZaxster our twittera account where you can check policy id.

**Comment by PSMaxZaxster** [comment]
Our homepage: https://www.maxzaxster.com

**Comment by TomStray** [comment]
Dear Contributor, please add a comma to the end of line 4 and get rid of the comma at the end of line 6.

**Comment by PSMaxZaxster** [comment]
> 
> 
> Dear Contributor, please add a comma to the end of line 4 and get rid of the comma at the end of line 6.

Done. I hope i correct true one.

**Pull request merged**
