### PR TITLE
Added FourTwentyNFTs

### PR DESCRIPTION
**Pull request by KasperTheGhost420**

### CODE REVIEW

**Comment by KasperTheGhost420** [comment]
Wanting to verify my project on CNFT.IO and obtain the yellow check mark.

**Comment by TomStray** [comment]
Dear Contributor, could you please link your twitter or website with your Policy ID on it to verify.

**Comment by KasperTheGhost420** [comment]
https://twitter.com/FourTwentyNFTs

For verification

**Comment by KasperTheGhost420** [comment]
Why was this closed, my project was not verified i waited for two months :(

**Pull request closed without merging**
