### PR TITLE
Create Ash and Tray comic Season 1

### PR DESCRIPTION
**Pull request by veopixelado**
Hi @TomStray following your instructions, I have created this new policy in the Projects folder using the new readme file.I want to verify my project, I created a monthly comic strip, using NFT-MAKER pro tools and I want to drop on December, 2.

These are project social links and website:

twitter: https://twitter.com/ashandtraycomic
discord server: https://discord.gg/KygaSfJP
website: https://pixelado.art/projects/ash-and-tray-comic-strip-cardano-nft/

Because of the changes in the protocol and because I have no skills for this, I made some messy attempts to achieve this, so if its possible to delete all the "Ash and Tray" related pull requests but this, it would be great. I am sharing this also with the nft-maker team to try to speed things up.

Thank you!!

### CODE REVIEW

**Comment by veopixelado** [comment]
@TomStray I am getting a JSON error again, no idea what it means, please help me...

**Comment by TomStray** [comment]
Dear Contributor, try changing your code slightly so that it is like this:

image
I'm not sure if it will work or not, if it doesn't, I'll pass this pull request on to someone to have a look at it.

**Review by veopixelado — COMMENTED** [review]
@TomStray I just did what you told me via email and followed the screenshot you attached. Thank you! hope this helps

**Comment by veopixelado** [comment]
@TomStray updated it but receiving the same error, no idea what it means, can I allow anyone who understand this to edit directly? it's so hard for me to understand coding...  sorry to bother you..

**Comment by CNFT-io** [comment]
The file is not within the Projects Dirctory! Please make a change and then we can approve this!

**Comment by veopixelado** [comment]
Done @TomStray @CNFT-io this is the new pull request https://github.com/Cardano-NFTs/policyIDs/pull/4391

Excuse me for the mess... and thank you for your fast response

**Pull request closed without merging**
