### PR TITLE
The Blind Girl

### PR DESCRIPTION
**Pull request by IvicaCardanimeStories**
"The blind girl" is a collection by Cardanime Stories telling the story of a blind girl traveling through real and imaginary places.
Semi-bright sights, seen through the wide lens of a blind eye, painted by the hands of a rare one with translucently clear vision and creative mind.

### CODE REVIEW

**Comment by MaxJewell** [comment]
Hello, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by IvicaCardanimeStories** [comment]
Hi, yes sure.
Twitter: https://twitter.com/cardanimes?t=atWdeHGykA_PEjxxJudIoA&s=09
Website: https://cardanimestories.com/cardanime-stories
Discord: https://discord.gg/St3jaZx6av

The blind girl collection had 3 drops with 3 different policy id's
The first policy is verified but with a wrong name, the name is the name of our older project.
Here are all 3 policies:

"The blind girl" first collection policy ID:
6bbaad257be15648faf264cae3f96fe92aec0aa1e6fc62431301e627
https://cardanoscan.io/tokenPolicy/6bbaad257be15648faf264cae3f96fe92aec0aa1e6fc62431301e627

"The blind girl" second collection policy ID:
310a220fef357d50529000abf2bca016262ce071e817914f135c4699
https://cardanoscan.io/tokenPolicy/310a220fef357d50529000abf2bca016262ce071e817914f135c4699

The third drop will be minted today with this policy id: 459edd4d13630c4e5c38663c021765c492309a478ba3bf7b0e9af432

If you need any other information please tell.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by IvicaCardanimeStories** [comment]
Everything okay? The 3 policies will be verified soon?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by IvicaCardanimeStories** [comment]
Hey Max, I've noticed that the policy ID for the:

"The blind girl" second collection policy ID:
310a220fef357d50529000abf2bca016262ce071e817914f135c4699
https://cardanoscan.io/tokenPolicy/310a220fef357d50529000abf2bca016262ce071e817914f135c4699

Is verified with the right name and everything is good.

Can you please help me with two other requests?
Namely, the first collection policy id

"The blind girl" first collection policy ID:
6bbaad257be15648faf264cae3f96fe92aec0aa1e6fc62431301e627
https://cardanoscan.io/tokenPolicy/6bbaad257be15648faf264cae3f96fe92aec0aa1e6fc62431301e627

has a name of our old project "CardanimeStoriesSpecialEURO2020"
Can you please change this since it's wrong and add it in "the blind girl" project?

The second request is, can you please verify the newest drop of the same collection under the same name "the blind girl" this is the policy id of it:

"The blind girl" third collection policy ID:
459edd4d13630c4e5c38663c021765c492309a478ba3bf7b0e9af432
https://cardanoscan.io/tokenPolicy/459edd4d13630c4e5c38663c021765c492309a478ba3bf7b0e9af432

Thank you in advance.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
