### PR TITLE
Ada Power

### PR DESCRIPTION
**Pull request by Okiyada**
https://twitter.com/VXLKTPM3bK81SD0/status/1429892938339860481?s=19

### CODE REVIEW

**Comment by Dean00K** [comment]
Hey, thanks for the pull request. I can't verify you, yet. you've only given me a twitter account with 2 followers and no information about your project. Can i get some more information and a blurb about you/artist/project? From what I can tell, the policy ID is already locked and it's only one single token? Are you a project? I need to do adequate due diligence here. hope that makes sense.

**Comment by Okiyada** [comment]
> Hey, thanks for the pull request. I can't verify you, yet. you've only given me a twitter account with 2 followers and no information about your project. Can i get some more information and a blurb about you/artist/project? From what I can tell, the policy ID is already locked and it's only one single token? Are you a project? I need to do adequate due diligence here. hope that makes sense.

Hello, thanks for your comment. I am a new artist base in Thailand. This is my first project. and because i want To prevent copying of the work, I was recommended by a friend of mine to do this.

for the question you ask
1. My Name (Artist): Okiyada
2. My Project’s name : Ada Power Project
3. My Twitter : https://twitter.com/adapowernft?s=21

4. The question is “Is it a single token?” Ada Power Project plans to launch 1000 nft (AdaPower001-AdaPower1000). I am not sure if it should be called a single token or not?

If my answer is irrelevant to the point? Please give me some advice
thank you.

**Comment by Dean00K** [comment]
Okay cool, So you can mint multiple NFTs under one single policy ID which would make everything much easier moving forward. Just something to think about. When I say single token, what I mean is, when i look up your policy ID (because you only had one policy ID on the initial commit) all I can see is one single token. So that's all the information I had. Good to know more about the project. 1000 single tokens on 1000 individual policy IDs will get a bit complicated if that's what you were thinking of doing.
I suggest getting set up to be able to mint all tokens under one single policy ID. Other than that, all good, I wish you luck with your project.

**Comment by Okiyada** [comment]
> Okay cool, So you can mint multiple NFTs under one single policy ID which would make everything much easier moving forward. Just something to think about. When I say single token, what I mean is, when i look up your policy ID (because you only had one policy ID on the initial commit) all I can see is one single token. So that's all the information I had. Good to know more about the project. 1000 single tokens on 1000 individual policy IDs will get a bit complicated if that's what you were thinking of doing.
> I suggest getting set up to be able to mint all tokens under one single policy ID. Other than that, all good, I wish you luck with your project.

How to set up to mint all token under one single policy?
Thanks you for the Advice.

**Comment by Dean00K** [comment]
You're gonna have to talk to whichever service you use for minting.

**Comment by Okiyada** [comment]
I was minting at nft maker

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Dean00K** [comment]
Then you need to organise with them.

**Comment by Okiyada** [comment]
I will do it,Thanks you.

รับ Outlook สำหรับ Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
