### PR TITLE
Project update - "Forest Tikis | The Beginning of a New Era" collection

### PR DESCRIPTION
**Pull request by Marinhaaas**

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

**Comment by Marinhaaas** [comment]
> Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there so that I can verify.

Hey TomStray!

Confirmation tweet: https://twitter.com/ForestTikisCNFT/status/1460775829508665344
Website: https://www.foresttikis.com (policy on footer)

Thanks for your support!

**Comment by Marinhaaas** [comment]
Hey TomStray!

Confirmation tweet:
https://twitter.com/ForestTikisCNFT/status/1460775829508665344
Website: https://www.foresttikis.com (policy on footer)

Thanks for your support!

TomStray ***@***.***> escreveu no dia terça, 16/11/2021 à(s)
17:19:

**Comment by TomStray** [comment]
Please add the first policy ID you have in your code to your website, twitter or discord.

**Comment by Marinhaaas** [comment]
Done!

Now you can check it on footer website, FAQs on Discord and on twitter
thread!

Greetings!

TomStray ***@***.***> escreveu no dia quinta, 18/11/2021 à(s)
10:08:

**Pull request merged**
