### PR TITLE
Added Danraco NFT

### PR DESCRIPTION
**Pull request by Danraco**
See proof of ownership on this tweet that I just did: https://twitter.com/danraco/status/1429435273427968004

### CODE REVIEW

**Comment by Dean00K** [comment]
Hey mate, all of your policy IDs will remain open. They never lock. Your twitter has 9 followers.. anywhere i can get some more information? a project website or a discord channel?

**Comment by Dean00K** [comment]
The 2nd last policy ID doesn't work at all*

**Comment by Danraco** [comment]
Sorry I'm a bit new to this! I'm just starting my NFT collection and it has been a bit quiet. I'm using EasyCNFT service, 2nd last NFT has not been sold any - that's why it doesn't work at all :( You can find my discord server here: https://discord.gg/9CfEYmQmeW (also policy id's can be found from there). Let me know if you need more information. Thanks!

**Comment by Dean00K** [comment]
Okay, I understand if you're new to this. But I need to verify CNFT projects. Do you understand what I mean about your policy IDs remaining open? It means, that you could set up a rare NFT drop and only have 10 NFTs and sell them all for 1000 ADA each, and everyone that buys them feels happy and special because they have a really rare NFT.. but the policy ID never locks, and you could technically go back and mint another 5000 of the same NFT and sell them and you've now diluted the market of what was a rare NFT and now is not a rare NFT.. that make sense? I can't verify you mate. Locked policy IDs create trust. Yours never locks.

**Comment by Danraco** [comment]
I did not know that it works like that. Sure, now i understand that you can't verify, it is obvious. Thanks for all explanations!

**Pull request closed without merging**
