### PR TITLE
Added Cardano NFT Collection

### PR DESCRIPTION
**Pull request by dritch666**
Twitter https://twitter.com/Daryl66159451
https://cardanonftcollection.godaddysites.com/nft-policies
https://twitter.com/daryl66159451/status/1448571375937937414?s=21
Hi Policy ID added to my twitter account & added to my Web Site.
https://cardanonftcollection.godaddysites.com/

### CODE REVIEW

**Comment by MaxJewell** [comment]
Until I can see the Policy ID's on the webpage I can not verify you

**Comment by dritch666** [comment]
> 
> 
> Until I can see the Policy ID's on the webpage I can not verify you

Hi Policy ID added to my twitter account & added to my Web Site.
https://cardanonftcollection.godaddysites.com/

**Comment by dritch666** [comment]
> 
> 
> > Until I can see the Policy ID's on the webpage I can not verify you
> 
> Hi Policy ID added to my twitter account & added to my Web Site. https://cardanonftcollection.godaddysites.com/nft-policies

Hi Policy ID added to my twitter account & added to my Web Site.

Twitter https://twitter.com/Daryl66159451
https://cardanonftcollection.godaddysites.com/nft-policies

Could you please verify my project.

**Comment by dritch666** [comment]
Hi What do I need to do next?

**Comment by dritch666** [comment]
Can you please tell me why this was closed?

**Pull request closed without merging**
