### PR TITLE
Create TuomoCNFTs

### PR DESCRIPTION
**Pull request by omout**
https://twitter.com/tuomomout

### CODE REVIEW

**Comment by MaxJewell** [comment]
Morning, 
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by omout** [comment]
Hi,
https://twitter.com/tuomomout

Thanks,

**Comment by KaiNFT** [comment]
Please display evidence of your policy ID's on your twitter.

**Comment by MaxJewell** [comment]
Due to inactivity on this pull request we will have to close this request. 
Feel free to open a new request when you have gathered everything you need to be verified.

**Pull request closed without merging**
