### PR TITLE
Added Rosemary Herbivore

### PR DESCRIPTION
**Pull request by ricardo621**

### CODE REVIEW

**Comment by MaxJewell** [comment]
I can verify the first two Policy ID's. May I have a link to all the other ones. Many thanks.

**Comment by ricardo621** [comment]
Hi Max,

Thank you very much – I'd kinda given up thinking they'd be verified as there are so many to deal with.
Here's a link to all the NFT's I require verification for. Apologies in advance if there's any errors. I have absolutely no idea what I'm doing!

Basil Herbivore:
https://richardhood.squarespace.com/cardoodlr
https://www.cnft.io/token.php?id=614d97f0873fd558fade75cc
https://github.com/ricardo621/policyIDs/commit/9bee5b876bd6754f83ad2af2c4a94eb88ae67c84

Macy Herbivore:
https://richardhood.squarespace.com/cardoodlr
https://www.cnft.io/token.php?id=614d97a36df1f0f6a1e4220f
https://github.com/ricardo621/policyIDs/commit/d8388369b1a757f272f805612b7f3c65f22b6584

Ginger Herbivore:
https://richardhood.squarespace.com/cardoodlr
https://www.cnft.io/token.php?id=613f6ea6c7748f82b760dd97
https://github.com/ricardo621/policyIDs/commit/d562f0b564b3a38de99b07fd01a178c5a08610ab

Rosemary Herbivore:
https://richardhood.squarespace.com/cardoodlr
https://www.cnft.io/token.php?id=613f6e9cf86a622fca98f3bd
https://github.com/ricardo621/policyIDs/commit/efcfc7c6caa87d2f5c21e74013d577bdcbbc28cd


–
Richard Hood


________________________________

**Comment by MaxJewell** [comment]
I can verify all the Herbivore, however I need the links to the other commits.

**Comment by ricardo621** [comment]
I thought I’d just sent them to you?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ricardo621** [comment]
Sorry, I misunderstood! I’ll get the commits together  for the others. Thanks Max :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ricardo621** [comment]
Funnybones:
https://github.com/ricardo621/policyIDs/commit/24681e9bdf3fd0ff33274012046ffb9abd799b42

Don't Shoot:
https://github.com/ricardo621/policyIDs/commit/b16dec20d746eb38d80b1df72280c697fb1c828f

Rex:
https://github.com/ricardo621/policyIDs/commit/0585265196ef6b7eec628e7f7fc8e26548e6b4d3

Zebedee:
https://github.com/ricardo621/policyIDs/commit/5e25225013bf3ea6469eab759966870dc7b5817d

Don't Touch:
https://github.com/ricardo621/policyIDs/commit/9e6da95b6c7ecc1ac1760b58c68be2aa7bbafeba


Thanks Max


–
Richard Hood


________________________________

**Comment by ricardo621** [comment]
Hi, my NFTs still don’t appear to have been verified? I’d imagine this is apparent when you get a little yellow tick on the assets description page. It’s been nearly two months. I thought you said they’d been verified?

Thanks,

Richard

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
