### PR TITLE
Update NeonSparrow

### PR DESCRIPTION
**Pull request by Tattoosbyjj**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.

Many thanks.

**Comment by Tattoosbyjj** [comment]
Hey Max, yeah I’ve already verified my twitter account but my twitter is @neonsparrownft and all my policy ids are in the alt tags of previous posts. Thank you
Have a great day
JJ

**Comment by Tattoosbyjj** [comment]
> Would you be able to add a link to a twitter account/website to verify your identity and with all the Policy ID's on them.
> 
> Many thanks.

Hey Max, yeah I’ve already verified my twitter account but my twitter is @neonsparrownft and all my policy ids are in the alt tags of previous posts. Thank you
Have a great day
JJ

**Comment by KaiNFT** [comment]
Dear Contributor,

Please can you forward me a direct link to find your Policy ID's

Many thanks - Kai

**Comment by Tattoosbyjj** [comment]
> Dear Contributor,
> 
> Please can you forward me a direct link to find your Policy ID's
> 
> Many thanks - Kai

policy IDs are embedded in ALT text of posts made on twitter. Twitter address https://twitter.com/neonsparrownft?s=21

**Comment by MaxJewell** [comment]
They are not within the alt tags, could you add them in your bio instead?

**Comment by Tattoosbyjj** [comment]
> They are not within the alt tags, could you add them in your bio instead?

I have previously been verified by CNFT with the alt text within my media. There is not enough space to add policy ids in my bio.

can you suggest an alternative?

**Comment by MaxJewell** [comment]
you will need to all of them so I can verify you

**Comment by Tattoosbyjj** [comment]
> you will need to all of them so I can verify you

https://twitter.com/neonsparrownft/status/1455265669772103694?s=21

**Comment by Tattoosbyjj** [comment]
> you will need to all of them so I can verify you

Can I add a link to Linktree or a file where I can add my policy IDs?

**Comment by Tattoosbyjj** [comment]
> Dear Contributor,
> 
> Please can you forward me a direct link to find your Policy ID's
> 
> Many thanks - Kai

Hey there, OK so I’ve figured this be the best solution.

I’ve linked my Linktr.ee (linktr.ee/Tattoosbyjj) account to my twitter (@neonsparrownft)

if you scroll to the bottom of my linktr.ee it will give you a link to “Neon Sparrow ID’s”

that will give you all my policy IDs that I currently own! I’m currently trying to find the policy IDs for the NFTs I have sold but am currently on vacation and operating on an IPhone. I hope all this is OK

If there is any issues please let me know
Thank you
JJ

**Comment by AnOnlineGuy** [comment]
We have made another change to the GitHub that you should be aware of. 

I need you guys today to go through all the PRs and close them with this message. 

‘Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
