### PR TITLE
Create Chronicles of the Blade

### PR DESCRIPTION
**Pull request by CryptoBoons**

### CODE REVIEW

**Comment by CryptoBoons** [comment]
https://twitter.com/CryptoBoonsInc

We made it the bio on the profile.

**Comment by TomStray** [comment]
Dear Contributor, please remove the comma at the end of line 7. As well as this, please change the square bracket on line 8 so that it is parallel with lines 2, 3, 5 and 6.

**Comment by CryptoBoons** [comment]
Absolutely! Thank you for getting back to us. We will have this done today
and follow up when it is completed.

**Comment by CryptoBoons** [comment]
Done

**Comment by CryptoBoons** [comment]
Does this mean we have been verified?

**Pull request closed without merging**
