### PR TITLE
Added Absolute Units project

### PR DESCRIPTION
**Pull request by Absoluteunitsnft**
My hope is that this project will be strong and give joy to many.

### CODE REVIEW

**Comment by MaxJewell** [comment]
Please leave a link to twitter/webpage for proof with policy ID's.

**Comment by Absoluteunitsnft** [comment]
https://twitter.com/AbsoluteunitsNF

**Comment by Absoluteunitsnft** [comment]
https://twitter.com/AbsoluteunitsNF

**Comment by Absoluteunitsnft** [comment]
Thanks!

**Pull request merged**
