### PR TITLE
Adverse sold on Easy CNFT

### PR DESCRIPTION
**Pull request by KosmosKarl**
Sale page
https://easycnft.art/en/flash/239

### CODE REVIEW

**Comment by Dean00K** [comment]
Dear contributor, thank you for the pull request and twitter link – Apologies, while the cnft.io website is down, could you please provide a pool.pm link to your NFT project for verification? Thank you.

**Comment by KosmosKarl** [comment]
Hi
Here's some links to project assets on Pool.pm
https://pool.pm/f8cf05076cade023bab6bd9b4ad4d668b82369c06fb2e89a5c7b7978.ADX53
https://pool.pm/f8cf05076cade023bab6bd9b4ad4d668b82369c06fb2e89a5c7b7978.ADX128
https://pool.pm/f8cf05076cade023bab6bd9b4ad4d668b82369c06fb2e89a5c7b7978.ADX17

**Comment by Dean00K** [comment]
these are really cool - are you aware your policy ID will never lock? Part of the verification process requires policy IDs to be either locked, or a date set for future locking. There are exceptions to this, have you got any more information on the project for me to do adequate due diligence before verification?

**Comment by KosmosKarl** [comment]
Thank you for reviewing and i glad you appriciate the art.  
The project used generative adversarial networks A.I technology to create unique planet images.  The first 150 planets (1 of 1 NFTs) were sold on https://easycnft.art/en using their vending machines and sold out within 20 hours.  When setting up the sale page i did not select 'policy time lock' date option (I was not aware this would havepotential varifing issues and did not fully understand the option).
I have contacted easy CNFT and it is not possible to lock the NFTs after they have been minted.  I have no option to add to the project using the policy ID. 
I am using CNFT to add more NFTs to project using their vending machine system, these will be policy time locked with a new policy ID.  There will be a 500 max supply of unique AdaverseX planets (including the 150 already minted in the above policy).   I would greateful the orgianal 150 NFTs could be verfied as they have been purchased using the vending machine by collectors.

**Pull request merged**
