### PR TITLE
Order Of Otranto - Abbey Mint

### PR DESCRIPTION
**Pull request by xadram**
Twitter: https://twitter.com/OrderofOtranto
Website: https://orderofotranto.io/
Discord: https://discord.gg/CjXhwZY6Yq
Policy ID: 

Policy ID is on the website for confirmation

### CODE REVIEW

**Comment by xadram** [comment]
Twitter: https://twitter.com/OrderofOtranto
Website: https://orderofotranto.io/
Discord: https://discord.gg/CjXhwZY6Yq
Policy ID: 

Policy ID is on the website for confirmation

**Review by xadram — COMMENTED** [review]
Twitter: https://twitter.com/OrderofOtranto
Website: https://orderofotranto.io/
Discord: https://discord.gg/CjXhwZY6Yq
Policy ID: 

Policy ID is on the website for confirmation

**Comment by KaiNFT** [comment]
Dear Contributor, 

This request will now be closed, make a new ticket with the following criteria; the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by xadram** [comment]
@KaiNFT the file is in the projects directory and the json is valid. Can you provide more details on the error. I've tried a few times now

image

**Pull request closed without merging**
