### PR TITLE
Update cardinos

### PR DESCRIPTION
**Pull request by przcntn**
Adding proper golden tix

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by przcntn** [comment]
I have had the project since May and its been verified like 10 times already so please just put it through. 
Cardinos.io.

**Comment by KaiNFT** [comment]
Hi Contributor,

I understand however I still need to see the evidence of the Policy ID via social media/website.

Sorry for any inconvenience caused.

**Comment by przcntn** [comment]
Its in the discord. https://discord.gg/3RuwuG4c

**Comment by KaiNFT** [comment]
Dear Contributor,

The policy ID in line 34 is not visible in your discord.

**Comment by itsmestale** [comment]
Thanks for being so thorough @KaiNFT.
Apologies for stepping in here, in this case I will just verify this as I have been able to verify these guys in the past by hand.
Absolutely right though, they should have that accessible to you. Keep it up <3

**Pull request merged**
