### PR TITLE
Update Cardamigos project adding policy for 3D

### PR DESCRIPTION
**Pull request by JhonatanMdz**
This is to add a new policy ID for the new 3D Cardamigos collection

Website with updated policies:  https://www.cardamigos.io/About 
Twitter:  https://twitter.com/cardamigosCNFT 
Website: https://www.cardamigos.io/

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, please make sure that line 5 is parallel with line 4 and line 9 is parallel with line 8.

**Comment by JhonatanMdz** [comment]
Identation fixed

**Comment by KaiNFT** [comment]
Dear Contributor,

Apologies about the response time, Please make the necessary adjustments to your JSON file in order for me to merge the pull request.

**Comment by MaxJewell** [comment]
Due to inactivity on this pull request we will have to close this request. 
Feel free to open a new request when you have gathered everything you need to be verified.

**Pull request closed without merging**
