### PR TITLE
Add TheHiddenOrder

### PR DESCRIPTION
**Pull request by TheHiddenOrder**
Initated Project The Hidden Order

### CODE REVIEW

**Review by TheHiddenOrder — COMMENTED** [review]
Waiting on Verification

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy IDs on there so that I can verify. Also, please remove the space on line 19, just after the policy ID but before the ending speech mark.

**Comment by TheHiddenOrder** [comment]
https://twitter.com/ThHddnOrdr/status/1445383348650745870?s=20

Link to twitter for Policies

**Comment by TheHiddenOrder** [comment]
Please reverify. https://twitter.com/ThHddnOrdr/status/1445383351259607044

**Comment by TheHiddenOrder** [comment]
Great! When will it be up and running? On Cnft.io?

**Pull request merged**
