### PR TITLE
Added Galactic Guardians

### PR DESCRIPTION
**Pull request by GalacticGuardians**

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide evidence of your policy ID via social media or a website in order for me to merge the pull request.

**Comment by GalacticGuardians** [comment]
No problem

https://galactic-guardians.com/

https://twitter.com/GGuardians_CNFT

let me know if you need anything else!

GG Team

**Comment by KaiNFT** [comment]
Dear Contributor,

Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by GalacticGuardians** [comment]
Should be good now :)

**Comment by GalacticGuardians** [comment]
Everything all good?

**Pull request merged**
