### PR TITLE
Violintiles

### PR DESCRIPTION
**Pull request by Violintiles**
Paolo Leonori Violin with every one of my house's tile

https://twitter.com/violintiles

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

**Comment by Violintiles** [comment]
> Dear Contributor,
> 
> Please make the necessary adjustments to your JSON file in order for me to merge the pull request. If you can't find the issue, please use a JSON validator; https://jsonlint.com/

I think i fixed it already. First time doing this thank you for helping

**Comment by KaiNFT** [comment]
Dear Contributor, 

You must have a website for your project that matches your project name in order for me to merge the pull request

**Comment by KaiNFT** [comment]
Needs to be a website made for the project.

**Pull request closed without merging**
