### PR TITLE
CNFTStable

### PR DESCRIPTION
**Pull request by CNFTSTABLE**
Creation

### CODE REVIEW

**Comment by CNFTSTABLE** [comment]
Tweet Proof

https://twitter.com/CNFTStable/status/1426859073463406598

**Comment by CNFTSTABLE** [comment]
https://twitter.com/CNFTStable/status/1426859073463406598

**Comment by Dean00K** [comment]
Hey - I'm giving Stale a hand with github - Can you confirm if you still need this to be merged? Looks like the last commit was just a deletion of the previous commits... LMK, cheers.

**Pull request closed without merging**
