### PR TITLE
Added new policy

### PR DESCRIPTION
**Pull request by FrigidOptics**

### CODE REVIEW

**Comment by MaxJewell** [comment]
Could we have a link to a twitter/webpage which have provided the Policy ID's you are requesting.

Thanks.

**Comment by FrigidOptics** [comment]
https://twitter.com/FrigidOptics/status/1443998496248500229

what do i do going forward when i have new policies to add, but the previous request like this one was not  acted on yet ? Can i just do multiple pull requests while one is open or something ?

**Comment by MaxJewell** [comment]
This tweet does not have all the policy ID's you want merging. Please provide this and we can move forward

**Comment by FrigidOptics** [comment]
please put someone else in charge. these newer people done screwed up my customers and everything for months.

**Pull request closed without merging**
