### PR TITLE
Added floating Heads Club

### PR DESCRIPTION
**Pull request by tmsgo-iscte**
Website: www.floatingheadsclub.com
For any doubts or corrections please email us at floatingheadsclub@gmail.com or message us @discord

### CODE REVIEW

**Comment by KaiNFT** [comment]
Dear Contributor,

Please provide proof of Policy ID via website or social media so I can merge the pull request.

**Comment by tmsgo-iscte** [comment]
Sorry for the inconvenience,
Policy added to our website:
www.floatingheadsclub.com
Thank you!

**Comment by tmsgo-iscte** [comment]
> Dear Contributor,
> 
> Please provide proof of Policy ID via website or social media so I can merge the pull request.

Website: www.floatingheadsclub.com
For any doubts or corrections please email us at floatingheadsclub@gmail.com or message us @discord

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Pull request closed without merging**
