### PR TITLE
Create Project NordicArt

### PR DESCRIPTION
**Pull request by Jumpery**

### CODE REVIEW

**Comment by Jumpery** [comment]
Proof : addr1qysaes98vfd2zqzf9ej05u2xwc7zh5355gvj2cw6xtepzde4hfxk3neap7h4pgfq3a0k6wlsetgnshlk45l6mlsmgrnqx22at5

**Comment by Jumpery** [comment]
Also , my twitter account https://twitter.com/CnftsAda (set the project name in my twitter name)

**Comment by TomStray** [comment]
Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

**Comment by Jumpery** [comment]
> Please edit your Pull Request, the new file must be within the 'Projects' directory. Please check the README.md file for further information.

I have no idea how  to do that , already watched the readme.md file 5 times :(

**Pull request closed without merging**
