### PR TITLE
Created Alpha Pixel

### PR DESCRIPTION
**Pull request by tinosestric**
This is an art project of huge importance.  prof. Antonio Rollo, is a first Italian digital artist exhibited in any art gallery/museum or other institution with his digital work. I'm submitting a project that I am assisting him with. 
asist. Martin Petrič.
On behalf of prof. Antonio Rollo, accademia di belle arti di Bari, Italy.

### CODE REVIEW

**Comment by tinosestric** [comment]
And there are couple of mine artworks to verify too. Cheers.

**Comment by tinosestric** [comment]
And meanwhile prof. Antonio Rollo did the website at: 0280.org/alphapixel, you can check the domain owner and other folders on the domain. If you need any other form of verification please write me an email to martin.petric@aluo.uni-lj.si, or Antonio's mail a.rollo@accademiabari.it, thank you.

**Comment by TomStray** [comment]
Dear Contributor, please update you links as when I click on them, this is what I see:

image

**Comment by tinosestric** [comment]
Dear Tom.
That's strange.
i'm sending links again here.
There was a maintenance on CNFT.io, and i couldn't see where they were,
that's why i'm sending links so late.

https://www.cnft.io/token/618142e23ff43a2e406c4d63
https://www.cnft.io/token/618143133ff43a2e406d0314
https://www.cnft.io/token/618143433ff43a2e406db2b6
https://www.cnft.io/token/618143913ff43a2e406ed7b6

Best, Martin

**Comment by TomStray** [comment]
Dear Contributor, please send a link to your twitter or website/CNFT.io/Pool with your policy ID(s) on there for your "Alpha Pixel" code.

**Comment by tinosestric** [comment]
Dear Tom,

the links have changed due the CNFT update,

here is the link,

https://www.cnft.io/token/618143913ff43a2e406ed59c

Thank you.

Martin
lp Martin

**Comment by tinosestric** [comment]
Awesome, thanks!
lp Martin

**Comment by tinosestric** [comment]
Hi Tom,
sorry to bother you, but didn't the merging of my pull request make the
NFTs verified?
Just asking, because i steel don't se the yellow sign besides the NFTs.
Thank you!
and happy 2022!
Martin

**Pull request merged**
