### PR TITLE
Update Cardano Flowers

### PR DESCRIPTION
**Pull request by Proudik**

### CODE REVIEW

**Comment by TomStray** [comment]
Dear Contributor, there is some conflicts with your commit, this means that you have already merged some of the policy IDs in your commit. Please remove lines 20 to 29 and then remove the comma at the end of line 19.

**Comment by Proudik** [comment]
Hello Tom. I am confused. I'd like to add those policies for the project Cardano Flowers. I'm not sure why do I have to delete them? 
https://www.coruna.io/policy-ids

**Comment by TomStray** [comment]
Dear Contributor, conflicts with your commit means that in a past pull request you have already verified those particular policy IDs so I am not able to verify them again.

**Comment by Proudik** [comment]
Hello. Yes, some of the policy IDs were verified already. But those were the ones on rows from 1 to 18. So if I remove rows 20-29, nothing new will get verified?

**Comment by TomStray** [comment]
Dear Contributor, if you are sure that it is the IDs from 1 to 18 that have already been verified, then remove them but it is highlighting as 20 to 29 as the conflicts for me. Just make sure that is correct and then I'll check again after they have been removed.

**Comment by Proudik** [comment]
Thank you Tom,

Rows with verified IDs were removed now. Changes in Patch-13.

Thank you

**Pull request closed without merging**
