### PR TITLE
Add first project Diaspora

### PR DESCRIPTION
**Pull request by masterjedikid0**
To add my Policy ID to get my project verified

### CODE REVIEW

**Comment by masterjedikid0** [comment]
I have no website or twitter for project, withdrawing my request

**Comment by masterjedikid0** [comment]
Sorry, created a Twitter account hopefully that is enough. https://twitter.com/DiasporaShips

**Comment by masterjedikid0** [comment]
Sorry, closed accidentally. Twitter account https://twitter.com/DiasporaShips

**Comment by Dean00K** [comment]
I need more info mate. I can't do adequate due diligence on a project with a twitter profile showing 0 followers / 0 following. Also, your policy ID comes up as 'unknown'. I can't verify if its locked or not.

**Pull request closed without merging**
